### ISSUE TITLE
Survival nested gallimimus uses old model

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#1]
## Expected Behavior

Expected New model and skin to be used once nested as a gallimimus

## Current Behavior

Once nested as a gallimimus on survival game mode, player will have the old model and old skin.
Sounds are working properly (that is: using juvenile/hatchling sounds)
Here's a screenshot:
![theisle-win64-test_2018-02-24_22-50-39](https://user-images.githubusercontent.com/35901313/36637421-104baa14-19ba-11e8-8442-ba1c476a2dfb.jpg)

Note: Once the player reaches the Adult stage, the new model and skin will be use
Tested on : Official Dev 2

## Steps to reproduce

-On character selection menu, select the nest option (make sure that there are eggs on the nest)
-Spawn
-You will know have the Old Adult gallimimus model

## Build Information
[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1755657/TheIsle.log)
> **Game Version:** 0.1.34.1 - 2554345 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed.
