### ISSUE TITLE
Female Adult T.Rex skin not being applied initially

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#10]
## Expected Behavior

On character selection screen, Adult Tyrannosaurus Female Skin to be displayed after selecting female gender option.
Female Skin to be used after confirming

## Current Behavior

On Character selection screen, Adult Tyrannosaurus Female skin isn't displayed after selecting female gender option.
Here's a screenshot:

![theisle-win64-test_2018-02-27_20-43-20](https://user-images.githubusercontent.com/35901313/36761685-f5a8558a-1bfe-11e8-8a40-0276948f441d.jpg)

Initially, after selecting Female Gender, Male skin will be used. Note: Player can still place a nest.
However, after Safe Logout Female skin will be used.
Screenshots:
Before Safe Logout:
![theisle-win64-test_2018-02-27_20-34-08](https://user-images.githubusercontent.com/35901313/36761724-2bccc510-1bff-11e8-97fb-3989ccfd17f0.png)
After Safe Logout:
![theisle-win64-test_2018-02-27_20-35-55](https://user-images.githubusercontent.com/35901313/36761747-4ee54e3c-1bff-11e8-97cb-7943cb7903fc.png)

## Steps to reproduce

-On character screen (Sandbox) select Tyrannosaurus Adult.
-Pick Female Gender
  -Notice that there's no skin difference
-Confirm
-Safe Logout
-Notice that after rejoining, Female skin will be used, instead of Male.

Notes:
-Simple logout and Immediate rejoin will not grant you Female skin.
-Simple logout and rejoin after at least 1 minute will grant you Female skin.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1765103/TheIsle.log)

> **Game Version:** 0.1.34.2 - 2561560 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.0

**Comment by Emanthealmighty** [comment]
Retested on 22 April 2019
Adult Tyrannosaurus spawns in with the correct skin.
