### ISSUE TITLE
Opening interface while eating/drinking causes player to get stuck in animation

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#101]
## Expected Behavior

Opening the interface such as scoreboard or escape menu should not cause the player to get stuck in their eating/drinking animation.

## Current Behavior

If you are eating/drinking and open the scoreboard or escape menu, the player will find themselves stuck in their looping animation until they hit E again.

## Steps to reproduce

1. Spawn as anything.
2. Find water and drink by holding E.
3. While holding E to drink, hold tab to open the scoreboard, then let go of E.
4. When you close the scoreboard by hitting tab again, you will be stuck in the looping animation.

## Build Information

> **Game Version:** 0.1.36.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.0
