### ISSUE TITLE
Rain graphical bugs

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#103]
## Expected Behavior

When raindrops land in a puddle, a rippling effect is created.  When landing on a hard, convex, or otherwise non-water surface, ripples should not occur.  

Puddles should form on flat or concave areas only during rain.

## Current Behavior

Currently, raindrops create ripples on dinosaur surfaces as well as the ground.  Puddle effects are displayed on the terrain globally.  This includes hillsides and other surfaces where puddles could never form. The entire map is coated in a puddle layer during the rain, except for trees and rocks it seems.

## Steps to reproduce

Simply observe rain graphics in-game, on your dinosaur or in areas described.

## Build Information

Dev branch version 0.1.36.8
Windows 10 machine
Client role

Below is a video of both effects.

https://youtu.be/1OCCTBaPS-A

**Comment by dinosauriac** [comment]
There's a height mask that ensures ripples only appear on the top of your character, they transition into less intense rivulets at a certain angle. Similar stuff will probably get added to props soon, though getting puddles to only show on flat surfaces may be a bit much to ask.
