### ISSUE TITLE
Parasaurolophus can attack while getting out of resting,cutting the animation.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#104]
## Expected Behavior

Parasaurolophus to be unable to attack while getting out of resting animation.

## Current Behavior

Parasaurolophus can attack while getting out of resting animation, cutting the animation

Video evidence:
https://youtu.be/jTv6jJb8lgY

## Steps to reproduce

-Spawn as an Adult Parasaurolophus.
-Sit down.
-Get up and attack with LMB.
-Notice that the animation will cut/pop and the attack animation will be played.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1926021/TheIsle.log)

> **Game Version:** 0.1.36.8 (development)

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added Parasaurolophus to #16 

Thanks!
