### ISSUE TITLE
Players can clip through canyon rocks to hide

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#106]
## Expected Behavior

Players should not be able to hide in the rocks at the canyons.

## Current Behavior

Players can currently hide in the rocks at the canyon, making it easy to grow.

![image](https://user-images.githubusercontent.com/30550499/38964826-e5e4a664-4370-11e8-96c8-9fe30e398cf1.png)

## Steps to reproduce

1. Spawn as a juvenile.
2. Go to the canyon.
3. Clip through a rock and rest to hide in it.

## Build Information

> **Game Version:** 0.1.36.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
This should be fixed since 0.1.36.9
