### ISSUE TITLE
Water Ripples below Water's surface

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#107]
## Expected Behavior

Thenyaw Water Ripples appear seamlessly with the rest of the water, on the same plane as the rest of the unaffected water. Ripples can be seen from all angles.

## Current Behavior

Water ripples are seen easily from directly above, but if you view the water from the side, you can see that the ripples are not aligned with the main watersource. The ripples are unable to be seen from the side view.

## Steps to reproduce

Walk/run in water, observe ripples from all angles.

## Build Information

> **Game Version:** 0.1.36.8 (development) 

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by Hypno123** [comment]
Could we a video/screenshot of this to make it clearer?

**Comment by Hypno123** [comment]
As Mel said. Water ripples should appear on top of the water, not underneath it.

![image](https://user-images.githubusercontent.com/30550499/39390247-b8a7f514-4a89-11e8-97d2-f6d33d4344e2.png)

**Comment by dinosauriac** [comment]
Still not entirely sure what's going on here. It looks like the surface waves might be remaining visible when they should be covered by the character perhaps?
