### ISSUE TITLE
Lava makes dinos look metalic

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#108]
[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1926578/TheIsle.log)
# Expected Behavior

Lava should cast an orange light onto creatures the same way that fire does:
https://steamuserimages-a.akamaihd.net/ugc/2425627755265009878/AF627CBBA0DA5FFF1BFACF3A49E541091B5F5B53/

## Current Behavior
Dinos that stand near lava on Thenyaw instead have a super bright, metallic orange glow to them (even on the side that isnt facing the lava):
https://steamuserimages-a.akamaihd.net/ugc/2443642466615343422/E0BC9A387AE7CDEBC8782BD7F47DC64BBA8415A8/
[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1926399/TheIsle.log)

## Steps to reproduce

Simply get close to lava on Thenyaw Island

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.36.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
In the screenshot that is a side effect of being rained on, with the glisten of the water picking up the lava light. I think shadows are turned off for the lava light currently for performance reasons, which is why it might appear omnidirectional.
