### ISSUE TITLE
Running into trees on Thenyaw plays a wooden surface Foostep sound

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#109]
## Expected Behavior
Most of the time, when i sprint right into a tree as any creature, no sound plays at all, so im assuming that is the intended outcome.

## Current Behavior
When I sprint into a tree as a utah (havent been able to replicate it as anything else so far, but it happens VERY inconsistently as utah, so it might just be that way for all dinos) i sometimes hear a single wooden footstep sound effect, like the ones you hear on the test level on the wood surface. I hear it for a split second, then its gone. Most of the time, when i sprint into a tree it just plays no sound at all.

## Steps to reproduce
Sprint into a tree as a Utahraptor (ive only ever had it happen to me as an adult). It usually plays no sound, so just keep trying until it does. It may help to sprint downhill into one.

## Build Information

> **Game Version:** 0.1.36.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client
[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1926576/TheIsle.log)

**Comment by Hypno123** [comment]
Can you get a video of this?

**Comment by Hypno123** [comment]
Managed to replicate this. The wooden sound is made when your foot touches a tree - I actually think it makes more sense for it to stay this way.
