### ISSUE TITLE
Juvenile Puerta deals no damage

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#11]
## Expected Behavior

The juvenile puerta should be able to deal damage with all attacks. (Stomp, tail whip and kick.)

## Current Behavior

The juvenile puerta currently deals no damage to opponents until it progresses to adult.

## Steps to reproduce

1. Spawn as Puerta.
2. Get a friend within attacking range.
3. Attack your friend and notice they take no damage.

## Build Information

> **Game Version:** 0.1.34.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.3
