### ISSUE TITLE
Slight glow around dinos when camera is angled down a bit

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#110]
## Expected Behavior
Dinos shouldn't have a glowing outline obviously 

## Current Behavior
Dinos have a glowing outline around them:
https://steamuserimages-a.akamaihd.net/ugc/2443642466615640483/585F813EA9EA89FEB7446FB9AC3CF2EF7E1538AE/

https://steamuserimages-a.akamaihd.net/ugc/2443642466615696219/28433F3441EE5512475A70E81476404A5284CB7E/
## Steps to reproduce
be any dino, angle the camera a bit low, and youll see the outline against the grass

## Build Information

> **Game Version:** 0.1.36.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1926594/TheIsle.log)

**Comment by Hypno123** [comment]
This may be intended to emphasize how wet the dinosaur is. I'll keep this up until we get confirmation on that.

**Comment by dinosauriac** [comment]
This is a side-effect of the ambient occlusion post process, it doesn't react well with grass which causes a bit of a halo effect. Reducing the AO distance would probably remove the problem, but make the overall scene lack some depth, so it's a bit of a tradeoff.

**Comment by Aliens218** [comment]
Issue still exists, commenting because I'm unsure if this is something that can be fixed in the coming re-code.

**Comment by dinosauriac** [comment]
Not sure if there's much that can be done there. Major AAA games have released recently with the same ghosting from AO. Disabling ambient occlusion would make the world look flat, and reducing the area of influence almost makes things worse since you then have a sharp line around the character instead of a soft falloff.
