### ISSUE TITLE
Carno sub UVs not lining up

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#113]
## Expected Behavior

UVs should line up seamlessly.

## Current Behavior

The UVs on the carno sub adult horns are not lined up, resulting in nubs at the tip where the bump map is not applied. There is a clear line where the bump map ends before it reaches the end of the horn.

![image](https://user-images.githubusercontent.com/38515115/39012589-d41be682-43e2-11e8-8f74-07d899d91f77.png)

## Steps to reproduce

Log in as carno sub adult and attempt to observe up close by running the camera into hard surfaces.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1929438/TheIsle.log)

> **Game Version:** 0.1.36.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Sub adult carno removed.
