### ISSUE TITLE
Utah does not leave footprints/make noise when jumping

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#114]
## Expected Behavior

When landing from a jump, one would expect to leave footprints upon landing as well as some type of sound to occur.

## Current Behavior

Utah is able to land from a jump without either noise or footprints being made.

## Steps to reproduce

Select Utah in any server.  Jump, observe.

## Build Information

> **Game Version:** 0.1.36.8

> **Operating System**: Windows 10

> **Network Role**: Client

Video enclosed below:

https://youtu.be/-JgMQWCGoDo

**Comment by dinosauriac** [comment]
There are no jump up or landing animations to put such effects on currently, it just blends into the "falling" pose. It's one of the minor movement features that'll be getting looked at soon.
