### ISSUE TITLE
Utah hatchling cannot eat

### ISSUE THREAD

**Issue by fubar345** [TheIsleGame/bugs#115]
## Expected Behavior

 Utah hatchling should be able to eat from corpses/gore piles

## Current Behavior

Utah hatchling cannot eat from corpses or gore piles

## Steps to reproduce

Step 1: Pick utah hatchling and try to eat.

## Build Information

> **Game Version:** 0.1.36.8(dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Tested this again recently. They are unable to eat however they **can** drink now.
