### ISSUE TITLE
Water Growth Bug

### ISSUE THREAD

**Issue by MsCatbugPLZ** [TheIsleGame/bugs#117]
## Expected Behavior
You stop growing if you're in water.

## Current Behavior

When you enter the water and your growth tick timer reaches 0 it freezes and you have to relog in order to start growing again.

## Steps to reproduce

Enter a pool of water and wait for the timer to reach 0
Gif: https://gfycat.com/SevereCleverEquine

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:**0.1.36.9 (dev)

> **Operating System**: Windows 7

> **Network Role**: Dedicated Server (Dev 2)

**Comment by looterz** [comment]
This is intended, to prevent camping under water.
