### ISSUE TITLE
Wrong water texture

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#118]
## Expected Behavior

Water should appear like water.

## Current Behavior

Water looks like cement tiles.

![image](https://user-images.githubusercontent.com/38515115/39032703-ae1a1ddc-443c-11e8-827d-3c046fb8bc7b.png)

## Steps to reproduce

Log onto Thenyaw and observe water source.

## Build Information

> **Game Version:** 0.1.36.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.37.0
