### ISSUE TITLE
Bodies are inconsistent

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#12]
## Expected Behavior

Ragdolls should fall the same way for every player and allow them to be eaten from where they land.

## Current Behavior

Ragdolls currently fall differently for every player, resulting in corpses landing in different locations and oftentimes being inedible.

To fix this issue, the player must either get outside of render distance of the corpse or relog on the server.

## Steps to reproduce

1. Spawn as anything.
2. Kill another player.
3. Attempt to eat the corpse and notice that it is in a different position for other players.

## Build Information

> **Game Version:** 0.1.34.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Should be fixed since 0.35.0

**Comment by Emanthealmighty** [comment]
Retested on 22 April 2019
Ragdolls are consistent in each player's screen.
