### ISSUE TITLE
Missing foliage on Thenyaw

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#121]
## Expected Behavior

There should be far more trees and bushes on Thenyaw. As of 0.1.36.9 half of them appear to be missing.

## Current Behavior

The trees and bushes used to almost touch the water in this area, proving that almost half of them are missing from the map. We had this issue when the map was first released as well.

![image](https://user-images.githubusercontent.com/30550499/39058488-e1827ada-44b3-11e8-9b90-f9f401754959.png)

## Steps to reproduce

1. Spawn in.
2. Look around at the lack of foliage.

## Build Information

> **Game Version:** 0.1.37.0 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in 0.1.38.9
