### ISSUE TITLE
Orodromeus mouth stretching

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#122]
## Expected Behavior

Oro's mouth should open normally.

## Current Behavior

The mesh of the mouth is stretching when performing actions.

![image](https://user-images.githubusercontent.com/38515115/39068079-0f307cc6-44a9-11e8-9047-0718b1006584.png)

## Steps to reproduce

Log in as Orodromeus and roar.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1933260/TheIsle.log)

> **Game Version:** 0.1.37.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.51.1
