### ISSUE TITLE
Sub Trike friendly animation too short

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#123]
## Expected Behavior

The animation should play for the length of the audio accompanying it and should appear similar to the animations of that nature in the same dinosaur family.

## Current Behavior

The friendly call (2) animation is a short jerk that finishes before the audio and is much shorter than the friendly call animations for juvenile and adult trikes.

https://youtu.be/QCBoD_kxP00

## Steps to reproduce

Log in as Sub Adult Triceratops and press 2 for friendly roar.

## Build Information

> **Game Version:** 0.1.37.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.38.4
