### ISSUE TITLE
Parasaurolophus mouth not closing

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#124]
## Expected Behavior

Para's mouth should not always hang open.

## Current Behavior

The mouth hangs open on the adult Parasaur while being upright and laying down.

![image](https://user-images.githubusercontent.com/38515115/39070978-55702b28-44b3-11e8-90b6-c31a8193eef9.png)

The mouth hangs open on the juvenile while laying down.

![image](https://user-images.githubusercontent.com/38515115/39070990-650724d8-44b3-11e8-986e-b197b42bd59e.png)

## Steps to reproduce

Log in as Parasaur adult and observe or log in as Parasaur juvenile and lay down.

## Build Information

> **Game Version:**0.1.37.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
