### ISSUE TITLE
Back button on News page shows 'Close' caption

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#125]
## Expected Behavior

There should not be a caption when hovering the back button on the news page.

## Current Behavior

Hovering the back button shows a close caption.

![image](https://user-images.githubusercontent.com/30550499/39079127-8a4bf7a6-450c-11e8-8144-67f7f75567b7.png)

## Steps to reproduce

1. Start the game.
2. Go to the news page.
3. Hover the back button.

## Build Information

> **Game Version:** 0.1.37.0 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
This was fixed as of revision 812
