### ISSUE TITLE
Spawns that break your leg

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#126]
## Expected Behavior

You should never spawn in and immediately break your leg.

## Current Behavior

There are spawns that cause you to break your leg immediately. Some of these spawns may affect one species and not another.

1. 
![image](https://user-images.githubusercontent.com/30550499/39084820-7b71e504-4572-11e8-9898-1d1d1523ed5b.png)
![image](https://user-images.githubusercontent.com/30550499/39084828-88745b1a-4572-11e8-9e54-ba1901b0f4b3.png)

2.
![image](https://user-images.githubusercontent.com/30550499/39084855-0c612fd4-4573-11e8-868f-e9e504214b31.png)
![image](https://user-images.githubusercontent.com/30550499/39084860-1b236b2c-4573-11e8-913b-5d7ac932decd.png)

3.
![image](https://user-images.githubusercontent.com/30550499/39084871-4807e884-4573-11e8-87b5-376bcb537f90.png)
![image](https://user-images.githubusercontent.com/30550499/39084875-679e4170-4573-11e8-8823-19f8f71545e8.png)

4.
![image](https://user-images.githubusercontent.com/30550499/39084903-fb8e3c46-4573-11e8-9b03-35d84afb71d6.png)
![image](https://user-images.githubusercontent.com/30550499/39084908-068fd640-4574-11e8-860b-7855e48d3b8f.png)

5.
![image](https://user-images.githubusercontent.com/30550499/39084935-66f00442-4574-11e8-8777-f5318274cf1b.png)
![image](https://user-images.githubusercontent.com/30550499/39084939-6fbcd14a-4574-11e8-8d8b-9318d0413c81.png)

6.
![image](https://user-images.githubusercontent.com/30550499/39084960-a66f1c5c-4574-11e8-99ef-ef8c0c0ec68b.png)
![image](https://user-images.githubusercontent.com/30550499/39084964-af887a68-4574-11e8-9c2d-f12567283312.png)

7.
![image](https://user-images.githubusercontent.com/30550499/39085000-0cdf3648-4575-11e8-93d0-20f5f0ad213d.png)
![image](https://user-images.githubusercontent.com/30550499/39085014-14992f74-4575-11e8-892e-9428e5d1960c.png)

8.
![image](https://user-images.githubusercontent.com/30550499/39085081-ce043864-4575-11e8-951e-140dac38003c.png)
![image](https://user-images.githubusercontent.com/30550499/39085082-d0c8b2f0-4575-11e8-953e-48685647b860.png)

9.
![image](https://user-images.githubusercontent.com/30550499/39085135-51e8da90-4576-11e8-96d1-b6da42478a4f.png)
![image](https://user-images.githubusercontent.com/30550499/39085143-596712e6-4576-11e8-85b5-ca10606af81c.png)

10.
![image](https://user-images.githubusercontent.com/30550499/39085155-859b6830-4576-11e8-80b9-42cebd273166.png)
![image](https://user-images.githubusercontent.com/30550499/39085156-8d5da268-4576-11e8-90ef-29fa7bbab235.png)

11.
![image](https://user-images.githubusercontent.com/30550499/39085166-ad804a64-4576-11e8-8db2-1c58ebec0716.png)
![image](https://user-images.githubusercontent.com/30550499/39085171-b5dc0d24-4576-11e8-9e2f-f01f3421b7ce.png)

12.
![image](https://user-images.githubusercontent.com/30550499/39085186-f68ed338-4576-11e8-8e46-01332cf4c298.png)
![image](https://user-images.githubusercontent.com/30550499/39085188-fa65405a-4576-11e8-85f4-0a003f207ebc.png)

13.
![image](https://user-images.githubusercontent.com/30550499/39085201-32020872-4577-11e8-8079-2d1fc822b203.png)
![image](https://user-images.githubusercontent.com/30550499/39085204-44bb4ee2-4577-11e8-9767-f3c75ef84f87.png)

14.
![image](https://user-images.githubusercontent.com/30550499/39085219-741071d6-4577-11e8-9c44-04206dd996e3.png)
![image](https://user-images.githubusercontent.com/30550499/39085221-81bb308c-4577-11e8-9fa9-42b21105c297.png)

15.
![image](https://user-images.githubusercontent.com/30550499/39085230-a3cc9eea-4577-11e8-8238-1db6ffe5ea34.png)
![image](https://user-images.githubusercontent.com/30550499/39085232-aa13aaaa-4577-11e8-961d-abc52fb561d4.png)

16.
![image](https://user-images.githubusercontent.com/30550499/39085244-c593992a-4577-11e8-9e6e-3e043c5d87a3.png)
![image](https://user-images.githubusercontent.com/30550499/39085266-11adf472-4578-11e8-96ba-fa485ced5e1e.png)

17.
![image](https://user-images.githubusercontent.com/30550499/39085274-2d177e22-4578-11e8-8763-62589144b0e9.png)
![image](https://user-images.githubusercontent.com/30550499/39085268-1a818460-4578-11e8-9f72-3cb8011cce2a.png)

18.
![image](https://user-images.githubusercontent.com/30550499/39085290-59d8ed60-4578-11e8-8059-f13810fe4d3d.png)
![image](https://user-images.githubusercontent.com/30550499/39085295-6edea13c-4578-11e8-9810-511ab06eeffe.png)

19.
![image](https://user-images.githubusercontent.com/30550499/39085316-913401aa-4578-11e8-9813-99bd147a7382.png)
![image](https://user-images.githubusercontent.com/30550499/39085321-9ef48a4e-4578-11e8-8599-deff76a76f42.png)

20.
![image](https://user-images.githubusercontent.com/30550499/39085326-b52a858e-4578-11e8-8875-e07d00fedb50.png)
![image](https://user-images.githubusercontent.com/30550499/39085331-bdf9f4d8-4578-11e8-8a59-a64f8e1e1688.png)

21.
![image](https://user-images.githubusercontent.com/30550499/39085335-d8a42312-4578-11e8-866a-422c548d148a.png)
![image](https://user-images.githubusercontent.com/30550499/39085339-df700e18-4578-11e8-985c-a2811f9b2ea6.png)

22.
![image](https://user-images.githubusercontent.com/30550499/39085347-01bacf30-4579-11e8-9b29-8ed068db0fc8.png)
![image](https://user-images.githubusercontent.com/30550499/39085352-0a12e406-4579-11e8-8cb6-8a69217ec2f2.png)

23.
![image](https://user-images.githubusercontent.com/30550499/39085390-71a1a67a-4579-11e8-93ec-4881e10fe714.png)
![image](https://user-images.githubusercontent.com/30550499/39085393-798571a0-4579-11e8-83a6-da45ccbe4604.png)

24.
![image](https://user-images.githubusercontent.com/30550499/39085409-c3e05d32-4579-11e8-92f6-d724249a3eb8.png)
![image](https://user-images.githubusercontent.com/30550499/39085405-b2378f38-4579-11e8-84bf-6039843fe865.png)

25.
![image](https://user-images.githubusercontent.com/30550499/39085449-4879d74e-457a-11e8-89fd-947e1f3e9b06.png)
![image](https://user-images.githubusercontent.com/30550499/39085508-47f6df5a-457b-11e8-9ef3-69165a7422b7.png)

26.
![image](https://user-images.githubusercontent.com/30550499/39085590-d2e7e932-457c-11e8-8594-f9c4cfa0520a.png)
![image](https://user-images.githubusercontent.com/30550499/39085599-ecec74ba-457c-11e8-9055-5d9caad1b894.png)

**If there are any spawns missing, feel free to add pictures of them to the comments or report to me to update this. Thanks.**

## Steps to reproduce

1. Spawn in.
2. Check for broken leg.
3. If not broken, respawn until you find the broken spawns.

## Build Information

> **Game Version:** 0.1.37.1 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by MortenSilver** [comment]
![image](https://user-images.githubusercontent.com/38515115/39088113-8ceee090-457a-11e8-857f-c2252bf67715.png)
![image](https://user-images.githubusercontent.com/38515115/39088120-9371a0ce-457a-11e8-8cd6-3dfc574d9178.png)

 on Dev 4

**Comment by dinosauriac** [comment]
I've gone through and looked at pretty much every spawn point, readjusting their height to be as close to the ground as possible without throwing up an error. Hopefully that will prevent any leg problems next build, but definitely double check those spots again when that's gone out to make sure.

**Comment by Hypno123** [comment]
Got a report that this spawn breaks legs too. Will coordinates alone be sufficient or will you need an image of the location too?

![image](https://user-images.githubusercontent.com/30550499/39088771-181d789a-45b0-11e8-9af7-f549c6e5ce0c.png)

**Comment by Souretsu** [comment]
![20180421172743_1](https://user-images.githubusercontent.com/26914945/39088934-8671e190-4589-11e8-88a0-2d33787a4a6b.jpg)

This one definitely breaks your leg as a Giga.  But I didn't notice any falling or anything, just instantly broken leg.

**Comment by Hypno123** [comment]
Fixed in 0.1.37.2 - If any of these are still present, open in a new issue. Thanks!
