### ISSUE TITLE
Dino calls are dependent on movement

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#128]
## Expected Behavior

Playing as any dinosaur, you should be able to vocalize with 1,2,3,4,f regardless of how you are moving.

## Current Behavior

Present on all dinosaurs, some calls are limited based on how the player is moving. If a player is moving using a+s, they cannot call with 1,2.  If a player is moving with s+d, they cannot call with 2,3.

https://clips.twitch.tv/AmazonianLitigiousKumquatPeteZaroll

## Steps to reproduce

Move around in all directions and test out the different calls in each direction.

## Build Information

> **Game Version:** 0.1.37.1 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Souretsu** [comment]
This is actually just an issue created by keyboard ghosting, I'm pretty sure.  Was able to successfully perform roars while holding A+S as well as S+D on the most recent dev version.

I had this issue a while back on my old Dell laptop.  Different keyboards stop reading key presses if you press certain combinations down, like it can't read more from that sector of keys.  More advanced keyboards can register as many key presses as there are keys on the board.

**Comment by Hypno123** [comment]
Looks like Sour beat me to it! Tested this for myself and also had no issues performing the roars while holding A+S etc.
