### ISSUE TITLE
Utah- Calling/Biting while crouching causing standing

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#129]
## Expected Behavior

Utah Raptor- Character should be able to crouch and REMAIN crouched when making various vocalizations and biting.

## Current Behavior

If Utah Raptor is crouching and makes any call (1,2,3,4,f), the character will stand up to do full-bodied animation, then go back down into crouch. This also occurs for the crouch + full-bodied bite animation.

https://clips.twitch.tv/DaintyModernKeyboardDansGame

## Steps to reproduce

Be a Adult Utah Raptor, crouch, make various calls and bite.

## Build Information

> **Game Version:** 0.1.37.1 (development)

> **Operating System**: Windows

> **Network Role**: Client (labrats)

**Comment by Hypno123** [comment]
Fixed in 0.1.37.5
