### ISSUE TITLE
Ambush modifier and unintended dinosaur movement and orientation 

### ISSUE THREAD

**Issue by FatLemur** [TheIsleGame/bugs#130]
## Expected Behavior

Animals running with ambush modifier should be able to turn normally without skipping animations

## Current Behavior

This footage was taken from dev server 3- juvi carno, survival. It has been reported in #bug-reports to effect at least juvi utah as well
https://www.youtube.com/watch?v=gLviadKIPgw&feature=youtu.be 

## Steps to reproduce

Move around while under ambush modifier attempting sharp changes in direction

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.37.6 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.36.7

**Comment by MortenSilver** [comment]
Still able to break orientation by simply spinning in a tight circle with directional keys in 0.1.53.3
