### ISSUE TITLE
Giga drinking animations

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#132]
## Expected Behavior

Feet should be firmly planted while drinking.

## Current Behavior

Feet move around during drinking animations.

Adult - feet slide back and forth during the drinking animation. https://www.youtube.com/watch?v=KPOfdriPE78Sub Adult - feet are planted but the left leg is very animated compared to the right. https://www.youtube.com/watch?v=e6E5fzf6p8E
Juvenile / Hatchling - the legs extend downward during drinking. https://www.youtube.com/watch?v=zZ6i8XzNnto

## Steps to reproduce

Log in as Giga and drink.

## Build Information

> **Game Version:** 0.1.37.7 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Looks like the links you have provided aren't working. Could you edit this with working ones? Thanks.

**Comment by MortenSilver** [comment]
Done

**Comment by Hypno123** [comment]
Added to #501
