### ISSUE TITLE
"Infinite Ambush" mode

### ISSUE THREAD

**Issue by BlackSpectre** [TheIsleGame/bugs#133]
## Expected Behavior

Ambush mode to cease being active after expected time.

## Current Behavior

Ambush mode remains on.

Tap (Don't hold) CTRL to crouch.
Wait for the "Ambush" icon to appear
Then, press SHIFT and then immediately press CTRL
Quickly press CTRL again to stand up before the Ambush notification appears.

You can now sprint faster to no end.

Easy step procedure:
CTRL, icon pops up, 
SHIFT then CTRL right after,
 CTRL (before you see the ambush icon pop up)

## Build Information

> **Game Version:** 0.1.36.7 Devbranch

> **Operating System**: Windows 10

> **Network Role**: Client and Dedicated Server.

**Comment by looterz** [comment]
Fixed in 0.1.37.8
