### ISSUE TITLE
Ambush cancelled by crouch

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#135]
## Expected Behavior

The dinosaur should have a specific window of time when it can ambush, once ambush conditions have been met and ambush has been triggered. Actions performed during this time window should either cancel ambush or not affect it for the duration of the window.

## Current Behavior

Once ambush is triggered, crouching again cancels it. The player must remain crouched for X amount of time to meet the ambush conditions again. Once ambush is triggered, switching to trot, walk, or resting does not affect ambush and the player can still sprint at ambush speeds during the ambush window of time. Examples of Utah ambush being interrupted by crouching and Carno ambush not being affected, because their speed modifiers are most noticeable and ambush windows are fairly long.

https://www.youtube.com/watch?v=j7zhVdq1QWQ
https://www.youtube.com/watch?v=i_YbNEed9cA

## Steps to reproduce

1. Log in as any carnivore.
2. Crouch for X amount of time to meet ambush conditions.
3. Press or hold Shift to trigger ambush.
4. Crouch to have ambush cancelled or perform any other action to not have it affected.

## Build Information

> **Game Version:** 0.1.37.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
@Hypno123 would you please test this again? I could not reproduce it, but it's possible this was fixed as a result of other code changes.

**Comment by Hypno123** [comment]
I feel like this is either intended or should remain how it is. Doesn't make sense for players to be able to resume ambush after losing all their speed by crouching.

**Comment by looterz** [comment]
I just want to clarify that this is an intended change.
