### ISSUE TITLE
Utah leaves no footsteps when walking/limping.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#136]
## Expected Behavior

Utahraptor to leave footsteps when walking/limping.

## Current Behavior

Utahraptor (All life stages)  leaves no footsteps when walking/limping

Video Evidence: https://youtu.be/bWeGsaYbO80
## Steps to reproduce

-Spawn as Utahraptor (Any stage ,juvenile and adult preferred).
-Walk/limp. 

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1945173/TheIsle.log)

> **Game Version:** 0.1.38.0 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.38.2
