### ISSUE TITLE
Sub-adult Carnotaurus has no ambush.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#137]
## Expected Behavior

Expected Sub-adult Carnotaurus to be able to ambush.

## Current Behavior

Sub-adult Carnotaurus has no ambush. No speed boost, no icon.
Video Evidence: https://youtu.be/SuDvtvvMCWk

Note: every single Survival carnivore has ambush, even the hatchlings.
## Steps to reproduce

-Spawn as / Get to Sub-adult Carnotaurus.
-Crouch.
-Wait for ambush icon to pop up.
-Notice that it never will pop up.
-Sprint to make sure it's not an issue with the icon not popping up.
-Notice that no speed boost is received.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1945207/TheIsle.log)

> **Game Version:**  0.1.38.0 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client.

**Comment by Hypno123** [comment]
It is intended that Carno does not have an ambush due to its regular sprint being fast enough to run prey down.
