### ISSUE TITLE
Corpses killed during rain stay glossy

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#139]
## Expected Behavior

For everything to dry off one it stops raining.

## Current Behavior

When something is killed during rain, it stays wet and glossy after the rain stops.

![image](https://user-images.githubusercontent.com/38515115/39287193-71265aa4-48f0-11e8-98b6-9c415186c94c.png)

## Steps to reproduce

Kill someone during rain and wait for it to stop.

## Build Information

> **Game Version:** 0.1.38.0 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by MortenSilver** [comment]
It gets fixed if you re-log.

**Comment by foszor** [comment]
Fixed in 0.1.38.6
