### ISSUE TITLE
Pressing enter in Settings menu opens chat, disables mouse controls when pressed again. (only in-game)

### ISSUE THREAD

**Issue by RagdollZombie** [TheIsleGame/bugs#141]
## Expected Behavior

Pressing Enter while in the in-game settings menu shouldn't do anything.

## Current Behavior

Pressing Enter while in the in-game settings menu brings up the chat, allowing you to type while in the menu. Pressing enter again closes chat and disables mouse controls until you either press Enter again or press Esc to exit the menu.

## Steps to reproduce

Go into a server and pause the game. Go into the settings menu and press Enter. The chat will pop up, allowing you to type. Pressing Enter again closes the chat and disables mouse controls until you either press Enter again or Esc.

## Build Information

> **Game Version:** 0.1.38.0 (dev branch)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.0
