### ISSUE TITLE
Utah and Trike hatchlings have the same base damage as the juveniles; Galli hatchling stats same as Juvenile (Tested in Sandbox)

### ISSUE THREAD

**Issue by RagdollZombie** [TheIsleGame/bugs#142]
## Expected Behavior

Utah and Trike hatchlings should have a lower base damage than their juvenile counterparts.

Galli hatchlings should have lower health, weight mass, and damage than juvenile counterpart.

## Current Behavior

Utah and Trike hatchlings have the same base damage as the juveniles.

Galli hatchlings have the same stats as juveniles

## Steps to reproduce

Spawn in as a Utah or Trike hatchling, take note of the bite damage, then respawn as their juvenile versions.
Note that the bite damage is the same as the juveniles.

Spawn in as a Galli hatchling
Note it's stats,
Respawn as The juvenile version. 
Compare juvenile's stats to hatchling.

## Build Information

> **Game Version:** 0.1.38.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Closing this.

Utah and Trike hatchlings have their weight mass increased as they progress to juvenile, effectively making them do more damage, even though it says they do less bite damage.

As for galli stats, this has already been reported in #92 

To improve:

- Search through open reports for issues before posting (adding comments where needed.)
- Try to report all issues separately. If you report 10 problems and the team can only fix 9 of them, it forces them to keep the whole report open, even though most of the issues have been fixed.

Thanks for the help regardless :smile:
