### ISSUE TITLE
Hatchlings don't leave footprints when walking / crouch walking

### ISSUE THREAD

**Issue by RagdollZombie** [TheIsleGame/bugs#143]
## Expected Behavior

Hatchlings should leave footprints when walking, trotting, sprinting, and crouch-walking

## Current Behavior

Hatchlings don't leave footprints when walking or crouch-walking.

## Steps to reproduce

spawn as any hatchling.
walk or crouch-walk, notice that the footprints don't appear like they do with sprinting and trotting

## Build Information

> **Game Version:** 0.1.38.0 (dev branch)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Did further testing on this. Here is a list of when footprints **DO NOT** appear:

Utah: Trot, walk and crouch.
Carno: Walk and crouch.
Rex: Walk and crouch.
Giga: Walk and crouch.
Galli: Walk and crouch.
Para: Run, trot and walk.
Trike: Trot and walk.

**Comment by dinosauriac** [comment]
I'm unsure whether this is something we really want/need for hatchlings.

**Comment by Hypno123** [comment]
As it stands some hatchling species leave footprints while others do not. In that case it needs to be decided whether they all do or all do not.

**Comment by dinosauriac** [comment]
Hmm. I believe this is actually a side effect of the velocity check being done in the footstep notify. Had the same thing with the adult Utah's walk recently, the thing is moving so slowly it literally doesn't trip the velocity trigger to spawn a footstep. Going to try reducing the speed requirement.

**Comment by Hypno123** [comment]
Fixed in 0.1.38.4
