### ISSUE TITLE
Camara stomp prints not aligned

### ISSUE THREAD

**Issue by RagdollZombie** [TheIsleGame/bugs#144]
## Expected Behavior

Camara's front legs should leave a print at the point of impact on the ground.

## Current Behavior

When the Camara stomps, the prints are spawned behind its front legs, underneath it's stomach.

## Steps to reproduce

Spawn as Camara
Stomp the ground

## Build Information

> **Game Version:** 0.1.38.0 (dev branch)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Before stomping:
![image](https://user-images.githubusercontent.com/30550499/39343345-33f50d3a-49d4-11e8-8744-8419dc05caf3.png)

After stomping:
![image](https://user-images.githubusercontent.com/30550499/39343349-3be3c4fa-49d4-11e8-9658-624e0d54b3d0.png)

**Comment by dinosauriac** [comment]
You weren't moving at the time?

**Comment by Hypno123** [comment]
That's the result of stomping without moving.

**Comment by Hypno123** [comment]
Fixed
