### ISSUE TITLE
Volcano rock missing texture

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#146]
## Expected Behavior

The rock should have a texture.

## Current Behavior

The rock by the volcano currently has no texture applied to it.

![image](https://user-images.githubusercontent.com/30550499/39391784-f912c9fa-4aa0-11e8-9fb5-dbf089b9c5bd.png)

## Steps to reproduce

1. Spawn as anything.
2. Go to the volcano.
3. Find the untextured rock.

## Build Information

> **Game Version:** 0.1.38.0 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed.
