### ISSUE TITLE
Black texture on the Beach (V3)

### ISSUE THREAD

**Issue by apparero** [TheIsleGame/bugs#148]
## Expected Behavior

The ground should have a texture.

## Current Behavior

A part of the beach has a black texture.
![image](https://user-images.githubusercontent.com/15094907/39399574-8894cf04-4b20-11e8-821a-3313896c2a8b.png)

## Steps to reproduce

1. Spawn as any Dinosaur
2. Walk to the in the screenshot specified location

## Build Information

> **Game Version:** 0.1.38.1(dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
![image](https://user-images.githubusercontent.com/30550499/39412941-239ee192-4c1b-11e8-9346-485dcbd8b6e6.png)

**Comment by Hypno123** [comment]
Fixed.

**Comment by RagdollZombie** [comment]
More black squares and other texture issues found on the beach at (Lat: -667,451.125 Long: 149,082.453 Alt: -72,908.344)

Also continues down into the ocean floor

![image](https://user-images.githubusercontent.com/16749057/57186470-e81de800-6e94-11e9-906b-b224ecd3a0a8.png)

![image](https://user-images.githubusercontent.com/16749057/57186474-f53ad700-6e94-11e9-9527-34ff99cd5595.png)
