### ISSUE TITLE
"P" screen growth timer/stat update delay

### ISSUE THREAD

**Issue by Arkaria3D** [TheIsleGame/bugs#149]
## Expected Behavior

Growth timer hits 0 seconds, growth and other stats update immediately, and timer resets

## Current Behavior

Growth timer reaches 0 seconds, remains at 0 for a random length of time (used stop watch to time it. Got 45 seconds, 1min 9 seconds, and 1min 3 seconds) then stats finally update and the timer resets

## Steps to reproduce

Use P to pull up stat screen. Watch timer and stats.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.1 (dev)

> **Operating System**: Windows

> **Network Role**: Dev Branch, Dev 4 server, V3 map

**Comment by Hypno123** [comment]
Must be caused by network lag. Couldn't reproduce on both the testing and listen servers.
