### ISSUE TITLE
Being killed immediately after spawning freezes camera in place, does not refresh to character select

### ISSUE THREAD

**Issue by RagdollZombie** [TheIsleGame/bugs#151]
## Expected Behavior

Being killed while spawning should take you to the character select screen as normal.

## Current Behavior

If you are killed the exact moment you spawn:

The death camera will lock in place
The deceased screen animation will not show
The blood overlay will still be visible
You will be stuck until you respawn or relog

## Steps to reproduce

Have another player spawn as a large dinosaur that can 1-hit any small dinosaur
Spawn in as a small dinosaur
Have the other player try to hit you at the exact time you spawn in. May take several tries, might need more testing.

## Build Information

> **Game Version:** 0.1.38.1

> **Operating System**: Windows

> **Network Role**: Client

## Screenshot

![spawnbug](https://user-images.githubusercontent.com/16749057/39450868-9ea6a526-4c81-11e8-9db8-85ceca77ed28.jpg)

**Comment by Hypno123** [comment]
Could you get a video of this occurring on the testing server?

**Comment by Hypno123** [comment]
Fixed in 0.1.39.1 with changes to spawn system
