### ISSUE TITLE
Animation bug allows Acro to attack while sitting

### ISSUE THREAD

**Issue by RagdollZombie** [TheIsleGame/bugs#152]
## Expected Behavior

All dinosaurs cannot bite while sitting, Acro included.

## Current Behavior

If you spam attack while standing up and sit back down again as the Acro bite animation plays, you will be able to bite while resting until you stand up again.

## Steps to reproduce

Spawn as an Acro
Rest
Spam attack as you stand back up. Immediately rest again when Acro's bite animation plays.
You will be able to bite while resting until you stand up again.

## Build Information

> **Game Version:** 0.1.38.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Species currently not in survival. Can be re-opened should it be added.
