### ISSUE TITLE
V3 ocean has no underwater effects

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#155]
## Expected Behavior

There should be underwater effects for the ocean when the player places their camera under the water.

## Current Behavior

There are no underwater effects when the player places their camera under the water.

![image](https://user-images.githubusercontent.com/30550499/39412877-84ba4c1a-4c1a-11e8-81a9-b157dec1f859.png)

## Steps to reproduce

1. Spawn as anything.
2. Go to the ocean (or use spectator camera.)
3. Place your camera under the water. Sight should become blurry and audio should sound muffled.

## Build Information

> **Game Version:** 0.1.38.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Ocean hasn't been updated yet. Bit of a tricky task, need a way to disable thirst replenishment on water volumes before the new ones can be used there.

**Comment by Hypno123** [comment]
This is apparent on the new V3 map. I'll assume due to same reasoning as above.

**Comment by Hypno123** [comment]
This is an enhancement.
