### ISSUE TITLE
Lakes that cannot be drank from on V3

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#156]
## Expected Behavior

Every lake should be drinkable.

## Current Behavior

These lakes currently cannot be drank from (will update should I find more.)

![image](https://user-images.githubusercontent.com/30550499/39412959-71e2b36a-4c1b-11e8-9943-796d04db2b4f.png)

![image](https://user-images.githubusercontent.com/30550499/39412984-e56d213a-4c1b-11e8-868e-dc8dd16d3b5a.png)

## Steps to reproduce

1. Spawn as anything.
2. Go to any of the above lakes.
3. Attempt to drink from them with E and realize you are unable to.

## Build Information

> **Game Version:** 0.1.38.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Did that lake have the interaction effects when swimming? Wondering if I missed a spot.

**Comment by Hypno123** [comment]
As in swimming, underwater effects etc? Everything was working correctly other than being unable to drink from it.

**Comment by Souretsu** [comment]
Found another one, attaching one picture w/ coordinates as well as another for geographical reference.
![20180430221059_1](https://user-images.githubusercontent.com/26914945/39459149-746ca120-4cc7-11e8-8c3c-3f9c2cd0a123.jpg)
![image](https://user-images.githubusercontent.com/26914945/39459174-906c3d9a-4cc7-11e8-91d9-998b1f0558f3.png)

**Comment by Hypno123** [comment]
Fixed in 0.1.38.7
