### ISSUE TITLE
Untextured Orb found on Thenyaw.

### ISSUE THREAD

**Issue by fubar345** [TheIsleGame/bugs#157]
## Expected Behavior

Untextured orb to not exist.

## Current Behavior

Untextured orb exists

## Steps to reproduce

Go to the coords in the screenshot and you will find the orb.

## Build Information

![image](https://user-images.githubusercontent.com/13227782/39433885-02901102-4c65-11e8-9ba9-52e8aa59ce60.png)

> **Game Version:** 1.38.2

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Ahh, that's one of the DFAO interaction meshes I was testing with the other day. *Should* be gone with the next update to the map.
