### ISSUE TITLE
V3/Dev4 Nightvision: Skin Pattern Disappear in Shadows

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#158]
## Expected Behavior

Skin patterns appear dulled/darker in shadows

## Current Behavior

If you are under a tree (or something that produces a "shadow"), At night, and turn on nightvision, the "shadowed" skin areas become patternless and light grey

https://cdn.discordapp.com/attachments/401560830312841227/440306847153651722/unknown.png

## Steps to reproduce

Go to Dev 4-V3 map. At night, go under some trees or other shadow-producing objects. Turn on nightvision and observe pattern on skin

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.2 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
With changes to night vision coming, this does not need to be worried about. Can re-open if the issue persists with the new system.
