### ISSUE TITLE
V3 Footprints on top of ocean water 

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#161]
## Expected Behavior

For footprints to appear below the water if the feet are submerged.

## Current Behavior

Footprints appear on top of water when walking in the shallows in the ocean.

![image](https://user-images.githubusercontent.com/38515115/39461232-5153d824-4cd7-11e8-8602-7358eeb08790.png)

## Steps to reproduce

Walk through shallow ocean water, with your feet just below the surface.

## Build Information

> **Game Version:** 0.1.38.2 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.38.8
