### ISSUE TITLE
V3 Section of the ocean is invisible

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#162]
## Expected Behavior

The water should always be visible.

## Current Behavior

There is a section of the ocean where the water texture does not render in. There is a line that the camera has to cross in order to render water properly. The water physics are still there, the dinosaur swims, and the proper audio sounds play.

![image](https://user-images.githubusercontent.com/38515115/39461494-2ae5d6cc-4cd9-11e8-8be8-03214292cc3d.png)

https://www.youtube.com/watch?v=PIb9MRAZx5w

## Steps to reproduce

Spawn at the location in the screenshot and observe the ocean.

## Build Information

> **Game Version:** 0.1.38.2 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed with changes to the ocean.

**Comment by melmelMeliora** [comment]
Playing today I found ocean that was invisible. I thought it was a big stretch of sandy beach and was running around on it until I suddenly started swimming in... nothing. Coords -535, 12
