### ISSUE TITLE
Subadult Carno unable to Ambush, all other growth stages can.

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#163]
## Expected Behavior
Consistent ambush behavior between all growth stages
## Current Behavior
Juvenile and Adult Carno are both able to Ambush, Subadult cannot. I remember hearing that Carno was having its ambush bonus taken away, so I'm not sure if it's a case of it missing from the Subadult or of it not being taken away from the Adult.

Video: https://youtu.be/k_TaTksmAIA
## Steps to reproduce
1. Spawn as Subadult Carno
2. Crouch in preparation for Ambush
3. Observe as the bonus does not activate
## Build Information
> **Game Version:** 0.1.38.2 (dev)

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by Hypno123** [comment]
I believe it needs to be taken away from the adult Carno as they are fast enough to simply sprint down almost everything as it is.

**Comment by Souretsu** [comment]
From a balance perspective I agree, their normal sprint speed is currently faster than any other animal, including ambush speeds.  I just wasn't sure if it was a problem with Sub Carno not having it, or a problem of Carno still having it.

**Comment by Hypno123** [comment]
Fixed in 0.1.38.4
