### ISSUE TITLE
Respawning with nightvision in spectator mode causes it to carry over to next spawn.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#165]
## Expected Behavior

Night vision to be disabled if the user re-spawns with it active in the spectator mode.

## Current Behavior

If the user re-spawn with night vision activated in spectator mode, it will carry over to the next spawn.
User won't be able to deactivate it unless he/she re-logs.

Video evidence: https://www.youtube.com/watch?v=kqNQdiyNtV0&feature=youtu.be

## Steps to reproduce

-Spawn as anything that can activate night vision.
-Activate your night vision.
-Enter spectator mode.
-Re-spawn.
-Select anything, even if it doesn't have night vision.
-Notice that your old night vision filter will still be active, same filters, same colors.
-Try to deactivate your night vision (if you have one).
-Notice that (if you have it) a different night vision filter will be applied, instead of deactivating the older one.
-Stay stuck with night vision until you log out of the server.

Note: Tribals / mercs will keep the night vision, regardless if they have it or not.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1969249/TheIsle.log)

> **Game Version:**  0.1.38.3 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client.

**Comment by looterz** [comment]
Fixed in 0.1.39.0
