### ISSUE TITLE
Animals regenerate stamina when swimming.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#166]
## Expected Behavior

Animals to be unable to regenerate stamina when swimming.

## Current Behavior

Animals can regenerate stamina when swimming.
Animals can then swin for longer than expected/calculated.
Some animals (hatchling Gallimimus, for example,) can't even drown due to this.
Note: needs further testing to make sure the same as above doesn't happen to other animals.

Happens to any animal that regenerates stamina when walking/trotting.
Video Evidence: https://youtu.be/F2fqZm85yrw
  -Note: In Parasaurolophus case (shown in the video) After each 3 "stamina drain" tick, instead of draining 2 stamina, only 1 stamina will be drained (because para regenerates 1 stamina every tick).
## Steps to reproduce

-Spawn as anything that can regenerate stamina.
-Go into the water.
-Pay attention to your stamina.
-Notice that sometimes the "Stamina drain" ticks will drain different amounts than before.
  - Notice that some animals (like hatchling gallimimus) don't even lose stamina.
## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1969256/TheIsle.log)

> **Game Version:** 0.1.38.3 ( development )

> **Operating System**: Windows 10.

> **Network Role**: Client.

**Comment by Souretsu** [comment]
*That* explains it.  I saw a Carno spend several consecutive minutes in the water without dying earlier this evening and wasn't sure what was going on.

**Comment by looterz** [comment]
Thanks for the report, looking into this now.

**Comment by looterz** [comment]
Fixed for 0.1.38.4
