### ISSUE TITLE
V3 Hatchlings swim very fast

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#168]
## Expected Behavior

Hatchlings probably were not that great at swimming considering how weak they are.

## Current Behavior

Hatchlings are supersonic in the water. Tested as utah and carno. Observed a para.

https://www.youtube.com/watch?v=hgJ6Ohj7ZPk

## Steps to reproduce

Log in as a hatchling and go for a swim.

## Build Information

> **Game Version:** 0.1.38.3 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.38.4
