### ISSUE TITLE
V3 Sky effects not synced between players

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#171]
## Expected Behavior

Weather should be the same for all players and weather changes should be experienced at the same time by all players.

## Current Behavior

Sky effects are not synced.
![image](https://user-images.githubusercontent.com/38515115/39666070-b2e74c46-506b-11e8-9a56-20fab8c88334.png)
![image](https://user-images.githubusercontent.com/38515115/39666072-b7df8e5c-506b-11e8-9d08-434a18a90c6c.png)

Screenshots were taken at the same time on Dev 4. The clouds cleared up shortly after and the sky was the same for both players. Both games run on epic settings.

## Steps to reproduce

Play on 2 different accounts and watch for simultaneous weather changes.

## Build Information

> **Game Version:** 0.1.38.5 (development). Happened right after the update that dealt with foliage.

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Is this still an issue?

**Comment by dinosauriac** [comment]
Need more info, honestly. It sounds like one player joined after the other here. The weather system has a set time period for lerping between conditions, so when you enter it changes from the default to whatever is currently active over that time frame. I could be wrong, but I don't think there's anything set up to instantly change to the current weather condition on joining yet, it has to go through the motions.

**Comment by Hypno123** [comment]
The sky effects will always be the same now, though they might look slightly different for each player.

My view:
![image](https://user-images.githubusercontent.com/30550499/43853000-a8436ae8-9b36-11e8-983b-5d03c88dcd6e.png)

Souretsu's view
![image](https://user-images.githubusercontent.com/30550499/43853003-acfd1408-9b36-11e8-8eb9-05e3b64d06c0.png)

Going to close this regardless.

**Comment by looterz** [comment]
Hard to tell how different it is with the camera angles and locations being different, would need two developers to test with the debug screen on which now shows the current time of day in seconds.
