### ISSUE TITLE
V3 ambience possibly not synced with weather

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#172]
## Expected Behavior

The weather ambience should be synced with weather effects.

## Current Behavior

Ambient sound files seem to play without a clear trigger.

During this instance, an ambient sound layer was added to the night ambience that sounded like wind or distant rolling thunder. I only say this because I saw clouds at the time, but I'm not sure what exactly the sound is without a visual aid. It is present in this video and is quieter than the default night ambience. 

https://www.youtube.com/watch?v=RDUBtHxEcX4

Upon hearing this audio, myself and Souretsu noted that the sky effects were not the same for us (covered in a separate issue). When the audio started, my sky was cloudy, but Sour's sky was clear. My sky cleared up shortly after, but the new audio persisted for a while. We were not in the mountains, so this is not the audio linked to elevation.

## Steps to reproduce

Log in and observe ambient sounds in relationship to weather.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.4 (development). This happened right after the foliage update.

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
That's just the wind. The sky conditions being un-synchronized is its own issue. There's usually a period of up to 30 seconds for the current active ambience / weather to transition in when loading into a map, which might be what you've been experiencing.

**Comment by MortenSilver** [comment]
Alright. I wasn't sure if that's what was supposed to happen. The wind has so much bass coming through on my headset, that it sounds like thunder XD
