### ISSUE TITLE
Missing hitbox on a type of tree

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#173]
## Expected Behavior

One should not be able to walk through the trunk of this kind of tree

## Current Behavior

It is possible to walk to the trunk of this type of tree with any dinausaure
![20180505204003_1](https://user-images.githubusercontent.com/35146192/39666489-8b022276-50a4-11e8-87df-0d56aaf7f67c.jpg)

## Steps to reproduce

1. Take any dinosaur
2. Find this type of tree
3. Walk through the trunk

## Build Information

> **Game Version:** 0.1.38.5 (development)
> **Operating System**: Windows
> **Network Role**: Client

**Comment by Hypno123** [comment]
I believe this is intended due to forests becoming too difficult to navigate when it's set to clip with the creatures. 

I will however leave this up until we hear otherwise.

**Comment by foszor** [comment]
@Hypno123 correct
