### ISSUE TITLE
Hatchlings do not make full contact with the ground- floating

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#174]
## Expected Behavior

Hatchling feet make contact with the ground/whatever surface they are standing on.

## Current Behavior

Currently there is an obvious space between the ground and the hatchling feet.
![image](https://user-images.githubusercontent.com/32625368/39666726-f6c1368c-506d-11e8-9b31-347a7da2dae5.png)
Currently present on these hatchlings: All

## Steps to reproduce

Be a hatchling and check feet at all angles.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.5 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Mostly fixed in 0.1.38.6.

Foot IK should tidy this up when it's ready anyway.
