### ISSUE TITLE
Missing hatchling footstep sound for some creatures on V3

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#175]
## Expected Behavior

We should hear the footsteps of the hatchling

## Current Behavior

You can't hear the footsteps of any hatchling expect galli. But you can hear all of them on the DV-TestLevel

## Steps to reproduce

1. Take an hatchling
2. Walk with it

## Build Information

> **Game Version:** 0.1.38.5 (development)
> **Operating System**: Windows
> **Network Role**: Client

**Comment by Hypno123** [comment]
I believe these may have been disabled on purpose due to how small they are.

@dinosauriac will know.

**Comment by Hypno123** [comment]
Intended.
