### ISSUE TITLE
Animation of the giga hatch isn't synced with the sound

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#176]
## Expected Behavior

The sound should only come out after the hatch took is breath

## Current Behavior

The sounds comes out when the hatch is still taking is breath
https://www.youtube.com/watch?v=NVo44Omgiek&feature=youtu.be

## Steps to reproduce

1. Take a Giga Hatch
2. Do any call with it 

## Build Information

> **Game Version:** 0.1.38.5 (development)
> **Operating System**: Windows
> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in 0.1.39.2
