### ISSUE TITLE
Water Ripple Interaction Effect not flush with Watersource Borders

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#177]
## Expected Behavior

Animations (ie ripples/splashes/etc) should be apparent as soon as you enter the water.

## Current Behavior

Water effects do not trigger until a player is about 1-1.5 feet into the water

https://clips.twitch.tv/CogentSquareWerewolfLitFam

## Steps to reproduce

walk in and out of a water source and observe when the water appears to be interacted with.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.5 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Intentional. Also, more noticeable with hatchlings since their collision objects are smaller so come into contact later than a large animal's would.
