### ISSUE TITLE
Delayed damage from certain dinosaur attacks.

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#178]
## Expected Behavior

Damage to occur immediately upon being hit.

## Current Behavior

With some dinosaurs (Rex confirmed, also noticed with Para and Trike in recent Dev branch builds), damage from taking a hit does not register immediately.  Seems to happen when the attack animation ends.

## Steps to reproduce

1) Spawn in as Adult Rex (or other affected dinosaur).
2) Attack another player character.
3) Notice that the pain sound, bone break, etc is not instant. 

## Build Information
Game ver. 0.1.38.5 (Public/Dev)
System: Windows 10
Client/Server: Dedicated

**Comment by Cocazou** [comment]
https://www.youtube.com/watch?v=BV-ym4DnjrI&feature=youtu.be

**Comment by Hypno123** [comment]
Example of this in 0.1.40.0: https://www.youtube.com/watch?v=bZxWIvLUb4k

**Comment by Hypno123** [comment]
With Rex fixed, just Para, Trike and Shant suffer from this in 0.1.51.9.

**Comment by Hypno123** [comment]
Fixed in 0.1.53.0
