### ISSUE TITLE
Progression 'old triceratops' unable to drink/eat

### ISSUE THREAD

**Issue by FatLemur** [TheIsleGame/bugs#179]
## Expected Behavior

Be able to interact with water sources or food bushes

## Current Behavior

This only effects the old/progression trike and not the survival trikes, unable to interact with food/water.

## Steps to reproduce

Pick 'old triceratops' in sandbox mode or progress to triceratops in progression mode and try to interact with food/water

## Build Information

> **Game Version:** 0.1.38.5 (Public/Dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Progression related. CY@
