### ISSUE TITLE
Join a full server when whitelisted as admin isn't working

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#180]
## Expected Behavior

If you are Whitelisted as an Admin you should be able to join the server even if it's full.

## Current Behavior

You can't join a full server if you are whitelisted as an admin. Getting "Server is full" message.

## Steps to reproduce

1. Get whitelisted as an admin on the server
2. Try to join the server when full 

## Build Information

> **Game Version:** 0.1.38.5

> **Operating System**: Windows

> **Network Role**: Dedicated Server

**Comment by looterz** [comment]
Fixed in 0.1.39.0
