### ISSUE TITLE
Flying bush on Thenyaw Island

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#181]
## Expected Behavior

Bushs shouldn't fly

## Current Behavior

This bush is flying.

![20180506182902_1](https://user-images.githubusercontent.com/35146192/39675543-f1665164-515c-11e8-9add-9929f42bbae5.jpg)
![unknown](https://user-images.githubusercontent.com/35146192/39675622-0078d4aa-515e-11e8-93a9-fe4bab810c6e.png)
![sans titre](https://user-images.githubusercontent.com/35146192/39675616-f8880928-515d-11e8-9958-412a8f0c3ac4.png)

## Steps to reproduce

1. Take a dino
2. Go to the location 
3. Admire it

## Build Information

> **Game Version:** 0.1.38.5

> **Operating System**: Windows

> **Network Role**: Dedicated Server

**Comment by looterz** [comment]
Fixed in 0.1.38.6
