### ISSUE TITLE
Leaving the server while in Spectator Mod causes bug 

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#184]
## Expected Behavior

If you leave a server while in spectator. You should be able to join the server later on

## Current Behavior

If you leave the server while in the spectator mod you you can't join the server again ( Getting the message "The connection to the server timed out"). You need to restart the server if you want to join the server again.

## Steps to reproduce

1. Take any dino and go into the spectator mod
2. Leave the server while in spectator mod
3. Try to rejoin the server

## Build Information

> **Game Version:** 0.1.38.5 (development)

> **Operating System**: Windows

> **Network Role**: Dedicated Server (Database)

**Comment by looterz** [comment]
I haven't been able to reproduce this bug.
