### ISSUE TITLE
Hidden hole on Thenyaw that causes players to be stuck indefinitely

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#185]
## Expected Behavior

There shouldn't be any hidden holes that players can get permanently stuck in.

## Current Behavior

There is a hole on Thenyaw that can be fell in and will cause the player to get stuck.  Only teleporting gets them out.

The strange thing about the hole is that it cannot be seen in spectator mode.

![image](https://user-images.githubusercontent.com/30550499/39759752-63f0e0e0-52cb-11e8-8750-22b081910e4d.png)

![image](https://user-images.githubusercontent.com/30550499/39759816-93b8c6b2-52cb-11e8-987f-dc7868fc34cb.png)

![image](https://user-images.githubusercontent.com/30550499/39759833-9f2c9bc2-52cb-11e8-8c65-3a622e80f620.png)

![image](https://user-images.githubusercontent.com/30550499/39759838-a503d9fc-52cb-11e8-8826-e92f9e3eee8b.png)

## Steps to reproduce

1. Spawn as anything.
2. Go to the hole at the coordinates provided.
3. Enter the hole and become stuck.
4. Go to spectator mode and notice the hole cannot be seen.

## Build Information

> **Game Version:** 0.1.38.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Covered this over with a new rock formation in the latest patch.
