### ISSUE TITLE
The damage giving from the para are not sync with the animation

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#186]
## Expected Behavior

The para should do damage to his victim when he is doing his animation.
https://www.youtube.com/watch?v=BV-ym4DnjrI&feature=youtu.be
## Current Behavior

The victim of the para is taking damage 1 sec after the para did his attack animation

## Steps to reproduce

1. Take a Para
 2. Hit a dino

## Build Information

> **Game Version:** 0.1.38.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Reported in #178
