### ISSUE TITLE
Call animations of all survival dinos can be canceled

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#187]
## Expected Behavior

You shouldn't be able to cancel the animation of the diffrent calls of a dino.

## Current Behavior

The call animation of all the survival dino's and at all stages can be cancelled by eating a carcass/plant without the sound of the call being interrupted. 
## Steps to reproduce

1. Take any dino in survival
2. Do a call (1,2,3,4 or F)
3. Then immediatly eat something

## Build Information

> **Game Version:** 0.1.38.5 (development)
> **Operating System**: Windows
> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.38.6
