### ISSUE TITLE
Can't eat/drink after biting

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#188]
## Expected Behavior

Player should be able to eat and drink every time they interact with appropriate objects.

## Current Behavior

The dinosaur will only initiate eating / drinking once, following a bite. It will not do so again, unless another bite is performed. A bite followed by a roar will have the same effect.

https://www.youtube.com/watch?v=TNQBvfaQhAo

The first sip of the animation is fine, but every following sip has an odd twitch.

https://www.youtube.com/watch?v=pbESXFJiCG4

You can see the left leg twitching every time I press E to drink and it wants to play the animation.

## Steps to reproduce

Log in as any carnivore, except adult rex, or as a juvenile gallimimus. (Sprint kicking will trigger the bug.)
Bite.
Roar.
Try to drink.

Alternatively:
Bite, drink.
Try drinking again.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.6 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.38.7
