### ISSUE TITLE
Sound artifact in ambience loop

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#190]
## Expected Behavior

Ambient sounds should be seamless, to enhance immersion, but not interfere with gameplay.

## Current Behavior

The ambient sound loop that plays during day / early evening has an artifact that does not sound like it belongs and it is distinct enough that I'm consciously aware of every time it plays. At the 0:20, there's a "beep-boop" sound. It's quiet, but there.

https://youtu.be/ledObHAS4Tk?t=15

## Steps to reproduce

Listen to day / evening ambience.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.7 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
I'm not hearing anything out of the ordinary. At 20 secs in the video that is a tropical bird chirping. It's something from Hawaii that makes a sort of wet "boop" if you want to call it that. I seriously don't see how this interferes with gameplay.

**Comment by Hypno123** [comment]
Doesn't interrupt gameplay and was purposely added; no change needed.
