### ISSUE TITLE
Floating rock(?) near swamp (Thenyaw)

### ISSUE THREAD

**Issue by IronSocksMcConnell** [TheIsleGame/bugs#191]
## Expected Behavior

Boulder to be placed in the ground.

## Current Behavior

Boulder is floating as high as the treeline.

![floating boulder](https://user-images.githubusercontent.com/39017725/39949491-acd5d21c-5540-11e8-8bdb-964dd20b6b8f.jpg)

## Steps to reproduce

Follow the coordinates given, should see it if looking towards the water.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** In the main menu, on the bottom right
0.1.38.7
> **Operating System**: Windows, Linux or Mac
Windows
> **Network Role**: Client, Listen Server or Dedicated Server
Dedicated Server, Isle Dev 3, Thenyaw map.

here in case.
[isle log.txt](https://github.com/TheIsleGame/bugs/files/1996995/isle.log.txt)

**Comment by Hypno123** [comment]
Fixed in 0.1.38.8
