### ISSUE TITLE
Particle appears in wrong place during Juvenile Utah movement

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#192]
## Expected Behavior

When walking in water, the splash particle should appear at the feet, or even on the surface of the water.

## Current Behavior

When trotting near the water's edge as a juvenile Utah, the particle effect appears overhead.  I have noticed that it does not appear nearly as high on a full-grown Utah juvenile, so the altitude may be a fixed point.

Video: https://youtu.be/4U1uGOZhonY

## Steps to reproduce

1) Spawn in as Juvenile Utahraptor
2) Move around at the edge of a body of water
3) Observe particle misplacement.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Took me a while to see what you meant there. That's not a water splash particle, it's a regular footstep impact. There's something with a rock physical material around there that the foot trace is colliding with, causing it to spawn impact effects. Does this happen at all water sources, or just this one?

**Comment by Souretsu** [comment]
From what I've been able to notice it's any water source.  Or rather all water sources that I tried this with.

**Comment by dinosauriac** [comment]
Fixed in 0.1.38.9
