### ISSUE TITLE
Water ripple effects playing on cave ceilings, walls during rain

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#193]
## Expected Behavior

When raining only the outside surfaces of structures should appear wet.

## Current Behavior

During rain, the "wet" effect for rocks etc will play on all surfaces of the object, even those which realistically should not be getting wet.  The rippling effect will also play on the side of the object, which does not altogether make sense.  Something akin to what is used on dinosaurs currently would make more sense, with ripples on top and running water on the side.

Video: https://youtu.be/VQBOOdz9tC4

## Steps to reproduce

Observe these types of objects during rainy weather.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Ceilings were an easy fix, walls are a different matter. Objects like rocks are very irregular, so they have a lot of small pieces that jut out down their sides and get classed as the "top" of an object. So whilst you won't see ripples appear vertically, they will still show on top of these outcroppings. 

We don't have any setup for "interiors" currently, but adding a switch to enable/disable weather effects on objects (e.g. IsInterior) might do the trick for objects that are entirely indoors or underground, Transitional objects will have to go for one or the other, though.

**Comment by dinosauriac** [comment]
Fixed in version 0.1.38.9
