### ISSUE TITLE
Hatchling Para uses wrong footprint model when sprinting forward.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#196]
## Expected Behavior

Hatchling Para to use correct footprint model when sprinting forward.

## Current Behavior

Hatchling Para uses wrong footprint model when sprinting forward.
Video evidence: 
https://www.youtube.com/watch?v=kWR9o5EQ5yo&feature=youtu.be
Screenshot:
![theisle-win64-test_2018-05-12_16-34-14](https://user-images.githubusercontent.com/35901313/39960932-534da824-5602-11e8-9209-99e7dcca2ec7.png)
Right footprints: Footprints left when sprinting forward.
Left footprint: Footprints that are expected to be left.

## Steps to reproduce

-Spawn as hatchling para.
-Sprint forward, do not turn.
-Notice that the wrong footprints are left.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1997878/TheIsle.log)

> **Game Version:** 0.1.38.7 ( development ).

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.39.0
