### ISSUE TITLE
"Offspring" dinosaur icon will not reflect current gender

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#2]
## Expected Behavior

Offspring dinosaur icon to always reflect current gender

## Current Behavior

Offspring dinosaur icon does not always reflect current gender
Here's a screenshot:
![20180225015826_1](https://user-images.githubusercontent.com/35901313/36637513-19d06104-19bc-11e8-89b1-7462170f44bf.jpg)
I'm a male not fully grown Gallimimus, but offspring icon says that I am female
Note: Tested only with gallimimus
Tested on Official Dev 2
## Steps to reproduce

-Nest someone in game
-Wait until they reach adult stage
-Make sure the current gender is being reflected properly by the offspring icon

## Build Information
[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1755673/TheIsle.log)

> **Game Version:** 0.1.34.1 - 2554345 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by looterz** [comment]
I believe design wise right now, the icon you see over other players is meant to reflect your relationship to them, so it is showing the player that they are that characters mother.

**Comment by ExtraHu3** [comment]
Got it
Issue Closed.
