### ISSUE TITLE
Client player has no head tracking in replays

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#200]
## Expected Behavior

The head tracking should persist in replays for the client player.

## Current Behavior

The client player does not have head tracking in their replay, however every other player does.

## Steps to reproduce

1. Record a replay ingame, moving your head around a lot (T to record/stop replay.)
2. Exit out of the server and watch your replay.
3. Find yourself in the replay - watch as your own head will always face forward, however every other player's head will look in the direction they were facing.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
I believe this is due to network optimization, and fixing this would lead to degraded performance online.
