### ISSUE TITLE
Test level portal crashes dedicated servers

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#201]
## Expected Behavior

Walking through the portal on the test level should not crash dedicated servers.

## Current Behavior

If too many people walk through the portals, it can crash the server. 

From my testing it seems to happen with excessive use of them and doesn't necessarily need multiple people to go through at once (though that does make it crash faster.)

Highly likely that the crash is dependent on the server specs.

## Steps to reproduce

1. Spawn as anything on the test level, on a dedicated server.
2. Walk through the portal.
3. Doing this enough times will cause the server to crash.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
A bunch more safety checks have been put in place for these, shouldn't be so problematic now. Please test.

**Comment by looterz** [comment]
I've tested it locally and this seems to be fixed now.
