### ISSUE TITLE
Trike trot animation plays when walking (for other clients)

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#202]
## Expected Behavior

Proper animations should play for appropriate gaits.

## Current Behavior

When a player switches from trot to walk on adult triceratops, the trot animation continues playing, but the player moves at walking speed. Eventually the animation switches to the right one. This can only be observed with other players. Your dinosaur functions as intended.

https://www.youtube.com/watch?v=_lxhCnGu28Q

## Steps to reproduce

Log in as adult triceratops and trot in a straight line for a while, then switch to the walk. Have someone observe your animations.

It seems that this is more likely to happen when only a single form of input is performed over a period of time, like walking forward. When a lot of different keys are pressed frequently for turning, etc, it does not trigger.

## Build Information

> **Game Version:** 0.1.38.7 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
For clarification, does this happen when you yourself trot as Trike? Or only to other Trike players that's you're watching, as in the video?

**Comment by MortenSilver** [comment]
Only when watching others around me.

**Comment by Hypno123** [comment]
Seems to be fixed in 0.1.39.7
