### ISSUE TITLE
Bushes stripped of food appear uneaten from a distance

### ISSUE THREAD

**Issue by RagdollZombie** [TheIsleGame/bugs#205]
## Expected Behavior

Bushes that are stripped of leaves should appear to be stripped of leaves from a distance.

## Current Behavior

At a distance, bushes that have been eaten will appear to be untouched.

## Steps to reproduce

Spawn in as a herbivore
Find an uneaten blue bush and eat it until it becomes stripped of food.
Start walking away from it.
Notice that at a certain distance the model will change from the stripped version back to the uneaten bush model.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

![closebush](https://user-images.githubusercontent.com/16749057/40089497-e0b54e78-5860-11e8-89fc-64c8a0adcbb8.jpg)

![farbush](https://user-images.githubusercontent.com/16749057/40089503-e7d975f8-5860-11e8-9237-33e5d39a0b2d.jpg)

**Comment by Hypno123** [comment]
Fixed in 0.1.38.8
