### ISSUE TITLE
Hunger/thirst decays while in spectator mode

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#206]
## Expected Behavior

Hunger and thirst should not decay while in spectator mode.

## Current Behavior

When in spectator camera, the players hunger and thirst still decays - this could result in the player dying as soon as they exit the spectator camera.

## Steps to reproduce

1. Spawn as anything.
2. Enter spectator camera.
3. Wait until hunger and thirst decays.
4. Exit spectator and look at hunger/thirst.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Adding to this, stamina also decays (go into spectator while swimming, when you return you will have less stamina.)

**Comment by looterz** [comment]
Fixed in 0.1.39.0
