### ISSUE TITLE
Footprints get stretched out on steep surfaces

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#207]
## Expected Behavior

footprints should always be the same dimensions

## Current Behavior

if you step on a surface that is a bit steep, the footprint you leave will be stretched out vertically

## Steps to reproduce

walk over steep terrain, like the little cliffs on v3:
https://media.discordapp.net/attachments/264289779963789314/447253233405263883/footprints.png

(its probably worth noting that the brightness and contrast in that image have been edited so you can see the footprints clearer)

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
I've tried a few ways to adjust the decal rotation to try and avoid this, but it might be as good as it can get. However, if/when we get IK for foot placement the issue might go away, since the footprint will be much better aligned to the world. Will have to wait and see.

**Comment by Hypno123** [comment]
Minor issue that could potentially be fixed by foot IK. Can reopen with updated results should it be needed.
