### ISSUE TITLE
Puerta stomp damage is delayed

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#21]
## Expected Behavior

The Puerta stomp animation should only damage when its feet are close to touching the floor, crushing anything beneath them.

## Current Behavior

The Puerta currently kills anything that runs under its legs, even after its feet have touched the ground, for a few longer than it should.

https://www.youtube.com/watch?v=a6q8rGlgKXI

## Steps to reproduce

1. Spawn as Puerta
2. Have another player spawn as another species.
3. Stomp with left click and tell the other player to run in after the feet have touched the ground - They will die even after it would be safe to attack.

## Build Information

> **Game Version:** 0.1.34.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.3
