### ISSUE TITLE
Fall damage can be negated by entering spectator mode whilst falling.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#210]
## Expected Behavior

Fall damage to be applied even if the user enters and leaves spectator mode whilst falling.

## Current Behavior

Fall damage can be negated by entering spectator mode whilst falling.

Video evidence: 
https://youtu.be/v786DGsD6tg

## Steps to reproduce

-Select any character.
-Find somewhere high.
-Jump/fall from it.
-Enter spectator mode right before reaching the ground.
-Leave spectator mode.
-Notice that no damage will be received, your leg won't be broken and/or you won't die.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2019820/TheIsle.log)

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
This is normal.
