### ISSUE TITLE
Dinosaurs do not get wet in lakes

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#211]
## Expected Behavior

When a dinosaur comes out of a lake, it should appear wet upon exiting the water.

## Current Behavior

No wetness effects when interacting with a watersource.

## Steps to reproduce

Enter water, swim around, exit water. Observe that there are no changes to the skin.

## Build Information

> **Game Version:** 0.1.38.7 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
I believe this was simply yet to be added, though we can keep this up until it is.

**Comment by dinosauriac** [comment]
Do we have a feature request tag? This isn't really a bug and technically not even required for the water volumes to be called "done". Yeah, it's something that'd be nice to have, but requires a fair bit of R&D.

**Comment by Hypno123** [comment]
@dinosauriac We've had an "enhancement" tag before, though I'm not sure if you guys want the bug tracker filled with those?
