### ISSUE TITLE
Water Light Refraction Loop - Too Obvious

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#212]
## Expected Behavior

When you observe the light hitting the bottom of the watersource, it should appear as a seamless loop, with no clear beginning and end.

## Current Behavior

Currently the lighting effects in the water appears too obviously looped. You can observe the lighting moving back and forth in an event pattern that repeats quickly.

https://clips.twitch.tv/SuperGentleOkapiNomNom

## Steps to reproduce

Observe lighting in water source. See the loop which is not seamless.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:**  0.1.38.7 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Could you get a video to further explain the issue?

**Comment by dinosauriac** [comment]
If you're talking about the water caustics, this should already be fixed when the next build goes out. The panners were all going at the same rate, which caused them to line up instead of having random motion.

**Comment by Hypno123** [comment]
Fixed in 0.1.38.8
