### ISSUE TITLE
When jumping into/out of shallow water, there are no sound effects or ripple effects

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#213]
## Expected Behavior

Ripple or splash visual effect coupled with a water sound effect when jumping in interact-able water sources

## Current Behavior

No effects when jumping into or out of shallow water, even in areas where ripples appear when you walk/run through it.
https://clips.twitch.tv/SmokyTallTomatoMau5

## Steps to reproduce

Jump around in watersources, observe.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.7 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Please test.

**Comment by Hypno123** [comment]
Tested as Utahraptor. Still an issue in 0.1.39.7
