### ISSUE TITLE
Giga and Utah drinking sounds

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#216]
## Expected Behavior

Each stage of a dinosaurs life should have sounds according to their size. (Hatchling and juvenile could probably get away with being the same.)

## Current Behavior

The Giga and Utah currently use the same drinking sound for every stage of their life. This looks and sounds unnatural and is most noticeable when drinking as the Giga hatchling.

https://www.youtube.com/watch?v=fIkDqQbZHK0

## Steps to reproduce

1. Spawn as any stage of Utah or Giga.
2. Drink from watersource.
3. Respawn as another stage of that dinosaur.
4. Drink again and listen to the same drinking sounds.

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.39.0
