### ISSUE TITLE
Water sounds on ground on Thenyaw

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#217]
## Expected Behavior

Appropriate step sounds should play in relation to ground texture that is being walked on.

## Current Behavior

On the north side of swamp on Thenyaw, water step sounds play in certain spots when walking on the slope of the hill.

https://www.youtube.com/watch?v=u0GsEH4x3fg

## Steps to reproduce

Log in and walk around on the slope north of the swamp.

Tested on Dev 3.

## Build Information

> **Game Version:** 0.1.38.7 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Could definitely use a video or picture for the location of this.

**Comment by dinosauriac** [comment]
Might have fixed this one. The surface mesh was triggering overlap events, wasn't really necessary since there's a collision box in the water volume to handle that. With the overlap events disabled on the surface it seems to have solved the issue. Something to test next build.

**Comment by dinosauriac** [comment]
Test please.

**Comment by Aliens218** [comment]
The issue has been fixed ^^
