### ISSUE TITLE
Utah sliding during limp animation

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#218]
## Expected Behavior

Feet to stay in place on ground while moving forward as any dinosaur.

## Current Behavior

While limping, Utah's limp anim speed does not match with its movement speed, resulting in sliding feet while limping.

## Steps to reproduce

1. Spawn in as Utah
2. Break leg or toggle fake limp
3. Move around
Video: https://youtu.be/xEJk2ueDQ6s

## Build Information

> **Game Version:** 0.1.38.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.39.0
