### ISSUE TITLE
Juvie Maia has no footstep sounds

### ISSUE THREAD

**Issue by Queenz29** [TheIsleGame/bugs#219]
## Expected Behavior

You would expect the Juvie Maia to have footstep sounds.

## Current Behavior

Juvie Maia makes no sounds while walking/sprinting.

## Steps to reproduce

1) Spawn in as a Juvenile Maia
2) Start walking 

## Build Information

> **Game Version:** 0.1.38.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in revision 1239
