### ISSUE TITLE
Adult Galli has no sniffing animation/ sound effects

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#221]
## Expected Behavior

Adult Gallimimus has a sniffing animation and sound which is then followed by the scent mechanism (lit up footprints/bushes/corpses)

## Current Behavior

Adult Gallimimus has the scent mechanism but does NOT have the animation and sound effect.
(Juvi Gallimimus works appropriately.)

## Steps to reproduce

Be a Gallimimus. Hold q to sniff. 

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:**  0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in revision 1243
