### ISSUE TITLE
Juvi and Adult Gallimimus- No Thirst/water depletion

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#222]
## Expected Behavior

Gallimimus has thirst depletion with time.

## Current Behavior

Gallimimus seem to have 0 thirst depletion. You only need to fill up water as you grow to replenish new stat gains.

## Steps to reproduce

Be a gallimimus, observe thirst depletion at 0.6/0.6 (full juvi) and 1/1 growth (full adult).

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:**  0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.39.0
