### ISSUE TITLE
Subadult Carnotaurus can place nests.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#223]
## Expected Behavior

Subadult carno to be unable to place nests.

## Current Behavior

Subadult carno can place nests,unlike other subadults.
Note: Adult carno can't place nests.

Screenshot evidence:
![theisle-win64-test_2018-06-02_14-58-30](https://user-images.githubusercontent.com/35901313/40879951-170e08a8-667f-11e8-8855-42e686974ac6.png)

## Steps to reproduce

-Spawn as female subadult carno.
-Press B

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2065283/TheIsle.log)

> **Game Version:** 0.1.38.9 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by looterz** [comment]
Closing this in preparation for the new nest system.
