### ISSUE TITLE
Unable to bite while moving after opening ESC menu while sniffing and moving.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#224]
## Expected Behavior

Expected to be able to bite while moving after opening ESC menu while sniffing and moving

## Current Behavior

After opening ESC menu While sniffing and moving, player will be unable to bite while moving.
I.E.: Player character will stop to play the idle bite animation.

Video evidence:
https://youtu.be/JEu98-BbWiA

Using Scent again should fix this issue.
## Steps to reproduce

-Spawn as anything that can use scent while moving.
-Use Scent while moving.
-Press ESC while still using scent.
-Close ESC menu.
-Move and bite.
-Notice that character will stop to play idle bite animation.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2065314/TheIsle.log)

> **Game Version:** 0.1.38.9 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.0
