### ISSUE TITLE
Hatchling Giga uses adult idle sounds.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#225]
## Expected Behavior

Hatchling Giga to use separate idle sounds from adult.

## Current Behavior

Hatchling giga uses adult   idle sounds.

Video Evidence:
https://youtu.be/UQiGMiORfnA

## Steps to reproduce

-Spawn as hatchling Giga.
-Listen to the idle sounds.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2065322/TheIsle.log)

> **Game Version:** 0.1.38.9 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in 0.1.39.2
