### ISSUE TITLE
Juvi Dryo 3 and 4 calls are identical

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#226]
## Expected Behavior

I distinct sound between 3 and 4 call for the juvenile dryo.

## Current Behavior

3 and 4 call are identical

## Steps to reproduce

Be a juvenile dryo, try all of the calls.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in revision 1241
