### ISSUE TITLE
Juvi Galli sniffing sound effects of adult utahraptor

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#227]
## Expected Behavior

Juvenile gallimimus has either a silent sniff or a very quiet/soft sniff.

## Current Behavior

Juvenile Gallimimus has the sound effect of the adult utahraptor sniffing.

## Steps to reproduce

Be a juvi galli. Hold q to sniff.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Not a bug.
