### ISSUE TITLE
Juvi Maia lacks footprints/scent

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#228]
## Expected Behavior

Juvi Maia should have footprints and a scent correlating with the footprints.

## Current Behavior

Juvi Maia have no footprints for sprint/walk/trot, and thus, also do not have a scent.

## Steps to reproduce

Be a juvi maia and move around and sniff, observe that you lack prints or scent. Or, find a juvi maia as another creature and sniff it if it moves.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in revision 1240
