### ISSUE TITLE
Hatchling Dryo can use Scent,no other hatchling can.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#229]
## Expected Behavior

Hatchling dryo to be unable to use Scent.

## Current Behavior

Hatchling dryo can use Scent,meanwhile,no other hatchling can.
Video evidence:
https://youtu.be/74_HarHmJGM

## Steps to reproduce

-Spawn as hatchling dryo.
-Move.
-Use Scent.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2065360/TheIsle.log)

> **Game Version:** 0.1.38.9 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in next build.
