### ISSUE TITLE
Rain effects are missing on dinosaur skin 

### ISSUE THREAD

**Issue by dinosauriac** [TheIsleGame/bugs#231]
## Expected Behavior

Wetness & water droplets should appear on dino skin during rain. 

## Current Behavior

Call me crazy, but it looks like since this latest update the water droplets / rivulets and wet sheen have been missing from dinosaur skin during rain. Possibly related to the changes in how MPCs are handled? Have tried on listen server and several different online matches, observing both own skin and other players.

## Steps to reproduce

Be in a rain storm and see if your character looks wet. 

## Build Information

> **Game Version:**  0.1.38.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Looks like it to me as well, testing with a juvie utah.

**Comment by foszor** [comment]
Fixed in 0.1.39.0
