### ISSUE TITLE
Hatchling Dryo able to sniff/smell - scent mechanism enabled

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#232]
## Expected Behavior

Other hatchlings appear to not have the scent mechanism enabled. Hatchling dryo should not be able to use the scent mechanism.

## Current Behavior

Hatchling Dryos can use the scent mechanism

## Steps to reproduce

be a hatchling dryo and hold q

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.0
