### ISSUE TITLE
Hatchling dryo calls same as juvi dryo

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#233]
## Expected Behavior

When hitting 1, 2, 3, 4, f... there should be a call that is all the same across the board and unique to the hatchling, like the other species' hatchlings have

## Current Behavior

Hatchling dryo shares the exact same calls as the juvenile dryo

## Steps to reproduce

Be a hatchling dryo. Test 1 2 3 4 f calls. Notice they are the same as Juvi dryo.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
