### ISSUE TITLE
Adult Giga Calf-Hamstring Clipping Rest Animation H

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#235]
## Expected Behavior

When resting (h), the hamstring should lay over the top of the calf of the giganoto.

## Current Behavior

Calf currently clips through the hamstring of the giganoto when resting (h)

## Steps to reproduce

Be an adult giga, press H to rest, observe posterior side of legs. Calf will clip through the hamstring significantly.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Can you add a picture to this report?

**Comment by Hypno123** [comment]
Added to #501
