### ISSUE TITLE
Dinosaurs can jump while using scent.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#236]
## Expected Behavior

Dinosaurs to be unable to jump while using scent

## Current Behavior

Dinosaurs can jump while using scent.

Video evidence:
https://www.youtube.com/watch?v=r6JL3cB6g_o&feature=youtu.be

## Steps to reproduce

-Spawn as anything able to use scent and jump
-Use scent.
-jump while using scent.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2065570/TheIsle.log)

> **Game Version:**0.1.38.9 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.0
