### ISSUE TITLE
Carnotaurus Adult movement issue

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#237]
## Expected Behavior

Carnotaurus to completely stop sliding when using alt turn.

## Current Behavior

Carnotaurus slides when it alt turns, meaning that it can cut its turning radius in half by tapping alt turn and sprinting while turning. It can also reach top speed, tap alt turn (don't actually turn, just keep sprinting ahead) and continue to move forward to lose less stamina than it would by sprinting normally. The deceleration allows you to keep speed. 

## Steps to reproduce

Be Carnotaurus Adult, tap alt turn while either sprinting at top speed or while turning. 

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Aliens218** [comment]
True Alpha is credited with this discovery.

**Comment by foszor** [comment]
Fixed in 0.1.39.0
