### ISSUE TITLE
Maiasaura and Dryosaurus stretched hatchling/juvenile corpses

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#240]
## Expected Behavior

The hatchlings and juveniles of Maiasaura and Dryosaurus to ragdoll normally.

## Current Behavior

The hatchlings and juveniles of Maiasaura and Dryosaurus stretch to abnormal proportions upon death.
[https://imgur.com/a/EMop1m8](url)

## Steps to reproduce

Be Juvenile Maiasaura, Juvenile Dryosaurus, Hatchling Maiasaura, and Hatchling Dryosaurus. Die, and your corpse will stretch.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.38.9 (dev)
> **Operating System**: Windows

> **Network Role**: Client

**Comment by ExtraHu3** [comment]
Same thing happens to Hatchling allosaurus,is also present on Juvenile stage:
![theisle-win64-test_2018-06-16_11-42-54](https://user-images.githubusercontent.com/35901313/41499678-604cb9ca-715a-11e8-9853-efe1705b8fac.png)

**Comment by Hypno123** [comment]
Going to add these to #347 for a more complete list.
