### ISSUE TITLE
Dinosaurs not swimming

### ISSUE THREAD

**Issue by Queenz29** [TheIsleGame/bugs#241]
## Expected Behavior

You would expect the Dinosaur to start swimming in the deeper water of the swamp.

## Current Behavior

Survival Dinosaurs do not swim in the swamp on Thenyaw, they can stand/walk/crouch in water that is too deep for them to stand/walk/crouch in.
Tested on one specific location in the swamp as Adult Giga.
https://cdn.discordapp.com/attachments/424338907375599616/452788506230784000/giga.png
https://cdn.discordapp.com/attachments/424338907375599616/452789103176581140/giga.png
Location:
https://cdn.discordapp.com/attachments/424338907375599616/452792690287968267/giga.png
https://cdn.discordapp.com/attachments/424338907375599616/452794993619238912/giga.png
Also watched players as both Trike and Utah walk on the surface in the exact same location.

## Steps to reproduce
For the specific case shown in the screenshots.
1)Spawn in as Adult Giga
2)Go to the location attached in the screenshot and walk into the water.
3)Try to crouch in the exact same location.

## Build Information

> **Game Version:** 0.1.38.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Queenz29** [comment]
I can test it on the other ones aswell in about an hour, will add them to this issue if necessary.

**Comment by dinosauriac** [comment]
I think this might actually have to do with the capsule height values in the dino blueprints not being adjusted. Trying it out in test level the new characters *can* swim, but they tend to swim well below the water surface. So, since the swimming level is a bit lower in most of Thenyaw's water sources they're able to just walk through the swamp for example.

**Comment by dinosauriac** [comment]
I've gone and adjusted the swamp water volume on Thenyaw to be a little higher which should help, but the new classes might still need some fine tuning.

**Comment by Hypno123** [comment]
Closing until further reports are made.
