### ISSUE TITLE
Character selection screen doesn't show Adult Carnotaurus gendered skin differences.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#242]
## Expected Behavior

Character Selection screen to show skin differences when selecting different Genders for Adult Carnotaurus.

## Current Behavior

Character Selection screen shows the same skin regardless of gender selected for Adult Carnotaurus. (Default male skin)
 
Screenshot evidence:
Male:
![20180603135000_1](https://user-images.githubusercontent.com/35901313/40889027-3850d2f4-6736-11e8-9c9e-57f01acd9f57.jpg)

Female:
![20180603135001_1](https://user-images.githubusercontent.com/35901313/40889035-431dad10-6736-11e8-96b6-eebb273542a4.jpg)

Note: If player selects female,Female carnotaurus skin will be applied in-game.
## Steps to reproduce

-Select Carnotaurus in Character Selection screen.
-Select Different genders.
-Notice that there's no skin differentiation between genders.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2066167/TheIsle.log)

> **Game Version:** 0.1.38.9 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by ExtraHu3** [comment]
Originally reported by Kuun Watermeluun#2653 in Isle Discord

**Comment by foszor** [comment]
Fixed in 0.1.39.0
