### ISSUE TITLE
trikes can stomp while getting up

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#243]
## Expected Behavior

adult and subadult trike should not be able to stomp while it is in the "getting up" animation

## Current Behavior

adult trike can stomp during the "getting" animation (but not when it is actually resting)

its also worth noting that sub adult/adult can also headbutt while getting up, but i dont know if thats intended or not

## Steps to reproduce

be an adult trike, press H to rest, then press H again to get up and quickly press left mouse

## Build Information

> **Game Version:** 0.1.38.9 (development)

> **Operating System**: Windows
> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.39.0
