### ISSUE TITLE
Utah juvenile can't drink or eat while crouching

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#245]
## Expected Behavior

Utah juvenile should be able to drink while crouching.

## Current Behavior

Utah juvi can't drink or eat while crouching.

## Steps to reproduce

Log in as a utah juvi and try to drink while crouching.

## Build Information

> **Game Version:** 0.1.38.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Not an issue in 0.1.40.3
