### ISSUE TITLE
Able to sniff while sprinting

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#246]
## Expected Behavior
You are unable to begin sniffing while in sprint.  Ergo, you probably should not be able to sprint while sniffing.

## Current Behavior

Currently while walking and sniffing, you are able to begin sprinting.

## Steps to reproduce

1) Spawn in as anything that is able to walk/trot and sniff simultaneously (which I think is currently anything).
2) Move while sniffing.
3) While holding W/A/S/D and your Scent key, begin holding down Shift to sprint.
4) Continue holding your Scent key while running, until scent activates.

Video: https://youtu.be/MX3vUHPjOSY

## Build Information

> **Game Version:** 0.1.38.9

> **Operating System**: Windows

> **Network Role**: Client, Listen Server or Dedicated Server

**Comment by looterz** [comment]
Fixed in 0.1.39.0
