### ISSUE TITLE
Juvi diablo stretches on death

### ISSUE THREAD

**Issue by fubar345** [TheIsleGame/bugs#247]
## Expected Behavior

Juvi diablo should not stretch on death.

## Current Behavior
 Juvi diablo stretches on death

## Steps to reproduce

Pick juvi diablo.
Go and die.
Watch your body stretch.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 1.39.1(dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Doesn't seem to be an issue in 0.1.39.7
