### ISSUE TITLE
All dinosaurs cannot roar while resting

### ISSUE THREAD

**Issue by TI-ghostway** [TheIsleGame/bugs#248]
## Expected Behavior

While resting, dinosaurs should still be able to use their roars.

## Current Behavior

If a dinosaur is resting, then it is unable to use any of the 1-4 roars and the F roar (default keys).

## Steps to reproduce

1 - Play as any dinosaur.
2 - Press H (default key) to rest.
3 - Attempt to use 1-4 or F roar (default keys) and notice that no sound or animation plays.

## Build Information

> **Game Version:** 0.1.39.1 (Dev Branch)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed as of patch 0.1.39.5
