### ISSUE TITLE
Small Herbivore music while playing as Juvi and Adult Cerato

### ISSUE THREAD

**Issue by FatLemur** [TheIsleGame/bugs#250]
## Expected Behavior

The in game music would play either the small or large carnivore themes

## Current Behavior

The in game music is stuck on the small herbivore music cycle while playing as cerato 

## Steps to reproduce

Play as cerato

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** The in game music

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
I'm not sure if music id is setup to play certain tracks based on diet/species yet. Correct me if I'm wrong.

**Comment by Hypno123** [comment]
Music playing based on diet etc is more of an enhancement than a bug.
