### ISSUE TITLE
Fresh Dilophosaurus Adult smaller than maximum Juvenile Dilophosaurus

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#251]
## Expected Behavior

The fresh Dilophosaurus Adult to be slightly larger than the maximum Juvenile Dilophosaurus

## Current Behavior

The maximum Juvenile Dilophosaurus is larger than a fresh spawn Dilophosaurus Adult

## Steps to reproduce

Have someone stay as a maximum sized Juvenile Dilophosaurus while you grow into an adult Dilophosaurus. The Juvenile will be larger.

[https://i.imgur.com/XEsNpvZ.png](url)

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Aliens218** [comment]
Meownster is credited with this discovery!

**Comment by Hypno123** [comment]
Fixed in 0.1.39.4
