### ISSUE TITLE
Dilo smells faster trotting than standing

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#252]
## Expected Behavior

The smelling loop should take the same amount of time to play regardless of movement.

## Current Behavior

The dilo gets smells to pop up after 1 sec while trotting and at least a full loop (sometimes more) while standing.

## Steps to reproduce

Log in as dilo, trot and sniff vs stand and sniff.

## Build Information

> **Game Version:** 0.1.39.3 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Some dinosaurs don't have their final scent animations, when those are added this will be fixed.
