### ISSUE TITLE
Dilo juvenile slides while crouching

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#253]
## Expected Behavior

Dilo juvenile should sneak without sliding.

## Current Behavior

Dilo juvenile slides when crouching.

## Steps to reproduce

Log in as dilo juvenile and crouch.

## Build Information

> **Game Version:** 0.1.39.3 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Closing this for an updated report.
