### ISSUE TITLE
Adult galli is unable to attack/does not show attack animation.

### ISSUE THREAD

**Issue by fubar345** [TheIsleGame/bugs#254]
## Expected Behavior

Adult galli should display an attack animation/ be able to attack.

## Current Behavior

Adult galli does not display an attack animation/be able to attack

## Steps to reproduce

1: pick  adult galli
2: attempt to attack and notice nothing happens.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 1.39.3(dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed.
