### ISSUE TITLE
Dilophosaurus Adult cannot eat from carcasses larger than it

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#255]
## Expected Behavior

The Dilophosaurus Adult to have the capability to eat from carcasses larger than it.

## Current Behavior

The Dilophosaurus Adult cannot eat from carcasses larger than it.

https://i.imgur.com/oGkSh1q.jpg

## Steps to reproduce

Become Dilophosaurus Adult, scout out a large gore pile, try to eat from it.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 1.39.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.4
