### ISSUE TITLE
Dryo full-bodied animation for calls - stands while crouched

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#256]
## Expected Behavior

Dryo is able to make vocalizations 1 2 3 4 f attack while crouched, and will remained crouched.

## Current Behavior

Dryo stands up while crouching and calling/biting to complete the full bodied animation. Bug only works if standing still. Crouch-walk + call is fine.

## Steps to reproduce

Be Juvi/adult dryo. Crouch and stay still. Make various calls and notice dryo standing

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
