### ISSUE TITLE
Juvi Galli unable to Attack. 

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#259]
## Expected Behavior

Both Juvi and Adult galli can attack with left mouse button click while standing/running/walking/trotting.

## Current Behavior

Only Adult galli can attack. Juvenile galli cannot attack at any time.

## Steps to reproduce

Be a galli, grow from juvi to adult, test attacks.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.5
