### ISSUE TITLE
Aiming down sight bug

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#26]
## Expected Behavior

The camera should come out of 'aiming down sight' mode when switching weapons.

## Current Behavior

The camera does not leave the ADS mode when changing weapons, causing it to be difficult for the player to see. https://www.youtube.com/watch?v=em3kmypQFaU

## Steps to reproduce

1. Spawn as human.
2. Aim down the sight of your gun.
3. Switch weapons with 3/4 and notice the camera is still aiming down the sight of the last gun.

## Build Information

> **Game Version:** 0.1.34.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Closing this in preparation for the human rewrite.
