### ISSUE TITLE
Repeating pain/damage sound effect after being hit

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#260]
## Expected Behavior

When you hit another dino, the dino taking damage should have a pain/damage sound effect when being hit and then not make any pain sounds unless actively taking damage.

## Current Behavior

If another player causes you damage (and you live), afterwards, if the aggressor player makes a vocalization (1 2 3 4 f), if you are AT A DISTANCE, you (the victim) will make a pain/damage sound every time the aggressor vocalizes.  This does NOT work if you are close together.  It does NOT work if its a sound created by biting (ex: dryo bite-yelling). 

https://clips.twitch.tv/ApatheticHelplessHamburgerPrimeMe

## Steps to reproduce

Be a dinosaur, and have a weaker dino (or one that won't kill you) attack you. Then create distance between you and the other user, and have the aggressor make vocalizations and observe your own dino making pain sounds.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed until confirmed otherwise.
