### ISSUE TITLE
The noose of the cerato goes into the ground when sniffing

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#261]
## Expected Behavior

The noose of the cerato shouldn't go into the ground when he is sniffing

## Current Behavior

The noose of the cerato goes into the ground when sniffing

Juvy : https://youtu.be/jvs6iyKT8sA
Adult : https://youtu.be/OS4nkyUPGGM

## Steps to reproduce

1. Take a cerato at stage "Adult" or "Juvy"
2. Sniff

## Build Information

> **Game Version:** 0.1.39.4 (development)
> **Operating System**: Windows
> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
