### ISSUE TITLE
Invisible/Invinsible Allo

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#262]
## Expected Behavior

The Allo should have a model

## Current Behavior

The Allo has no model but can still do damage to other creatures without taking any damage
https://youtu.be/GV3wYoMiTA4

## Steps to reproduce

1. Spawn as an Allo on Sandbox

## Build Information

> **Game Version:** 0.1.39.4 (development)
> **Operating System**: Windows
> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.39.9
