### ISSUE TITLE
Galli Scent Animation Stuck Freeze bug

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#264]
## Expected Behavior

Galli players can hit the scent button multiple times and it should not cause the player to get stuck.

## Current Behavior

If you play galli (adult and juvi) and hold the scent button for 1 second, let go, then immediately TAP the scent button, the galli is then stuck in place and cannot move WASD- JUMP. Player gets unstuck by attacking or H (resting). Player CAN vocalize but it doesn't not free the player from being stuck.

https://clips.twitch.tv/VivaciousIncredulousBaconLitty

## Steps to reproduce

See Above

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed as of revision 1392
