### ISSUE TITLE
Scent interrupts roar and allows to bite

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#265]
## Expected Behavior

If a dinosaur roars, it should play through the full animation and not be able to perform any other action with it's head.

## Current Behavior

Using scent while roaring will interrupt the roar animation, allowing the dinosaur to bite as soon as the scenting button is let go. The roar audio still plays entirely.

## Steps to reproduce

Log in as a dinosaur. Roar, hold scent button during the roar animation, then immediately click to bite.

Does not work for carno or para. They return to the roar animation once the scent button is let go.

## Build Information

> **Game Version:** 0.1.39.5 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.6
