### ISSUE TITLE
Juv. Maia/Dryo/Cerato/Dilo and Adult Dryo do not leave gore piles

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#266]
## Expected Behavior

For all dinosaurs, when a dead body is sufficiently eaten a gore mesh should be left behind

## Current Behavior
These dinosaurs do not leave a gore mesh when eaten:
-Juv. Maia
-Juv. and Adult Dryo
-Juv. Cerato
-Juv. Dilo

## Steps to reproduce
1. Spawn in as a carnivore
2. Have another player spawn in as one of the listed dinosaurs
3. Kill and eat them
4. Note that no ribcage spawns

## Build Information

> **Game Version:** 0.1.39.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
These classes do not have enough food to warrant a corpse.
