### ISSUE TITLE
Plants and gores stay highlighted if scenting on death

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#267]
## Expected Behavior

Plants and gores should not be highlighted after death.

## Current Behavior

If the dinosaur uses the scent mechanic and dies while the food is highlighted, that food will remain highlighted. If the food item highlighted isn't the food item for the current dinosaur, the food item will remain highlighted permanently. If the food item matches the current dinosaur, the highlight timer on the food gets reset and it eventually fades like intended. 

![image](https://user-images.githubusercontent.com/38515115/41205126-82961632-6cbb-11e8-9e63-494c4a91ca56.png)

Ex. I smelled the plants as a diablo and was killed while they were highlighted. I spawned in as cerato and the plants remained highlighted. Smelling again did not remove highlights from the plants.

## Steps to reproduce

Log in and find appropriate food. 
Smell to highlight. 
Be killed while the food is highlighted. 
Return as something else and observe.

## Build Information

> **Game Version:** 0.1.39.5 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.6
