### ISSUE TITLE
Para juvi and adult do not deplete water thirst

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#268]
## Expected Behavior

Para should lose thirst with time.

## Current Behavior

Paras of any age do not deplete water.

## Steps to reproduce

Be a para of any age, at the top of your age (fully grown juvi, fully grown adult). Drink until full (just for a clearer observation). Then wait and notice you do not drop thirst.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.5 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.6
