### ISSUE TITLE
Trike juvi adult does not deplete thirst water

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#269]
## Expected Behavior

Trike juvi/adult loses thirst with time

## Current Behavior

Trike juvi and adult do not deplete their water.

## Steps to reproduce

Be a juvi or adult trike at it's fully grown stage. Drink water to fill up for reference. Wait and notice that you do not deplete thirst and will remain full of water.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:**  0.1.39.5 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.39.6
