### ISSUE TITLE
Silently firing

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#27]
## Expected Behavior

Firing a weapon should always make a sound, even after it has just been unholstered.

## Current Behavior

Firing your weapon immediately after taking it out can cause the bullet to be silent, if done quick enough. 

https://www.youtube.com/watch?v=KCLOTPHwZOg

## Steps to reproduce

1. Spawn as mercenary.
2. Press V to enable combat mode (take off safety)
3. Put the weapon away with 4.
4. Take the weapon out with 1 and click immediately to fire a bullet silently.

## Build Information

> **Game Version:** 0.1.34.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Closing this in preparation for the human rewrite.
