### ISSUE TITLE
Trike 3 call roar . Dust cloud effect present when resting (h)

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#270]
## Expected Behavior

When an adult trike is laying down and 3 roaring, the dust/dirt effect should not be present because the foot is laying still.

## Current Behavior

When the adult trike is laying and 3 roars, there is a dirt/dust effect even though the foot does not move.

## Steps to reproduce

Be an adult trike. Lay down. 3 roar. Observe left forefoot.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.5 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed in next build.
