### ISSUE TITLE
Salad Tosser needs to prevent plants spawning underwater 

### ISSUE THREAD

**Issue by dinosauriac** [TheIsleGame/bugs#271]
## Expected Behavior

Procedural foliage should only appear on land. 

## Current Behavior

The new edible plants done through procedural generation are being spawned under water sources. 
This not only looks wrong, but makes those plants in particular completely unusable. 

## Steps to reproduce

Observe procedural foliage generated on Isle-V3

## Build Information

> **Game Version:**  0.1.39.7 

> **Operating System**: Windows

> **Network Role**: Client, Dedicated Server

**Comment by Hypno123** [comment]
Fixed in 0.1.39.9
