### ISSUE TITLE
Giga hatchling idle animation pauses when biting

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#273]
## Expected Behavior

Giga hatchling idle animation should not stop when biting.

## Current Behavior

Giga hatchling currently stops playing its idle animation when biting.

https://www.youtube.com/watch?v=nBFR0vfGgOY

## Steps to reproduce

1. Spawn as giga hatchling.
2. Stand still to play idle animation.
3. Bite and watch the animation pause, then resume playing.

## Build Information

> **Game Version:** 0.1.39.7 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed as of revision 1506
