### ISSUE TITLE
Allosaurus juvenile and hatchling camera doesn't collide with ground

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#277]
## Expected Behavior

The camera should collide with the ground.

## Current Behavior

The juvenile and hatchling allosaurus camera does not collide with the ground.

![image](https://user-images.githubusercontent.com/30550499/41498506-7b299d28-7167-11e8-9921-36d93a43eb7b.png)

## Steps to reproduce

1. Spawn as either juvenile or hatchling allosaurus.
2. Place camera under the ground.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Should be fixed next build.
