### ISSUE TITLE
Allosaurus right footprint is backwards

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#278]
## Expected Behavior

The footprints should be facing the direction of the creature.

## Current Behavior

The right footprint currently faces backwards for the Allosaurus

![image](https://user-images.githubusercontent.com/30550499/41498528-f9ee5a0e-7167-11e8-93a1-b427e5c462f6.png)

## Steps to reproduce

1. Spawn as Allosaurus.
2. Run forward and watch right footprint be placed backwards.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
