### ISSUE TITLE
Allosaurus juvenile does not place footprints

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#279]
## Expected Behavior

The Allosaurus juvenile should be placing footprints.

## Current Behavior

The Allosaurus juvenile does not place footprints.

![image](https://user-images.githubusercontent.com/30550499/41498544-304ff9d6-7168-11e8-9fdf-edd2fc9470cf.png)

## Steps to reproduce

1. Spawn as Allo juvie.
2. Run forward; no footprints are placed.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
