### ISSUE TITLE
Allosaurus eating animation does not loop

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#281]
## Expected Behavior

The Allosaurus eating animation should loop automatically.

## Current Behavior

The eating animation does not loop, you have to hold E after the montage has finished to begin eating again.

https://www.youtube.com/watch?v=JP48MiWINqk

## Steps to reproduce

1. Spawn as Allo (any stage.)
2. Find a corpse.
3. Hold E to eat. At the end of the montage, it will not loop and will require the player to hold E again.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Think this one is fixed. Try it out again next build to be sure.

**Comment by Aliens218** [comment]
This issue has been fixed.
