### ISSUE TITLE
Allosaurus and Rex juvenile corpses decay too quickly

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#282]
## Expected Behavior

Allosaurus and Rex juvenile corpses should last longer.

## Current Behavior

They currently decay to gore after a few seconds.

https://www.youtube.com/watch?v=F5oVzpdyQo4

## Steps to reproduce

1. Spawn as any dinosaur.
2. Kill a juvenile rex or allosaurus.
3. Watch the corpse turn to gore after a few seconds.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.40.0
