### ISSUE TITLE
Allosaurus juvenile uses quadruped footstep sound

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#283]
## Expected Behavior

Allosaurus juvenile should use the bipedal sound when walking/running.

## Current Behavior

Allosaurus juvenile currently uses the quadruped footstep sound.

## Steps to reproduce

1. Spawn as Allosaurus juvenile.
2. Run forward and listen to the sound of four feet instead of two.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
