### ISSUE TITLE
Allosaurus and Carnotaurus health regen too low

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#285]
## Expected Behavior

Allosaurus and Carnotaurus health regeneration should be much higher for its tier.

## Current Behavior

Both species currently sit at 25 health regeneration. Cerato is in the same tier and has 230.

Allo:
![image](https://user-images.githubusercontent.com/30550499/41498841-f222ee78-716e-11e8-9f73-3b994bb81358.png)

Cerato:
![image](https://user-images.githubusercontent.com/30550499/41498843-fdc6c27c-716e-11e8-8008-8d9ead8f2e92.png)

## Steps to reproduce

1. Spawn as adult Allo/Carno, check stats.
2. Change to Cerato and check its stats.
3. Notice Allo/Carno have far too weak health regen for their tier.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Aliens218** [comment]
This issue has been remedied in  0.1.40.0, I believe.
