### ISSUE TITLE
Corpses do not leave blood pools

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#287]
## Expected Behavior

Corpses should leave blood pools so that they can be picked up in scent. 

This is not to be confused with gore piles; this is referring to the ragdolls.

## Current Behavior

Killing a player will not cause a blood pool to pour from their corpse. 

This means that using scent will not pick up a corpse until it turns to a gore pile.

![image](https://user-images.githubusercontent.com/30550499/41499331-25825f40-7176-11e8-9419-e90072fd5365.png)
As you can see from the picture; gore piles are detected, bodies are not.

## Steps to reproduce

1. Kill a player.
2. Wait for their corpse to make a blood pool (it won't happen.)
3. Attempt to detect the corpse using scent. Nothing will appear because no blood pool is made.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by RagdollZombie** [comment]
Something I would like to note. Dinos dying from starvation or dehydration would still be unable to be scented if scent relied on the blood pool and not the actual ragdoll corpse. On the other hand, making every dino ragdoll have a blood pool would be strange if the dinosaur did die of something like starvation, which normally wouldn't leave a blood pool.

**Comment by dinosauriac** [comment]
This isn't a bug, it's a feature request, and one that will obviously get added in the future.

**Comment by Hypno123** [comment]
Closing this to keep bug tracker clear of enhancements.
