### ISSUE TITLE
Animals can interact with objects while losing momentum.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#289]
## Expected Behavior

Animals should be unable to interact with objects (Gore piles,corpses,nests,water,etc.) while losing momentum just like animals can't use Alt-turn while losing momentum.

## Current Behavior

Animals can interact with objects while losing momentum.
Result is usually unexpected sliding while interaction animation is played.

Video Evidence:
https://youtu.be/43rRYxVTIS4

## Steps to reproduce

Play as anything that has momentum and interact with objects (Corpses,gore piles,water etc.).

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2108469/TheIsle.log)

> **Game Version:**  0.1.39.9 ( development ).

> **Operating System**: Windows 10.

> **Network Role**: Client.

**Comment by looterz** [comment]
Fixed in 0.1.40.0
