### ISSUE TITLE
Gallimimus slides its feet when initiating sniffing animation

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#290]
## Expected Behavior

Gallimimus takes a step to assume the standing position for the sniffing animation.

## Current Behavior

Gallimimi' feet slide into side-by-side position while initiating the sniffing animation.

## Steps to reproduce

Be a gallimimus. Hold q. Observe feet.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed.
