### ISSUE TITLE
Allosaurus can move while getting up.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#291]
## Expected Behavior

Allosaurus should be unable to move while getting up from rest animation.

## Current Behavior

Allosaurus can move while getting up from rest,resulting in sliding.
Video evidence:
https://youtu.be/PpigVQps2Vk

## Steps to reproduce

-Rest as an allosaurus and try to move while getting up from rest animation.
-Notice that character will start moving and sliding before animation is complete.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2108476/TheIsle.log)

> **Game Version:** 0.1.39.9 ( development )

> **Operating System**: Windows 10.

> **Network Role**: Client.

**Comment by Aliens218** [comment]
This issue still exists in 0.1.40.0

**Comment by dinosauriac** [comment]
This should be fixed with the next build, there many be a very brief slide as it transitions from idle to walking state but your controls should be properly locked til that time.

**Comment by Hypno123** [comment]
Fixed.
