### ISSUE TITLE
Dark Border surrounding moon- too obvious

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#292]
## Expected Behavior

Moon should appear seamless with the night sky.

## Current Behavior

Moon as a sizable black border surrounding it which is obvious especially against a starry sky.

https://steamuserimages-a.akamaihd.net/ugc/912423900272582944/77F195942BD8EABB321F6DD7110EAC5CBC571595/

## Steps to reproduce

Observe the moon when it is night out, against multiple weather conditions (Clear, cloudy, etc). Notice dark ring around the moon.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the new issue, please do so.

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
The mask could potentially be tighter, but there's usually a glow there to obscure it not being exact. 
I think this is a quirk of the nightvision mode rendering.

**Comment by Hypno123** [comment]
Fixed.
