### ISSUE TITLE
Underwater texture applied to dry land V3

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#293]
## Expected Behavior

The ground should display appropriate textures.

## Current Behavior

The underwater shimmer texture is applied to a section above water.

![image](https://user-images.githubusercontent.com/38515115/41578077-6d52cf8c-735e-11e8-87be-629b33caf6fa.png)
![image](https://user-images.githubusercontent.com/38515115/41578090-78cf7eaa-735e-11e8-9db9-04c56b80083f.png)

## Steps to reproduce

Travel to the indicated coordinates.

## Build Information

> **Game Version:** 0.1.39.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed with changes to that area.
