### ISSUE TITLE
Adult trike shadow disappears

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#294]
## Expected Behavior

Shadows should display during the appropriate conditions.

## Current Behavior

The shadow will disappear at certain camera angles for other players. Shadows are on Medium setting.

https://www.youtube.com/watch?v=vhxNSINCDDM

## Steps to reproduce

Observe another triceratops player.

## Build Information

> **Game Version:** 0.1.39.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by MortenSilver** [comment]
If this isn't an issue due to the Shadow setting being on Medium instead of Epic, please close the thread. I wasn't sure, so I figured I'd report it.

**Comment by Hypno123** [comment]
Fixed.
