### ISSUE TITLE
Triceratops thirst gain is too small

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#295]
## Expected Behavior

Triceratops should be able to gain thirst back from drinking in a reasonable amount of time.

## Current Behavior

Triceratops thirst gain is very small, forcing the player to drink for several minutes.

## Steps to reproduce

Log in as an adult triceratops and drink.

## Build Information

> **Game Version:** 0.1.39.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.40.0
