### ISSUE TITLE
Allosaurus footsteps are backwards or double. 

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#296]
## Expected Behavior

I expect when walking, trotting, and running that the footsteps would be forward facing.

## Current Behavior

Currently while walking and trotting, the Allosaurus footsteps are backwards. When the Allosaurus is running, there are double footsteps.

## Steps to reproduce
Walk or trot as the Allo to get a backwards footprint. Run as the Allo to get double footprints. 
![20180620164007_1](https://user-images.githubusercontent.com/40440922/41683586-fcaf0aba-74a8-11e8-9709-32e2eedf7b3b.jpg)
![20180620164015_1](https://user-images.githubusercontent.com/40440922/41683590-fe22f3de-74a8-11e8-89be-cf21c85577a0.jpg)
![20180620164029_1](https://user-images.githubusercontent.com/40440922/41683592-ffcade7c-74a8-11e8-8c21-5c58c713388e.jpg)

> **Game Version:** 0.1.39.9 (development) 

> **Operating System**: Windows 10 

>**Network Role**: Client

**Comment by Hypno123** [comment]
Reported in #278 

Make sure to check closed issues before posting! :)
