### ISSUE TITLE
Players can get stuck in trees

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#297]
## Expected Behavior

The dinosaurs should be able to bump into trees without getting stuck.

## Current Behavior

Players have a chance to get stuck on a medium sized tree when touching it.

![image](https://user-images.githubusercontent.com/38515115/41685044-4eed3140-74ad-11e8-8252-4946e759bf10.png)

This is the type of tree. If the dinosaur is still growing, "growth pops" will free you from the tree. Otherwise, the only option is to /stuck, but it doesn't always work.

## Steps to reproduce

Log in as an any species and bump into trees until you get stuck.

## Build Information

> **Game Version:** 0.1.39.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
I believe other species are effected by this too, needs checking.

**Comment by MortenSilver** [comment]
I just got a carno stuck soon as I touched a tree. Probably safe to assume others would be affected too.

**Comment by MortenSilver** [comment]
Allo and Rex confirmed.

**Comment by Hypno123** [comment]
Fixed until confirmed otherwise.
