### ISSUE TITLE
Adult Utah's arm clipping through its body while in sniff animation.

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#298]
## Expected Behavior

While sniffing, I expect the Utah's arms to be on the sides of the body.

## Current Behavior

When in sniff animation as an adult Utah, the left arm clips through its body.

## Steps to reproduce
Press Q to sniff, and watch the arm clip through.
![20180620180313_1](https://user-images.githubusercontent.com/40440922/41687176-b6848aea-74b4-11e8-88c5-c10299b803f6.jpg)
![20180620180313_2](https://user-images.githubusercontent.com/40440922/41687181-b8c5da7a-74b4-11e8-8245-63a37a8b7f18.jpg)
![20180620180322_1](https://user-images.githubusercontent.com/40440922/41687186-baa65086-74b4-11e8-8e8f-2afa0cc9b799.jpg)

> **Game Version:** 0.1.39.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
