### ISSUE TITLE
Hatchling Dilo cannot use it's 4 call.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#299]
## Expected Behavior

Hatchling Dilo to be able to use it's 4 call.

## Current Behavior

Hatchling Dilo cannot use it's 4 call
Can use any other call.
Using voice wheel doesn't work either.

## Steps to reproduce

Be hatchling Dilo and try to use your 4 call.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2121344/TheIsle.log)

> **Game Version:** 0.1.39.9 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by dinosauriac** [comment]
I know this is still technically a bug, but does it matter? Hatchlings only have one call.

**Comment by ExtraHu3** [comment]
I can see your point,lacking a call as a hatchling doesn't impact gameplay like other issues do,so feel free to close this one.
