### ISSUE TITLE
Survival juvenile gallimimus can create nests

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#3]
## Expected Behavior

Juvenile Gallimimus to NOT be able to create nests

## Current Behavior

Juvenile Gallimimus is able to create nests
Here's a screenshot:

![theisle-win64-test_2018-02-24_23-19-31](https://user-images.githubusercontent.com/35901313/36637550-04c60ae2-19bd-11e8-98df-6d1c9b00ebcf.jpg)
Tested on Official Dev 2
## Steps to reproduce

-On character selection screen, choose juvenile Gallimimus 
-Make sure to select female Gallimimus
-Confirm
-Press b (or current "place nest" key/button)
-A nest will be created

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1755678/TheIsle.log)

> **Game Version:** 0.1.34.1 - 2554345 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client.

**Comment by looterz** [comment]
Fixed in the hotfix for `0.1.34.1`.
