### ISSUE TITLE
Chat messages are not received when on character select screen

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#30]
## Expected Behavior

Chat messages should still be received even when on the character select screen. This may lead to messages going unseen by players when playing sandbox etc.

## Current Behavior

Chat messages are not received when the player is on the character select screen.

## Steps to reproduce

1. Spawn as anything, see the global chat normally.
2. Hit respawn and tell another player to type into global chat.
3. While on the character select menu, all messages sent will not be received by the player.

## Build Information

> **Game Version:** 0.1.34.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
This is due to chat being a HUD widget which doesn't exist when you don't have a character. It would also be very hard to read the chat in that textured screen if it existed so I'm going to close this issue.
