### ISSUE TITLE
Allo juvenile right leg animation issue

### ISSUE THREAD

**Issue by Wannabgamers** [TheIsleGame/bugs#300]
## Expected Behavior

The legs should move equally.

## Current Behavior

The juvenile Allos right knee/leg jumps to the side https://i.imgur.com/gGz7gcR.gifv
## Steps to reproduce

1. Spawn as juvi Allo
2. Crouch
3. Look from above while crouching in a straight line.

## Build Information

> **Game Version:** 0.1.39.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
