### ISSUE TITLE
Juvenile Giga "sinks" in the ground when resting.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#301]
## Expected Behavior

Juvenile giga to play it's resting animation properly,without "sinking". 

## Current Behavior

Juvenile giga "sinks" in the ground when resting.
Happens to Hatchling stage as well.
Video Evidence:
https://youtu.be/8B1z_nqUd8E

## Steps to reproduce

-Be Juvenile/hatchling giga and play the rest animation.
-Notice that your body will "sink" in the ground.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2121395/TheIsle.log)

> **Game Version:** 0.1.39.9 ( development )

> **Operating System**: Windows 10.

> **Network Role**: Client.

**Comment by Hypno123** [comment]
Added to #501
