### ISSUE TITLE
Odd puddle forming when standing on the beach

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#302]
## Expected Behavior

A perfectly round puddle should probably not just appear under a dinosaur.

## Current Behavior

There is a perfectly circular puddle forming under the dinosaur when standing on the beach.

https://www.youtube.com/watch?v=shLPPfEGAvk

## Steps to reproduce

Log in as an adult trike and walk around on the beach.

## Build Information

> **Game Version:** 0.1.39.9 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in the next build.
