### ISSUE TITLE
low/medium shadows advantage

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#303]
## Expected Behavior

Players should not gain any advantage by having their shadows set to low/medium.

## Current Behavior

Shadows do not appear in the distance when they are set to low/medium whereas they do when set to high/epic. 

This allows players with lower graphics to have an advantage over those with higher settings during night.

Most noticeable in redwoods: https://www.youtube.com/watch?v=4e7x7djhFcc

## Steps to reproduce

1. Set shadows to low/medium at night, look into distance.
2. Set shadows to high/epic, look into distance again.
3. Low/medium clearly gives an advantage with no shadows appearing in the distance.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
I don't see anything but blackness both before and after.

**Comment by Hypno123** [comment]
Both Kitten and I experienced the bug found in the video I linked.

**Comment by ikarop** [comment]
Shadows should be consistent across all quality levels now.
