### ISSUE TITLE
Allo's thighs cave in during walk/trot/run

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#304]
## Expected Behavior

Allosaurus animations should play in a believable way.

## Current Behavior

During all forms of movement the Allo's hips cave inward, quite noticeably.

## Steps to reproduce

1. Spawn in as Allosaurus
2. Walk/Trot/Run as you like
3. Observe crumpled thighs/hips.  Note, it is easier to see from a high camera angle.

Video: https://youtu.be/TViAnHJUIRg

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
