### ISSUE TITLE
Hitting growth while stomping duplicates body

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#305]
## Expected Behavior

Hitting the growth button while stomping should not cause your body to duplicate.

## Current Behavior

Hitting the growth button while stomping will cause you to die upon changing to adult. After relogging you will still be alive, but your old corpse will remain.

This is the duplication bug that has been plaguing the servers for the past few weeks. 

These corpses are inedible at first but after letting them decay to gore piles, they can then be eaten.

https://www.youtube.com/watch?v=tvGsgzF_my0

## Steps to reproduce

1. Spawn as sub adult trike - skip growth.
2. Stomp with left click and press the growth button.
3. You will change to adult but spawn as a corpse.
4. Relog to come back to your corpse but still be alive.

The corpses are however inedible.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Should be fixed in 0.1.40.0, it's difficult for me to reproduce locally so it will need to be tested.

**Comment by Hypno123** [comment]
Fixed in 0.1.40.1
