### ISSUE TITLE
Allosaurus Adult camera phases through ground

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#306]
## Expected Behavior

The Allosaurus Adult camera to collide normally with the ground.

## Current Behavior

The Allosaurus Adult camera has no collision with the ground.

## Steps to reproduce

Spawn as Adult Allosaurus, look up, and notice that your camera phases through the ground.

https://i.imgur.com/5KJgNKy.jpg

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:**  0.1.40.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.8
