### ISSUE TITLE
Juvenile Allosaurus attentuation issue

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#308]
## Expected Behavior

The Juvenile Allosaurus bite and pain sounds to play at their proper distances and have fade-off.

## Current Behavior

The Juvenile Allosaurus bite and pain sounds can be heard from afar.

## Steps to reproduce

Have someone spawn in as Juvenile Allosaurus, have another spawn in as something that can damage said Juvenile Allosaurus, test distancing with these sounds.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
