### ISSUE TITLE
Allosaurus Adult not imported at old size

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#309]
## Expected Behavior

The Allosaurus Adult to be the same size as Allosaurus Old

## Current Behavior

The Allosaurus Adult is currently smaller than the Allosaurus Old.

## Steps to reproduce

Spawn in as Allosaurus Old, have someone spawn as Allosaurus Adult, notice that the sizes are different.

https://imgur.com/a/aKMpmbW

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Aliens218** [comment]
Not sure if this one is intentional or not. I wouldn't believe it to be.

**Comment by Hypno123** [comment]
Feel free to make this a suggestion in the official discord.
