### ISSUE TITLE
Sub adult triceratops camera does not collide with landscape

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#31]
## Expected Behavior

The camera for sub adult trike should collide with the landscape.

## Current Behavior

You can currently put the camera underneath the landscape/through walls etc.

## Steps to reproduce

1. Spawn as sub adult trike.
2. Place the camera under the ground - it does not collide.

## Build Information

> **Game Version:** 0.1.35.0 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Cannot reproduce in 0.1.35.3
