### ISSUE TITLE
Adult T-Rex leg clipping issue.

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#311]
## Expected Behavior

When the Adult Rex lays down, I did not expect to see clipping.

## Current Behavior

When the Adult Rex lays down, its upper legs clip into its lower legs. On the left and right side.

## Steps to reproduce
Choose Adult Rex and press H to lay down.
![20180624201815_1](https://user-images.githubusercontent.com/40440922/41825324-5cd1ca4a-77ec-11e8-9ac3-f1e1207aefba.jpg)
![20180624201820_1](https://user-images.githubusercontent.com/40440922/41825325-5e6bc2de-77ec-11e8-8c83-668981dd5d3c.jpg)
![20180624201844_1](https://user-images.githubusercontent.com/40440922/41825326-6033f992-77ec-11e8-8909-4ecd8e9164b7.jpg)

> **Game Version:** 0.1.40.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
