### ISSUE TITLE
Console command settings should not transfer to other servers

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#312]
## Expected Behavior

Console commands should not transfer to other servers.

## Current Behavior

Changing your settings on a listen server causes them to transfer to other servers.

For example typing "show Collision" in console will show you the capsules for each player, giving an advantage.

Listen server:
![image](https://user-images.githubusercontent.com/30550499/41835123-587b0648-784e-11e8-9896-c110350a3a7d.png)

Official server:
![image](https://user-images.githubusercontent.com/30550499/41835147-6ef915a4-784e-11e8-8fab-68c7b96a0e15.png)

## Steps to reproduce

1. Start a listen server.
2. Type "show Collision" (or CollisionPawn, Landscape, etc) in console.
3. Change to an official server and have the collision still visible.

## Build Information

> **Game Version:** 0.1.40.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
These are really intended to be dev-only, we just don't have a way of setting that just yet. Normal users shouldn't have access to these commands.

**Comment by looterz** [comment]
Fixed in 0.1.40.1
