### ISSUE TITLE
Juvenile trike does not have a distant threaten roar.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#314]
## Expected Behavior

Juvenile Trike's threaten call to be heard from a distance, like all its other calls

## Current Behavior

Nothing is heard from a distance when you threaten call.

## Steps to reproduce

Be a juvenile trike, record, threaten roar, go in your recording, hear the threaten call slowly fade away from its "close" version to absolutely nothing unlike the other calls, which fade into the "distant" versions.

## Build Information

> **Game Version:** 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
