### ISSUE TITLE
Doing a full body animation while getting up from resting doesn't work properly.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#315]
## Expected Behavior

While getting up from resting, full body animations should only affect certain body parts, like the way it does when you are crouching, resting, doing the standing to resting animation, ect.

## Current Behavior

However, unlike when the animation Stand to rest plays, when you are doing the rest to stand animation and you roar or do any full body animation, you will snap into doing it, completely ignoring the fact that you were getting up from resting. This does not make you able to move earlier or give any advantages. Once the full body animation ends, the rest to stand animation will continue playing, unless that full body animation was longer than the time it takes to stand up.

## Steps to reproduce

Be any dinosaur that has full body animations, use said full body animations while getting up from resting. Now in the duration of that animation, it will look like you're already standing up, while in reality you are still getting up from resting.

## Build Information.

> **Game Version:** 0.1.40.1 (Still an issue as of 0.1.51.9)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed.
