### ISSUE TITLE
Various ragdoll issues.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#316]
## Expected Behavior

 The ragdolls to act normal.

## Current Behavior

-Adult Giganotosaurus: https://cdn.discordapp.com/attachments/401465476661641217/453978204106129413/20180606194518_1.jpg (Does not happen for any of the other life stages) Seems to be standing on something invisible as it falls, too.

-Juvenile Giganotosaurus
https://cdn.discordapp.com/attachments/283178448329900033/461526705295589381/20180627154144_1.jpg

-Juvenile Utahraptor:
https://cdn.discordapp.com/attachments/401465476661641217/454957984846708747/20180609123957_1.jpg (Also happens for Hatchling Utahraptor)

-Juvenile Gallimimus
https://cdn.discordapp.com/attachments/283178448329900033/461486607443296266/20180627130220_1.jpg https://cdn.discordapp.com/attachments/283178448329900033/461486613592145930/20180627130224_1.jpg (Also happens for Hatchling Gallimimus)

(Sorry for the links, still figuring this whole github thing out)

## Steps to reproduce

Be any of the mentioned dinosaurs, record, die, look at the recording at the very moment you die and look at the deformations on the standard pose.

## Build Information.

> **Game Version:** 0.1.40.1  (All of them are still issues as of 0.1.51.9)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
With ragdolls falling to the floor almost immediately, I don't think this is even worth worrying about.

**Comment by Emanthealmighty** [comment]
Ragdolls actually fall really slowly.

I'd say that the giganotosaurus ragdolls need a fix the most as what's wrong with them is anything but unnoticeable.
