### ISSUE TITLE
Juvenile dinosaur animation problems

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#317]
## Expected Behavior

-Juvenile carnotaurus / Hatchling carnotaurus
Shouldn't sink when it rests, and its tail should be touching the ground, too.

-Juvenile allosaurus / Hatchling allosaurus
Shouldn't sink in general.

-Juvenile utahraptor / Hatchling utahraptor
Its resting animation should look like the adult utah. Its arms shouldn't be underground, its legs should be on the ground, the tail should touch the ground, too.

## Current Behavior

-Juvenile carnotaurus
It sinks into the ground when it rests, and its tail isn't even touching the ground. Same happens for the hatchling carno.

-Juvenile allosaurus
It is constantly sinking underground, it is expecially notable when it transitions from moving into standing, as its feet almost completely disappear into the ground. Same happens for the hatchling allo. https://cdn.discordapp.com/attachments/283178448329900033/461492000252887041/20180627131724_1.jpg - for a better view of the sinking problem.

-Juvenile utahraptor
It seems mostly fine, except for its resting animations. They need major fixing.
When it rests, its legs are in the air and its arms are undeground. The tail isn't touching the ground, either. (Same happens for the hatchling utahraptor)
https://cdn.discordapp.com/attachments/283178448329900033/461493305256050690/20180627132225_1.jpg
https://cdn.discordapp.com/attachments/283178448329900033/461493503935905792/20180627132219_1.jpg
The juvenile utahraptor also seems to have lost its old juvenile bite sound, now it sounds like a hatchling when it bites. I don't know if this is intended, but I'll put this here just in case.
The adult utahraptor also has a problem for its resting animation: the tail sinks underground.

## Steps to reproduce

Be any of the mentioned dinosaurs, do the mentioned things (rest, walk, or simply just stand) and see for yourself.

## Build Information.

> **Game Version:**: 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
#280 refers to floating arms and tail. I have removed this portion from your bug report.

**Comment by Hypno123** [comment]
Added to #501

**Comment by RagdollZombie** [comment]
Resting issues for mentioned juveniles still exist. You can spam the rest animation to see it easier.
