### ISSUE TITLE
Juvenile Dryo's arms go into its chest while drinking.

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#319]
## Expected Behavior

When drinking the arms should not be moving through the chest.

## Current Behavior

When drinking the Juvenile Dryo's arms go through its chest.

## Steps to reproduce
Choose a Dryo and go to any source of water to drink, observe.
![image](https://user-images.githubusercontent.com/40440922/41988415-08f37aa2-7a0a-11e8-8c84-f6a4c03c1b12.png)

> **Game Version:** 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed.
