### ISSUE TITLE
Adult trike is able to scent gore piles.

### ISSUE THREAD

**Issue by fubar345** [TheIsleGame/bugs#320]
## Expected Behavior
Adult trike should not be able to scent gorepiles

## Current Behavior
Adult trike can scent gore piles.

## Steps to reproduce
Pick adult trike and scent near a gore piles.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 1.40.1(dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by fubar345** [comment]
I tested this multiple times and was successfully able to scent the gorepiles each time. Will add to this if i experience it with other herbs.
![20180627180147_1](https://user-images.githubusercontent.com/13227782/42002547-bb6eaeba-7a35-11e8-855e-d2b21ce2e725.jpg)

**Comment by Hypno123** [comment]
All species can pick up corpses with scent regardless of their diet. Intended.

**Comment by fubar345** [comment]
Ah. Thought herbs weren't supposed to. My bad
