### ISSUE TITLE
Footprint scent disappears with night vision

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#322]
## Expected Behavior

Turning night vision on should not cause the scent from footprints to disappear.

## Current Behavior

Turning night vision on while scent is active causes the footprint scent to disappear. The scent returns when exiting night vision.

This does not effect gore piles.

https://www.youtube.com/watch?v=D8SB9eYwvk4

## Steps to reproduce

1. Run around, leaving footprints.
2. Use scent to see footprints.
3. Enable night vision with N and watch scent disappear until turned off again.

## Build Information

> **Game Version:** 0.1.40.1 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Not really a bug, that's the way I set it up. You have to pick one. 
Allowing both to be active starts making the footprint material a little too costly.
