### ISSUE TITLE
Juvenile Gallimimus' broadcast animation ends early.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#323]
## Expected Behavior

The animation to last till the roar has ended.

## Current Behavior

The animation ends while the sound of the roar is still playing. It's not a problem with the animation's play rate, the animation seems to just cut off.

## Steps to reproduce

Be a juvenile gallimimus and broadcast. Notice the difference between the adult's and the juvenile's animation, the juvenile animation clearly cuts off earlier.

## Build Information

> **Game Version:**: 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
I couldn't see anything seriously wrong with it, made some slight adjustments for the next build anyway. See if it's any better.

**Comment by Hypno123** [comment]
Fixed.
