### ISSUE TITLE
Negating the automatic roar when you chat.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#324]
## Expected Behavior

Messages to be unsendable while a montage is playing.

## Current Behavior

Players can currently negate doing the default call while chatting by biting (or sniffing, eating, drinking) and quickly pasting their message into chat to communicate without making as much noise as long as the montage is playing.

## Steps to reproduce

Be any dinosaur, copy a message, attack, sniff, drink or eat, and paste said message into the chat while the montage is still playing. You will now have communicated without doing the default roar.

## Build Information

> **Game Version:** 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Emanthealmighty** [comment]
Accidentally posted early. Going to modify this.

**Comment by Hypno123** [comment]
This has been covered in #404 in more detail.
