### ISSUE TITLE
Subadult giga / Adult giga rib eating consistency issues.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#327]
## Expected Behavior

Subadult giga to be able to eat large ribs.

## Current Behavior

A growing subadult giga can eat all the ribs except the small one.
A 1.0 subadult giga can only eat the titan ribs.
A 0.8 Adult giganotosaurus can eat large and titan.
A 1.0 Adult giganotosaurus can only eat titan ribs.

The issue here is that a subadult giga is completely incapable of eating any type of gore pile except the biggest one there is, as if it was an adult giganotosaurus. It's a small one, but still an issue.

## Steps to reproduce

Be a subadult giga with growth turned off, see how you can't eat large ribs. Now be an adult giga with growth activated, see how you can.

## Build Information

> **Game Version:** 0.1.40.1 (Still an issue as of 0.1.51.9)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Emanthealmighty** [comment]
A non fully grown subadult giga can eat all the ribs except the small one.
Subadult giga cannot eat any ribs other than the titan one. <--- The problem.

A non fully grown adult giga can eat all the ribs except the small one.
A fully grown adult giga can only eat the titan ribs, as it should be.

**Comment by Hypno123** [comment]
Fixed in 0.1.52.8
