### ISSUE TITLE
Eating sound plays even if player is no longer eating as Sub Rex.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#328]
## Expected Behavior

Eating sound to stop the moment player stops eating as Subadult Rex.

## Current Behavior

Eating sound keeps playing even if player is no longer eating or interacting with  gore piles/corpses.
Exclusive to Subadult Rex.
Doesn't happen when drinking.

Video Evidence:
https://youtu.be/hJJNeTj8Jhc

## Steps to reproduce

-Spawn as subadult Rex and eat.
-Stop eating before animation completes.
-Notice that eating sound will keep playing.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2150808/TheIsle.log)

> **Game Version:**  0.1.40.1 ( development )

> **Operating System**: Windows 10.

> **Network Role**: Client.

**Comment by dinosauriac** [comment]
Fixed next build.
