### ISSUE TITLE
Sub Rex eating sound isn't canceled when canceling the animation

### ISSUE THREAD

**Issue by Cocazou** [TheIsleGame/bugs#330]
## Expected Behavior

The eating sound should be canceled

## Current Behavior

The eating sound isn't canceling when canceling animation
https://www.youtube.com/watch?v=01YdSTp_PN0
## Steps to reproduce

1. Take a sub rex
2. Cancel the eating animation by releasing your eating hotkey

## Build Information

> **Game Version:** 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed next build. Make sure to check closed issues before opening new ones please! :)
