### ISSUE TITLE
Character Menu (via Insert or Esc Menu) inaccessible in "The Isle Official Testing" server.

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#333]
## Expected Behavior

Character Menu is accessible in the official dev test server by hitting esc and clicking on "Character", or by hitting insert.

## Current Behavior

On the Official test server on dev branch, you are unable to access The Character sheet, and thus unable to use coordinates to make reports.

## Steps to reproduce

Go on the dev branch server "The Isle Official Testing". Be any dinosaur. Attempt to access the character sheet. Note that it is disabled.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.1 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Server is on Sandbox so not technically a bug.
