### ISSUE TITLE
Replay system uses deprecated nightvision effect

### ISSUE THREAD

**Issue by dinosauriac** [TheIsleGame/bugs#335]
## Expected Behavior

Nightvision when using replay mode should mirror the effect used in-game. 

## Current Behavior

Right now it's a strange sort of false-colour effect when you press N in replay mode. It's kinda cool and does brighten up the scene a little, but it's not proper nightvision. Should either replace what's in use currently with the latest nightvision post process or keep this old effect around as an alternate viewing mode. 

## Steps to reproduce

Open a replay, press the nightvision key.

## Build Information

> **Game Version:** 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.51.5
