### ISSUE TITLE
The back of the left foot for adult allo twitches/wiggles constantly, even more so when broadcasting.

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#336]
## Expected Behavior

The Adult Allo's foot not to twitch.

## Current Behavior
When standing still, and even broadcasting the left foot of the adult allo twitches, and wiggles.
## Steps to reproduce
Spawn in as an adult allo and watch the back left foot twitch or wiggle. 

> **Game Version:** 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Video evidence please.

**Comment by Kingjaffad** [comment]
https://www.youtube.com/watch?v=q98O-biY6YE

Recorded the issue, the "twitch" on the left foot can be seen in the Allosaurus' idle.

**Comment by dinosauriac** [comment]
This is not a bug.

**Comment by PCSly** [comment]
@dinosauriac 
https://www.youtube.com/watch?v=eUU77JmThvc
