### ISSUE TITLE
When growing to the next life stage, your nest will disappear.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#337]
## Expected Behavior

The nest not to disappear.

## Current Behavior

As of now, when you're a sub giga,rex or trike and you make a nest, once you grow to adult the nest disappears.

## Steps to reproduce

Spawn as a full size subadult rex/giga/trike, make a nest, grow to adult, see the nest disappear before your eyes.

## Build Information

> **Game Version:** 0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
The nesting system will be reworked from scratch ans won't have this issue.
