### ISSUE TITLE
Players can change Gamma settings in Console.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#338]
## Expected Behavior

User should be unable to change Gamma settings in Console. 

## Current Behavior

Players can change Gamma settings via Console in Main Menu.
Players can then join any server with changed Gamma settings and gain unfair advantage during night time.

Note: trying to change Gamma settings in a server won't have any effect,must be done in main menu.

Screenshot Evidence:
![theisle-win64-test_2018-07-07_14-47-52](https://user-images.githubusercontent.com/35901313/42413371-999e4d9c-81f4-11e8-966d-4917002bbee2.jpg)

Screenshot was taken during "ddk" time with Gamma set at 6. (V3 Map)
NV was off

## Steps to reproduce

Open Console in Main Menu and Type Gamma < any number > 
-Example: Gamma 4.5 or Gamma 6
From now on game will be way brighter and NV won't be necessary at any point.

You  can reset your Gamma settings to default by typing Gamma 2.2 or Gamma 2.3
 
## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2172948/TheIsle.log)

> **Game Version:** 0.1.40.1 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by ExtraHu3** [comment]
Originally reported by user: quincy7890#8854 in Discord.

**Comment by Hypno123** [comment]
Fixed in 0.1.40.2 with removal of console.
