### ISSUE TITLE
Must relog to see birds on Thenyaw

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#339]
## Expected Behavior

The birds near the ocean to appear normally.

## Current Behavior

Unless you relog, you won't see the birds on Thenyaw when morning hits or whenever they're scripted to appear.

## Steps to reproduce

Wait an entire night on Thenyaw. (Or /time night then /time day). Relog. Notice that the birds appear.

https://i.imgur.com/fDvOcV5.jpg

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:**  0.1.40.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Hmm, well there's no scripting involved, this is more likely this is a LOD issue. If you start from further away than the birds render they might not reappear because they've been disabled at the lowest level of detail. What quality level you've set the Effects option to may affect this as well.

**Comment by Aliens218** [comment]
This has been remedied.
