### ISSUE TITLE
Thenyaw visible waterline not matched with interact-able waterline 

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#340]
## Expected Behavior

All Water sources should have a visible waterline that matches the interactable waterline (ex: ripples, splashes, etc)

## Current Behavior

Some water sources in Thenyaw have interactable waterlines vastly different from the visible waterline.

https://clips.twitch.tv/DeterminedSarcasticPigeonShadyLulu

## Steps to reproduce

Go to location in video, check above and below visible waterline to see where the ripples/splashes fall.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.1 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
So basically ripples/splashes made by players sometimes appear below the water?

**Comment by melmelMeliora** [comment]
Above and Below. It's like the whatever effects are put in at an angle.

**Comment by ikarop** [comment]
Fixed in 0.1.40.4.
