### ISSUE TITLE
Cannot see into dome, can see out of it.

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#342]
## Expected Behavior

The player should be able to either see into the dome or not see out of it. 

Not be able to see out from the inside and not see into it on the out.

## Current Behavior

Players can currently not see into the dome but can see out of it from the inside.

Outside:
![image](https://user-images.githubusercontent.com/30550499/42527964-0783e932-8472-11e8-90cd-ebd9f16ad210.png)

Inside:
![image](https://user-images.githubusercontent.com/30550499/42527973-101fdd80-8472-11e8-8e9a-dc3ae80f203a.png)

## Steps to reproduce

1. Go to the dome.
2. Look out of it from the inside.
3. Be unable to look into it from the outside.

## Build Information

> **Game Version:** 0.1.40.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in the latest version.
