### ISSUE TITLE
Camera forced into chest when entering dome

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#344]
## Expected Behavior

The dome should not be causing your camera to be forced into your chest.

## Current Behavior

The player's camera is forced into the chest of their creature when first entering the dome. Walking further to the center of the dome or leaving will allow the camera to go back to its normal position.

![image](https://user-images.githubusercontent.com/30550499/42528816-a508ec3c-8474-11e8-85e1-35a080947d00.png)

## Steps to reproduce

1. Enter the dome.
2. Watch camera zoom into the player's chest.

## Build Information

> **Game Version:** 0.1.40.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Well, you're not meant to be able to enter the dome...

**Comment by Hypno123** [comment]
No? Seems strange to put a lake inside, if player's aren't meant to access it.

**Comment by Hypno123** [comment]
Dome should not be accessible.
