### ISSUE TITLE
Ceratosaurus gets stuck in T-pose if game freezes while swimming

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#345]
## Expected Behavior

Ceratosaurus to play swimming animation even if game stutters/freezes while swimming.

## Current Behavior

Ceratosaurus gets stuck in "T-pose" if game freezes/stutters while swimming.
Happens to all Life cycles.
Doesn't happen to any other survival dinosaur as far as I've tested.

Video Evidence: https://youtu.be/EIErH3wazV8

## Steps to reproduce

-Be Ceratosaurus and swim.
-Wait for occasional freezes/stutters to happen when swimming.

Will certainly be harder to reproduce in stronger machines,but here are some conditions I've noticed that can cause stuttering:
-Day time.
-Heavy Weather (E.G: Storm).
-V3 or Thenyaw map. 
-and obviously,running background applications (E.G: Youtube videos)
## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2182284/TheIsle.log)

>Game Version: 0.1.40.3 ( development ) 

> **Operating System:** Windows 10

> **Network Role:** Client

**Comment by Hypno123** [comment]
Similar issue to #329 

Seems that this only occurs for Cerato's.

**Comment by Hypno123** [comment]
Added to #501
