### ISSUE TITLE
Juvie and Sub Trike not regenerating stamina

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#346]
## Expected Behavior

Juvie and sub trike should be regenerating stamina as the rex and giga do.

## Current Behavior

Juvie and sub trike currently have no stamina regeneration unless it is resting. This should only affect the adult.

## Steps to reproduce

1. Spawn as Juvie/sub Trike.
2. Run until stamina drains.
3. Stand to regain stamina, be unable to.
4. Begin resting and regain stamina as normal.

## Build Information

> **Game Version:** 0.1.40.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
This is intended. See SVN log from @looterz "Disabled stamina regeneration when not resting for Trike and slightly increased the stamina regeneration amount while resting."

**Comment by Hypno123** [comment]
The juvie and sub should regen stamina while standing. The adult should not.

**Comment by Hypno123** [comment]
Fixed in 0.1.40.4
