### ISSUE TITLE
Hatchling and juvenile corpses stretching

### ISSUE THREAD

**Issue by MoonTemeraire** [TheIsleGame/bugs#347]
## Expected Behavior

Body to die and fall down on the ground normally. Not stretching out

## Current Behavior

I can confirm that all herb hatchlings has this bug. Just sharing a few screenshots

Galli hatchling
https://steamcommunity.com/sharedfiles/filedetails/?id=1437896442
Para hatchling
https://steamcommunity.com/sharedfiles/filedetails/?id=1437897610
Several herbivore hatchlings
https://steamcommunity.com/sharedfiles/filedetails/?id=1437902577

Carnivore hatchlings seems to have the same issues

Allo hatchling
https://steamcommunity.com/sharedfiles/filedetails/?id=1437901117
Giga hatchling
https://steamcommunity.com/sharedfiles/filedetails/?id=1437902109

## Steps to reproduce

Join a server ( I played on the DV Test Level map/sandbox ) and joined in as a hatchling and then died as one

> **Game Version:** 0.1.40.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Examples of Maia and Dryo (hatch and juvie): 
![image](https://user-images.githubusercontent.com/30550499/42581809-81702c0c-8525-11e8-9cd6-0e7dbdb1cfdb.png)


Example of Allo hatch and juvie:
![image](https://user-images.githubusercontent.com/30550499/42581800-7c3f3d86-8525-11e8-8095-47834669cad7.png)

**Comment by MoonTemeraire** [comment]
I can still confirm that this issue is still here even after version 0.1.40.4 was released
https://steamcommunity.com/profiles/76561198844425554/screenshots/?appid=376210

**Comment by MoonTemeraire** [comment]
I can still confirm this being an issue even after version 0.1.40.4 released
https://steamcommunity.com/sharedfiles/filedetails/?id=1441961280
https://steamcommunity.com/sharedfiles/filedetails/?id=1441961156

**Comment by Hypno123** [comment]
I want to say this is fixed until someone reports otherwise. I personally haven't experienced this for a long time.
