### ISSUE TITLE
Bushes moving on different foliage settings

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#350]
## Expected Behavior

Bushes should not be changing positions on different foliage settings.

## Current Behavior

Occurs on both dedicated and listen servers.

Tested on Thenyaw and V3.

Foliage on cinematic shares the same positions as epic.

Bush on epic foliage setting:
![image](https://user-images.githubusercontent.com/30550499/42659362-ee3cd3a8-861f-11e8-93b2-d16dce0b929e.png)

Bush on high foliage setting:
![image](https://user-images.githubusercontent.com/30550499/42659476-508087d0-8620-11e8-988a-77e250372b73.png)

Bush on medium foliage setting:
![image](https://user-images.githubusercontent.com/30550499/42659444-34f8605a-8620-11e8-9de7-8a85113309d2.png)

Bush on low foliage setting:
![image](https://user-images.githubusercontent.com/30550499/42659466-443675de-8620-11e8-8712-e400ec73a0a5.png)

It does not affect the following bushes:

![image](https://user-images.githubusercontent.com/30550499/42660062-e1a4adb2-8621-11e8-9511-6417c5e8014a.png)

![image](https://user-images.githubusercontent.com/30550499/42660074-f0eab0f0-8621-11e8-82f5-68720caa6abb.png)

![image](https://user-images.githubusercontent.com/30550499/42660152-32b5dbc2-8622-11e8-819d-5b1a05bf60ec.png)

![image](https://user-images.githubusercontent.com/30550499/42660165-40c14350-8622-11e8-9011-115443f60f8b.png)
(and other sizes of edible bushes)

Trees are not affected.

## Steps to reproduce

1. Spawn as anything.
2. Hide in a bush.
3. Change foliage settings, check bush position.

## Build Information

> **Game Version:** 0.1.40.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Aha, as I suspected. Anything done using grass types is inconsistent. Only plants put down with the procedural spawner are the same for all players. Probably don't need that for the *actual grass* but anything larger than a shrub should be moved over to the procedural spawner, considering the smaller dinosaurs are losing out on hiding spots.

**Comment by dinosauriac** [comment]
Should test whether this is still happening after the most recent build went out.

**Comment by Hypno123** [comment]
Fixed.
