### ISSUE TITLE
Juvi vs Adult Gallimimus Vocal/Call Distance

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#355]
## Expected Behavior

Either Adult Galli's and Juvi Galli's can be heard from the same distance, or if anything, the adult is louder than the juvi.

## Current Behavior

There are long distance ranges where I cannot hear an adult galli calling, but I still hear the juvi galli very clear and loudly.

## Steps to reproduce

Be any creature. Have a friend be a juvi galli. Have another be an adult galli. Have them stand on top of each other, then slowly make distance and have them call out, and notice which calls last the longest distance. (Juvi's call)

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.4 (dev branch)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
I believe this is an issue for a few species. Closing this so that we can get a full report of all the examples of this once tested.
