### ISSUE TITLE
(minor) "Quit" button doesnt work if clicked directly after clicking "Back" and not moving cursor

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#356]
## Expected Behavior

going to the server list, clicking "back" and not moving the cursor shouldnt stop the quit button from working

## Current Behavior

you can click the quit button as much as you like, but it wont do anything unless you move your cursor off of it first

## Steps to reproduce

Click "play", then "back", and dont move the cursor, then the "quit" button wont work until you move the cursor off it and back on (does not happen all the time though)
https://www.youtube.com/watch?v=8Np3pjslT9o&feature=youtu.be

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
That's a safety feature so that you don't accidentally quit the game.
