### ISSUE TITLE
Certain dino corpses still blink (added video)

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#359]
## Expected Behavior

all corpses should not blink

## Current Behavior

certain dino corpses still blink, here is a list of those that do NOT blink as corpses:

juvis:
juvi gali, juvi trike, juvi para, juvi carno, and juvi utah

adults:
everything but allo adult

i have not tested subs

## Steps to reproduce

just suicide

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
I'm unable to replicate this issue so not sure what exactly is going on. Tested both species on and off of your lists and none of them seemed to blink.

**Comment by dinosauriac** [comment]
Need multiple people to confirm this. There's no reason why the adults would behave differently than the other life stages when it comes to blinking.

**Comment by foszor** [comment]
Test comment

**Comment by Hypno123** [comment]
Only seems to be apparent on dedicated servers.
