### ISSUE TITLE
Eating anim loop persists for other players

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#360]
## Expected Behavior

When not eating, players should not appear to be moving around while playing the eating animation

## Current Behavior

If a gore pile despawns while a player is eating but before the player can extract food, their eat anim will continuously play for surrounding players regardless of what they are actually doing. Note: If the gore despawns because the player finished eating it, this will not happen. May make more sense in reproduction steps.

## Steps to reproduce

1. With two players, locate a gore mesh.
2. With both players, begin eating the gore simultaneously.
3. The player that despawns the gore will behave as normal.
4. The second player, the one who did not "finish" the gore pile, will not receive food (obviously). On the first player's screen, the second player will now be stuck in an eating loop, sliding around the ground as they move.  The second player will appear unaffected on their own screen, however. 

The bug can also be canceled at any time by simply having the affected player bite.  The bite animation should play (for all players) and then onlookers will no longer see the eating loop played.

## Build Information

> **Game Version:** 0.1.40.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Refactored how this is handled, should be fixed as of 0.1.50.5
