### ISSUE TITLE
Adult Dryo keeps it's mouth open.

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#361]
## Expected Behavior

For the Adult Dryo to have it's mouth closed.

## Current Behavior

Adult Dryo has it's mouth open, does not close.

## Steps to reproduce
Choose Adult Dryo and you can see it's mouth is open.
![image](https://user-images.githubusercontent.com/40440922/42973160-23e39158-8b80-11e8-964d-9baa36bdd6db.png)

> **Game Version:** 0.1.40.4

> **Operating System**: Window

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed with new idle animation.
