### ISSUE TITLE
Diabloceratops idle to movement jitter

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#362]
## Expected Behavior

The idle to movement transition to be smooth.

## Current Behavior

Currently, whenever you move from idle the Diabloceratops jitters.

## Steps to reproduce

Spawn as Diabloceratops, spam any movement key and notice that you jitter. 

https://streamable.com/xu8l4

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Happens with every species, just more obvious for Diablo with how its idle animation plays.

More of an enhancement to make the transitions smoother.
