### ISSUE TITLE
AI gets stuck in water on V3

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#364]
## Expected Behavior

AI should either not enter water or not become stuck in it.

## Current Behavior

AI will currently flee into the water on V3 if you are a carnivore and will become stuck. They do not move if approached in the water.

## Steps to reproduce

1. Be a carnivore.
2. Find AI near a water source.
3. Chase the AI into the water and then leave them. They cannot leave the water.

## Build Information

> **Game Version:** 0.1.40.5 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
V3 still needs navigation obstacle volumes placed around water sources and other non-traversable areas to prevent issues like this

**Comment by Hypno123** [comment]
Fixed with new V3 map.
