### ISSUE TITLE
Juvi Utah Arms clip into body during sniff/scent animation

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#367]
## Expected Behavior

Arms of character never clip into themselves during any animation.

## Current Behavior

Juvi Utah's arms significantly clip into it's body during the stand-and-sniff animation

https://steamuserimages-a.akamaihd.net/ugc/924811883704132292/281E601952B8ECFDC8F7BF02237BACFD68DA2434/

## Steps to reproduce

Be a juvi utah. Hold Q while standing still. Observe arms, especially in the standing upright position.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.40.5 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Souretsu** [comment]
As a note, this happens with adult Utah, too, around the elbows.

**Comment by Hypno123** [comment]
Added to #501
