### ISSUE TITLE
Startup screen was replaced by the default UE4 one

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#369]
## Expected Behavior

The startup screen for the game should be the custom "The Isle" Apollo Engineering one.

## Current Behavior

The startup screen has currently been replaced by the default UE4 loading screen.

## Steps to reproduce

1. Start the game.
2. Watch the startup screen.

## Build Information

> **Game Version:** 0.1.40.7 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
It's a test asset being used while a new movie player system is being worked on. The original title video is actually still there and should play if the game doesn't load super quick.

**Comment by Hypno123** [comment]
Fixed in 0.1.50.1
