### ISSUE TITLE
Adult Allosaurus corpse decays faster than juvenile does.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#370]
## Expected Behavior

Adult allosaurus corpse to last longer or just as long as juvenile does.

## Current Behavior

Adult allosaurus  corpse decays faster than juvenile does.
By the time  A.allo corpse is gone,Juvie corpse is still at corpse stage.
Happens on both Dedicated Servers (tested on test server) and listen servers.

Video Evidence: 
https://youtu.be/qM9mTT6K3Sc - Edited
https://youtu.be/-_MmZpZz3gQ - Uncut

Note: not tested on non-fully grown adult allo.
## Steps to reproduce

-kill both Adult and juvenile allo.
-Watch their corpses as they decay.
-Notice that adult corpse decays faster than juvenile.
  
## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2224258/TheIsle.log)

> **Game Version:** 0.1.40.8 ( development )

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.8
