### ISSUE TITLE
Unusually High Ping for most players V3 Map

### ISSUE THREAD

**Issue by MoonTemeraire** [TheIsleGame/bugs#373]
## Expected Behavior

Players should be able to move around and fight smoothly 

## Current Behavior

Dinosaurs are sliding/teleportation/rubber banding around when moving and in combat with other dinosaurs

## Steps to reproduce

Join a server with V3 map and play

> **Game Version:** 0.1.50.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
This isn't worth reporting unless you are able to find the cause for the high ping. 

This is to be expected when a lot of players are on one server at the same time for the most part anyway.

**Comment by MoonTemeraire** [comment]
Wasn't sure it was worth reporting but I know a lot of people are struggling so gave it a try. Hard to know what's causing it now since it was not here before. Haven't had this issues in a long time, but now its really bad. Thanks for letting me know
