### ISSUE TITLE
AI spawns in water/underwater

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#374]
## Expected Behavior

AI dinosaurs should probably spawn in whatever logical terrain makes the most sense for that animal.

## Current Behavior

Currently the Orodromeus and Psittacosaurus AI are able to spawn in water.  Occasionally they will spawn swimming on the surface, but I have also noticed that they will spawn underwater as well, swimming some feet below the surface.

## Steps to reproduce

1) Spawn in an area near a large body of water, preferably the ocean.
2) Wait for AI to spawn near you
3) They will occasionally spawn in the water if given enough time.

## Build Information

> **Game Version:** 0.1.50.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed with new V3 map.
