### ISSUE TITLE
Broken seam between tiles on the coast of V3

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#375]
## Expected Behavior

Terrain should not at any point show broken seams.

## Current Behavior

At the new coastal area of V3, near the two redwoods entrances, a torn seam exists, seemingly stretching for quite a distance.

## Steps to reproduce

Observe the terrain in this area.  Videos linked below.

https://youtu.be/pKEYylXVZ2o
https://youtu.be/AG_2balBJWw

## Build Information

> **Game Version:** 0.1.50.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed with new V3 map.
