### ISSUE TITLE
Bugged terrain in "new" redwoods (walking on air, underground, etc)

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#376]
## Expected Behavior

Dinosaurs should be able to traverse terrain as they see it, without "floating" or falling through the floor.

## Current Behavior

Near the entrance to the newest redwoods forest (as of this version of the game) there is a bit of terrain where you can walk in the air or even through the ground.  Limited knowledge suggests it's a heightmap issue?

## Steps to reproduce

Walk around in the mentioned area.  Videos included.
https://youtu.be/rtZg-h258bE
https://youtu.be/9mP2ORE2VzY

## Build Information
> **Game Version:** 0.1.50.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
The area in question relative to the V3 skeleton.

![area](https://user-images.githubusercontent.com/30550499/43532229-83bc69be-95a9-11e8-925e-f85657c37c9d.jpg)

**Comment by Hypno123** [comment]
Fixed in 0.1.50.7
