### ISSUE TITLE
Herbivore food spawns under water

### ISSUE THREAD

**Issue by MoonTemeraire** [TheIsleGame/bugs#377]
## Expected Behavior

Herbivore food should spawn on land where you can eat from it

## Current Behavior

Plants are randomly spawning under water. You can't reach to eat from them

## Steps to reproduce

Join V3 map and see if you can find any

I found this one in this area of the map. I've found more around that area before. 
So far I haven't found any plants in other areas of the map where they are in the water

https://steamcommunity.com/sharedfiles/filedetails/?id=1463099804
https://steamcommunity.com/sharedfiles/filedetails/?id=1463099727

## Build Information

> **Game Version:** 0.1.50.6 ( dev )

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
These water sources probably still need to have mud painted under them to prevent this from happening.

**Comment by Hypno123** [comment]
Fixed with new V3 map.
