### ISSUE TITLE
Shadows projected onto dinosaurs unnaturally

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#378]
## Expected Behavior

When set to high or above, shadows should not look as dark as they do when standing underneath a tree.

## Current Behavior

When set to high or above, shadows are currently projected onto the creatures and look almost pitch black.

https://im5.ezgif.com/tmp/ezgif-5-4bb0679e6e.gif

## Steps to reproduce

1. Spawn as anything.
2. Stand underneath the leaves of a tree.

## Build Information

> **Game Version:** 0.1.50.6 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in 0.1.50.7.
