### ISSUE TITLE
Leaves on log mesh has no texture

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#379]
## Expected Behavior

The leaves on the logs should have a texture.

## Current Behavior

There's currently no texture for the leaves on log mesh.

![image](https://user-images.githubusercontent.com/30550499/43689592-de211d3e-98f4-11e8-8c12-41e4f95fe0ce.png)

## Steps to reproduce

1. Find the log at 10 latitude, -70 longitude.
2. Look at the leaves on the log, the texture is missing.

## Build Information

> **Game Version:** 0.1.50.6 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in 0.1.50.7.
