### ISSUE TITLE
Galli juvenile pauses idle animation for F and 2 call

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#380]
## Expected Behavior

The idle animation should not be pausing when performing the F/2 call.

## Current Behavior

The idle animation currently pauses, forcing both legs back to their default position for a second when performing the F/2 call.

![image](https://user-images.githubusercontent.com/30550499/43691407-ed05c452-9913-11e8-809c-53746526b779.png)

## Steps to reproduce

1. Spawn as Galli juvie.
2. Press F or 2 on your keyboard.
3. Watch legs move back to default position.

## Build Information

> **Game Version:** 0.1.50.7 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Juvenile gallimimus uses fullbody animations for all vocals as of version 0.1.5.8. 
Might still need some blend tweaks, but marking this one as fixed.
