### ISSUE TITLE
Rock with missing material on Thenyaw

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#382]
## Expected Behavior

The rock should not be missing its material.

## Current Behavior

The rock at 2 latitude, 116 longitude is currently missing its material, giving it a very blurry green look.

![image](https://user-images.githubusercontent.com/30550499/43746378-ddfb973e-99db-11e8-8ee6-53479ad045b7.png)

![2nlvgr](https://user-images.githubusercontent.com/30550499/43746451-4818e2ac-99dc-11e8-9c49-d1c991e85b43.jpg)

## Steps to reproduce

1. Spawn on Thenyaw.
2. Find the rock and look at it.

## Build Information

> **Game Version:** 0.1.50.7 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in 0.1.50.8.
