### ISSUE TITLE
When other players finish gore piles they get stuck in eating animation

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#39]
## Expected Behavior

When other players finish gore piles, they should immediately stop playing the eating animation.

## Current Behavior

When a gore pile is finished by another player, they will continue to play the eating animation for you, but on their screen they will be playing normal animations.

https://www.youtube.com/watch?v=5joX_tXGFuY

## Steps to reproduce

1. Spawn as a carnivore.
2. Kill something and eat it down to a gore pile.
3. Have another carnivore eat the gore pile.
4. Watch them continue their eating animation even after the gore pile is gone.

## Build Information

> **Game Version:** 0.1.35.0 (dev)

> **Operating System**: Windows

> **Network Role**: Client, dedicated.

**Comment by looterz** [comment]
Fixed in 0.1.35.3

**Comment by Hypno123** [comment]
Still apparent in 0.1.35.4 (at least for carnos)

**Comment by looterz** [comment]
Should be fixed now in 0.1.36.1
