### ISSUE TITLE
Water in Thenyaw is jagged in Swamp

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#391]
## Expected Behavior

The Water to be smooth when you go up to drink.

## Current Behavior

The water has some jagged edges.

## Steps to reproduce

Go to Swamp and walk up to the water's edge, I will post screenshots for the coords.
![20180811111454_1](https://user-images.githubusercontent.com/40440922/43993581-95a8d4ee-9d5d-11e8-9010-7c2bcbda3350.jpg)
![20180811111445_1](https://user-images.githubusercontent.com/40440922/43993584-99f649be-9d5d-11e8-95ad-1095f8b7116d.jpg)

> **Game Version**: 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
That's more of a problem with the landscape being jagged than the water itself.
