### ISSUE TITLE
Misplaced Redwoods Ambience

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#392]
## Expected Behavior

Default forest audio to initiate and loop in a non-redwood biome environment.

## Current Behavior

A small section of the V3 map currently has the redwood biome ambience overlaying the area. This area includes a small pocket in the Southwest directly North of the newest redwood biome region. Coordinates provided in videos.

## Steps to reproduce

Venture to the stretch of hills directly between large swamp and small swamp while sticking close to the mountainside bordering the Northern region of the new redwood biome. 
Ambience Part 1: https://streamable.com/mjm1s
Ambience Part 2: https://streamable.com/9v0xv
Ambience Part 3: https://streamable.com/jfmfy

**General Area Coordinates:** 
Latitude 279, 33, 938
Longitude 117, 289, 414
Altitude -43, 183, 625

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed with new V3 map.
