### ISSUE TITLE
Instant Kick Attack from Resting - Parasaurolophus Adult and Juvenile

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#394]
## Expected Behavior

Playing the full animation while rising from the resting position does not allow for any offensive action to prematurely occur.

## Current Behavior

The parasaurolophus adult and juvenile currently have the ability to immediately cancel the rest position upon rising in order to immediately utilize their high damage special attack (kick). This is directly contrary to the triceratops requiring the full rising from rest animation to finish before its special (stomp) is able to be performed.

## Steps to reproduce

Enter the rest position for either parasaurolophus adult or juvenile. 
Press H again to begin rising and immediately initiate the kick attack to cancel out the rising animation.

Adult Parasaurolophus instant kick: https://streamable.com/b5rem
Juvenile Parasaurolophus instant kick: https://streamable.com/5ajtq

For comparison, Triceratops special showing the delay in attack due to correctly playing the full rising animation:
Triceratops Adult: https://streamable.com/qqzgf
Triceratops Sub-Adult: https://streamable.com/0bfwa 

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Reported in #16
