### ISSUE TITLE
V3 Potholes Masterlist

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#396]
## Expected Behavior

There should be no potholes that players can fall into and not be able to escape from.

## Current Behavior

There are currently a number of potholes on V3 that the players can fall into and cannot escape from. 

**This will be an ongoing list - please comment any potholes that you may find on V3 in the comments.**

## Steps to reproduce

1. Spawn.
2. Go to one of the potholes found in the comments.
3. Fall in and not be able to escape.

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Skysealer** [comment]
Latitude: 585, 155. 438
Longitude: 509, 549. 219
![20180728211818_1](https://user-images.githubusercontent.com/42288648/44563346-d55eeb00-a72b-11e8-9b1c-d32d5efa3153.jpg)
Originally reported by user Laacer (28JUL2018)

**Comment by Skysealer** [comment]
Latitude: 316, 093. 281
Longitude: 298, 352. 312
[Image provided was too dark to utilize as reference]
Originally reported by user HDgamerDino (31JUL2018)

**Comment by Skysealer** [comment]
Latitude: 570, 721. 438
Longitude: 495, 103. 719
![20180807012657_1](https://user-images.githubusercontent.com/42288648/44563560-b01eac80-a72c-11e8-892d-7184bfe52a10.jpg)
Originally reported by user EmilyArt (07AUG2018)

**Comment by Skysealer** [comment]
Latitude: 531, 915.125
Longitude: 576, 957. 188
![20180808015033_1](https://user-images.githubusercontent.com/42288648/44563623-f3791b00-a72c-11e8-9507-969039dfd531.jpg)
**Note:** Larger animals will be able to navigate out; however, smaller juveniles will be stuck.
Originally reported by myself (08AUG2018)

**Comment by Skysealer** [comment]
Latitude: 571, 427. 812
Longitude: 496, 739. 844
![20180812232411_1](https://user-images.githubusercontent.com/42288648/44563739-874ae700-a72d-11e8-9cfe-d68f285747f2.jpg)
Originally reported by user Evil Minion (12AUG2018)

**Comment by Skysealer** [comment]
Latitude: 571, 558. 562
Longitude: 496, 198. 938
![unknown](https://user-images.githubusercontent.com/42288648/44563783-c7aa6500-a72d-11e8-9c9a-dc414555ebf3.png)
**Note:** This area in particular seems to have a cluster of small holes capable of capturing users (see previous comment for similar coordinate).
Originally reported by user Ultimate Fluff (12AUG2018)

**Comment by Skysealer** [comment]
Latitude: 591, 716. 375
Longitude: 532, 913. 75
[User was unable to provide a screenshot of the landscape due to drowning]
Originally reported by user Nachta (13AUG2018)

**Comment by Skysealer** [comment]
Latitude: 508, 304. 5
Longitude: 486, 606. 562
[User did not provide a screenshot of the landscape for reference]
Originally reported by user Evil Minion (16AUG2018)

**Comment by Skysealer** [comment]
Latitude: 585, 871. 188
Longitude: 519, 606. 406
![20180823193232_1](https://user-images.githubusercontent.com/42288648/44563997-de04f080-a72e-11e8-80e5-7e03fb7b7cc8.jpg)
Originally reported by user Aliens218 via DM (23AUG2018)

**Comment by Skysealer** [comment]
Latitude: 584, 282. 938
Longitude: 517, 005. 438
![20180823193414_1](https://user-images.githubusercontent.com/42288648/44564029-01c83680-a72f-11e8-97ac-5e63b746ae9c.jpg)
Originally reported by user Aliens218 via DM (23AUG2018)

**Comment by Skysealer** [comment]
Latitude: 524, 191. 438
Longitude: 485, 996. 312
![20180823170338_1](https://user-images.githubusercontent.com/42288648/44564410-c595d580-a730-11e8-88d3-6d30301de4d3.jpg)
Originally reported by user Aliens218 via DM (23AUG2018)

**Comment by Hypno123** [comment]
I'll grab screenshots for those that are missing them and get clearer ones that are hard to see.

**Comment by Skysealer** [comment]
**Latitude:** 604, 392. 438
**Longitude:** 500, 188. 062

![20180826201317_1](https://user-images.githubusercontent.com/42288648/44634830-99ff2f00-a96c-11e8-9b93-0b7333df52b5.jpg)

Originally reported by user Skysealer (26AUG2018)

**Comment by Skysealer** [comment]
**Latitude:** 599, 562. 688
**Longitude:** 433, 145. 719

![](https://cdn.discordapp.com/attachments/463493168407773205/483794560787415040/20180827202147_1.jpg)

Originally reported by user CJ_EB (27AUG2018)

**Comment by Skysealer** [comment]
**Latitude:** 566, 710. 062
**Longitude:** 505, 206. 719

![image](https://user-images.githubusercontent.com/42288648/44764248-c0fc6300-ab1c-11e8-94b0-c43612328fe6.png)

Originally discovered by users Aliens218 and Skysealer (28AUG2018)

**Comment by Skysealer** [comment]
**Latitude:** 534, 901. 875
**Longitude:** 462, 401. 25

_Note -- Cerato was stuck and died in the hole. Area to my right is a second hole you can get stuck in._
![20180828235721_1](https://user-images.githubusercontent.com/42288648/44764707-0ae64880-ab1f-11e8-8a40-d749d5fc1a90.jpg)

Originally discovered by users Alien218 and Skysealer (28AUG2018)

**Comment by Skysealer** [comment]
**Latitude:** 602, 428. 562
**Longitude:** 515, 825. 156

![image](https://user-images.githubusercontent.com/42288648/44764845-a7104f80-ab1f-11e8-90cb-599acdd3eddf.png)

Originally discovered by user Kiiks (28AUG2018)

**Comment by Skysealer** [comment]
**Latitude:** 570, 717. --
**Longitude:** 495, 097. 594

![image](https://user-images.githubusercontent.com/42288648/44892243-a4ddfa80-acb1-11e8-8b90-0edbad2a690f.png)

Originally discovered by Aliens218 (30AUG2018)

**Comment by Hypno123** [comment]
**Latitude:** 612
**Longitude:** 501

![image](https://user-images.githubusercontent.com/30550499/45329133-d929a480-b556-11e8-9a63-4e1690492b4f.png)

**Comment by Hypno123** [comment]
**Latitude:** 588
**Longitude:** 408

![image](https://user-images.githubusercontent.com/30550499/45454632-84179b00-b6dc-11e8-9fba-980f01012106.png)

**Comment by Skysealer** [comment]
**Latitude:** 587, 918. 312
**Longitude:** 530, 399. 562

![image](https://user-images.githubusercontent.com/42288648/45665630-be6ba880-badf-11e8-991d-1065ac15c17e.png)

Originally discovered by user Aliens218 (17SEP2018)

**Comment by Hypno123** [comment]
Fixed with new V3 map.
