### ISSUE TITLE
Main menu blinking lights shift to the left on server list menu

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#397]
## Expected Behavior

The lights should not be shifting to the left on the server listing screen.

## Current Behavior

The blinking lights found on the main menu will shift to the left when on the server listing screen.

![image](https://user-images.githubusercontent.com/30550499/44596877-af862480-a7c5-11e8-896b-ea2b00d990d4.png)

## Steps to reproduce

1. Start the game up.
2. Check the lights in the bottom right, they are in the correct position.
3. Click Play to go to the server listing screen.
4. Check the lights again and see they have shifted to the left slightly.

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
should be fixed as of revision no. 2002

**Comment by Hypno123** [comment]
This is still an issue in 0.1.51.3

**Comment by Hypno123** [comment]
See #453 for an updated report.
