### ISSUE TITLE
Hatchling Rex Deals Bone Break

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#399]
## Expected Behavior

A hatchling tyrannosaurus is unable to deal bone break.

## Current Behavior

Hatchling tyrannosaurus is able to deal bone break.

## Steps to reproduce

1. Have two users (User A and User B) -- User A becomes a hatchling tyrannosaurus while User B selects a dinosaur of their choice.
2. User A continually bites User B until bone break is dealt.

**Test Level // Sandbox // Differing weight classes:**
Hatchling Tyrannosaurus vs Adult Triceratops: https://streamable.com/7kigs
Hatchling Tyrannosaurus vs Adult Allosaurus: https://streamable.com/y7b3q
Hatchling Tyrannosaurus vs Adult Utahraptor: https://streamable.com/0zahr

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Souretsu** [comment]
Can this be closed? I don't recall this happening for quite some time.

**Comment by Hypno123** [comment]
No changes have been made to prevent it happening as far as I know - we can check this later.

**Comment by dinosauriac** [comment]
Fixed next build.
