### ISSUE TITLE
Giga statistics inconsistencies

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#40]
## Expected Behavior

The juvenile should always be weaker than the sub adult, and the sub adult should always be weaker than the adult.

## Current Behavior

When progressing to the next stage, you will have slightly reduced stats than previously, even though you appear larger.

Juvenile at .7:

![image](https://user-images.githubusercontent.com/30550499/38165068-c60d209c-3505-11e8-9602-c33be9b84f5d.png)

Sub adult at .6:

![image](https://user-images.githubusercontent.com/30550499/38165052-b27418d8-3505-11e8-9d7a-280c53fe2fdd.png)

## Steps to reproduce

1. Spawn as Giga.
2. Get to full grown juvenile - check stats with debug menu.
3. Grow to sub adult - check stats with debug menu.
4. Notice you grew bigger but lost health.

## Build Information

> **Game Version:** 0.1.35.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.35.3

**Comment by Hypno123** [comment]
Updated report for 0.1.35.8

**Comment by looterz** [comment]
Fixed in 0.1.35.9.
