### ISSUE TITLE
Pockets of Mountain Pass Lacking Collision (V3)

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#400]
## Expected Behavior

Users should not be able to clip through mountain walls and hide in them.

## Current Behavior

In certain areas of this specific mountain pass linking the red woods to the flood plains there are pockets of areas on either side where users are able to clip into and potentially hide/ambush from.

## Steps to reproduce
1. Log into a V3 server.
2. Travel to the following coordinates:
**Latitude:** 579, 715. 125
**Longitude:** 201, 199. 375
3. Hug the wall on both left and right sides of the pass to find pockets of rock wall lacking collision. 

**Wall Clipping Example (Dev 2):** https://streamable.com/hrmdp

**Overall Pass Entrance (South) Visual Reference:**

![20180904225821_1](https://user-images.githubusercontent.com/42288648/45069006-60c76d00-b098-11e8-9055-c1e96bd777f6.jpg)

**Coordinates for the Western wall:**

1. **Latitude:** 561, 833. 938 // **Longitude:** 194, 851. 922
2. **Latitude:** 556, 050. 188 // **Longitude:** 194, 480. 828
3. **Latitude:** 545, 783. 5 // **Longitude:** 193, 149. 062
4. **Latitude:** 539, 664. 5 // **Longitude:** 194, 143. 438
5. **Latitude:** 534, 347. 125 // **Longitude:** 192, 242. 875
6. **Latitude:** 521, 864. 125 // **Longitude:** 192, 027. 844
7. **Latitude:** 510, 155. 5 // **Longitude:** 194, 244. 391
8. **Latitude:** 494, 789. 844 // **Longitude:** 200, 411. 125
9. **Latitude:** 488, 513. 531 // **Longitude:** 196, 083. 953

**Coordinates for the Eastern wall:**

1. **Latitude:**  578, 554. 25 // **Longitude:** 206, 548. 734
2. **Latitude:**  571, 042. 625 // **Longitude:** 203, 507. 516
3. **Latitude:** 565, 970. 75 // **Longitude:** 202, 489. 562
4. **Latitude:** 563, 739. 125 // **Longitude:** 203, 518. 672
5. **Latitude:** 554, 593. 188 // **Longitude:** 198, 955. 422
6. **Latitude:**  547, 319. 062 // **Longitude:** 199, 974. 328
7. **Latitude:** 532, 173. 875 // **Longitude:** 196, 098. 344
8. **Latitude:** 525, 036. -- // **Longitude:** 194, 984.328
9. **Latitude:** 523, 572. 906 // **Longitude:** 196, 515. 375
10. **Latitude:**  520, 929. 438 // **Longitude:** 199, 758. 719
11. **Latitude:**  510, 018. 438 // **Longitude:** 200, 802. 406
12. **Latitude:**  505, 563. 594 // **Longitude:** 205, 697. 359

((Major special thanks to Aliens218 for helping me out with this))
## Build Information
> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Skysealer** [comment]
Additionally, another wall lacking collision has been discovered:

**Latitude:** 633, 289. 5
**Longitude:** 134, 014. 141

![image](https://user-images.githubusercontent.com/42288648/45914657-03f8e000-be16-11e8-940a-dcf45c977cf1.png)

Reported by Souretsu.

**Comment by Skysealer** [comment]
**Latitude:** 545, 718
**Longitude:** 419, 201

**Comment by Hypno123** [comment]
Fixed with new V3 map.
