### ISSUE TITLE
Setting Max Results value on server listing to a negative value causes game to crash

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#402]
## Expected Behavior

There should be sanity checks for the 'Max Results' on the server listing to prevent players from putting any invalid values that would cause your game to crash.

## Current Behavior

The 'Max Results' value does not have a sanity check for negative values. Entering -10000 etc will cause the player's game to crash.

![image](https://user-images.githubusercontent.com/30550499/45909733-99d34180-bdfb-11e8-9f39-97036a6562f4.png)

## Steps to reproduce

1. Start the game.
2. Go to server listing menu.
3. Enter a large negative value in the 'Max Results' field. -10000 for example.

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.60.0
