### ISSUE TITLE
Triceratops Resting Toe Distortion

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#403]
## Expected Behavior

For the feet of the Triceratops to be alligned and toes properly positioned on the ground in the resting animation.

## Current Behavior

The feet of the Triceratops lift in the air and the toes splay wildly when in the resting animation, making it look very odd.

## Steps to reproduce

1. Spawn as Adult Triceratops 
2. Hit rest key
3. Notice that toes splay in the resting animation.

![20180927020429_1](https://user-images.githubusercontent.com/26824146/46180001-f1eec580-c28b-11e8-9d06-c437d070c741.jpg)

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
