### ISSUE TITLE
Dinosaur Audio Montages Canceled by Eating/Drinking Animation

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#404]
## Expected Behavior

When performing any dinosaur audio montage, such as a broadcast or threaten, the animation is not to be canceled by any means other than the end of the animation montage.

## Current Behavior

When performing a dinosaur's audio montage you can cancel out the montage animation by activating an interactive object (such as drinking water, or eating from a ragdoll, eating from a gore carcass, or eating from a bush). This enables the dinosaur to either continue the eating/drinking animation and/or perform any native attack (RMB and LMB if applicable) while the audio is still playing.

## Steps to reproduce

1. Load into any server and select a dinosaur of choice.
2. Find any applicable source of food or body of water.
3. Perform any audio montage (ex: broadcast)
4. Immediately select E to interact with food or water -- Either continue to hold E for the full eating/drinking animation during the audio montage or let go and click LMB/RMB to attack while the audio montage plays.

**_SPECIAL NOTE:_** _Parasaurolophus and Carnotaurus are **NOT** able to attack, but can still cancel the audio montage to eat and drink._

**Full-Range Montage Cancellation (feat. Adult Triceratops):**
https://streamable.com/0ll6x

**Drinking Reference (feat. Adult Allosaurus):**
https://streamable.com/xjc63

**Individual Herbivore References:**
- Diabloceratops (Adult): https://streamable.com/jqnd3
- Diabloceratops (Juvenile): https://streamable.com/6dpl2
- Dryosaurus (Adult): https://streamable.com/h1s7v
- Dryosaurus (Juvenile): https://streamable.com/z99kd
- Gallimimus (Adult): https://streamable.com/dctli
- Gallimimus (Juvenile): https://streamable.com/zw06m
- Maiasaurus (Adult): https://streamable.com/vsnaq
- Maiasaurus (Juvenile): https://streamable.com/j5aki
- Parasaurolophus (Adult - Eating only): https://streamable.com/d2a2k
- Parasaurolophus (Juvenile - Eating only): https://streamable.com/ddum1
- Triceratops (Adult): https://streamable.com/fvlig
- Triceratops (Sub-adult): https://streamable.com/x4n80
- Triceratops (Juvenile): https://streamable.com/00efh

**Individual Carnivore References:**
- Allosaurus (Adult): https://streamable.com/njihl
- Allosaurus (Juvenile): https://streamable.com/73ng7
- Carnotaurus (Adult - Eating only): https://streamable.com/ng49l
- Carnotaurus (Juvenile - Eating only): https://streamable.com/p5na9
- Ceratosaurus (Adult): https://streamable.com/tqf6q
- Ceratosaurus (Juvenile): https://streamable.com/6inkr
- Dilophosaurus (Adult): https://streamable.com/emos4
- Dilophosaurus (Juvenile): https://streamable.com/q2eeg
- Giganotosaurus (Adult): https://streamable.com/g2yvp
- Giganotosaurus (Sub-adult): https://streamable.com/7by7p
- Giganotosaurus (Juvenile): https://streamable.com/j7y9f
- Tyrannosaurus (Adult): https://streamable.com/y0782
- Tyrannosaurus (Sub-adult): https://streamable.com/9deqv
- Tyrannosaurus (Juvenile): https://streamable.com/wuvmz
- Utahraptor (Adult): https://streamable.com/fb6sn

**Not Tested** -- Hatchlings and juvenile utahraptor due to shortened audio.

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.51.3
