### ISSUE TITLE
Laying down mid stomp allows you to play the stand animation while moving

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#405]
## Expected Behavior

Laying down mid stomp / kick animation should not allow your character to move when getting back up again.

## Current Behavior

Laying down while stomping (Trike) / kicking (Para or Galli) should not allow your character to move while getting back up again.

https://www.youtube.com/watch?v=jHOzIznDGWg

## Steps to reproduce

1. Spawn as Trike, Para or Galli.
2. Left click to stomp/kick.
3. Press H during the stomp/kick.
4. Wait until the attack animation is over.
5. As your character begins to rest, press H again to begin standing.
6. Move as your character begins to stand.

## Build Information

> **Game Version:** 0.1.59.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.51.5
