### ISSUE TITLE
Rest Jittering with Roar Montage Animations

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#406]
## Expected Behavior

For dinosaurs to enter and exit the resting state normally despite spamming the H key during the audio montage.

## Current Behavior

As you spam your H key and perform any roar, certain dinosaurs may jitter (most noticeably present in those with full-body animations)

## Steps to reproduce

1. Spawn as any survival dinosaur _(Save for Parasaurolophus, Maiasaura, and Dilophosaurus)_
2. Enter a roar montage _(Preferably broadcast as it's the longest and in certain cases, most noticeable)_
3. Spam your H key.
4. Notice that if said conditions are met, your dinosaur jitters as you spam your H key.

https://streamable.com/ivkmy **Allosaurus and Carnotaurus**
https://streamable.com/l1hs4 **Dilophosaurus and Ceratosaurus**
https://streamable.com/qcn8n **Giganotosaurus and Tyrannosaurus**
https://streamable.com/b45hf **Utahraptor and Diabloceratops**
https://streamable.com/h7d1w **Gallimimus and Dryosaurus**
https://streamable.com/03a6h **Parasaurolophus and Maiasaura**
https://streamable.com/xrmeu **Triceratops**

**NOTE**: _Some of the videos end or start too suddenly, but you can definitely see the jittering._

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
