### ISSUE TITLE
Orange glow surrounding the Triceratops

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#408]
## Expected Behavior

There should not be an orange glow surrounding the Triceratops.

## Current Behavior

An orange glow can be seen around all life stages of the Triceratops.

**Adult:**
![image](https://user-images.githubusercontent.com/30550499/46562532-5b0db300-c8f4-11e8-959e-5a0143ee10e6.png)

**Sub:**
![image](https://user-images.githubusercontent.com/30550499/46562541-682aa200-c8f4-11e8-9848-b73c79734626.png)

**Juvie:**
![image](https://user-images.githubusercontent.com/30550499/46562545-71b40a00-c8f4-11e8-923d-0e5cc1010450.png)

**Hatchling:**
![image](https://user-images.githubusercontent.com/30550499/46562555-7bd60880-c8f4-11e8-988b-0360a5a92d94.png)

Harder to see at night but still apparent.

## Steps to reproduce

1. Spawn as any life stage of the Triceratops.
2. Look at the orange glow surrounding it.

## Build Information

> **Game Version:** 0.1.51.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in the next build.
