### ISSUE TITLE
Orodromeus have black eyes

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#409]
## Expected Behavior

The Orodromeus should have the correct eye texture applied.

## Current Behavior

The Orodromeus currently has black eyes.

![image](https://user-images.githubusercontent.com/30550499/46564482-8a75ed00-c8ff-11e8-8906-6800ac116dbe.png)

## Steps to reproduce

1. Spawn as Oro or find an AI.
2. Stare into its black, demon eyes.

## Build Information

> **Game Version:** 0.1.51.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in the next build.
