### ISSUE TITLE
Switching from trotting to walking right before stopping mitigates momentum

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#413]
## Expected Behavior

trotting, then switching to walking right before stopping shouldnt affect momentum

## Current Behavior

if you trot as a dino that has momentum (allo for example, thats what i used), then switch to walking before you stop, you will experience much less momentum than you would have otherwise. Even if you only switch to walking like, half a second before you stop, it will still decrease momentum.

## Steps to reproduce

- Be a dino with momentum, like carno or allo
- trot, then right before you stop, switch to walking, and you will stop almost immediately, rather than keep going forward for a bit due to momentum

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
This is an enhancement.
