### ISSUE TITLE
Juvenile Tyrannosaurus Drinking Animation Jitter

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#414]
## Expected Behavior

While drinking, the juvenile tyrannosaurus should play a smooth drinking animation without any jitters.

## Current Behavior

While drinking, the juvenile tyrannosaurus exhibits a slight 'bouncing' jitter during the drinking animation.

## Steps to reproduce

1. Spawn as a juvenile tyrannosaurus on any server.
2. Find a potable water source and prompt the drinking animation.
-- Notice the bouncing jitter as the dinosaur performs the drinking animation.

**Visual Reference // Dev 4:** https://streamable.com/ptpk6 

## Build Information

> **Game Version:** 0.1.50.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
