### ISSUE TITLE
Dilo juv/adult able to move while standing up

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#415]
## Expected Behavior

Dinosaur should be unable to move while standing up from a resting position, until the animation completes.

## Current Behavior

Using movement keys during the animation will let Dilo slide around while still performing said animation

## Steps to reproduce

1. Choose Dilo (any growth stage)
2. Rest
3. Stand up from resting, while holding a directional key (WASD)
4. Observe sliding during animation

Note: This is possible for Allosaurus as well, however it is unable to move until about halfway through the animation.

video evidence: https://youtu.be/j93_jhgDlAA

## Build Information

> **Game Version:**  0.1.51.1 (dev branch)

> **Operating System**: Windows 10 Home

> **Network Role**: Client

**Comment by Hypno123** [comment]
Adult variant: https://www.youtube.com/watch?v=Fmv9NiQIFaY

**Comment by foszor** [comment]
Fixed in 0.1.51.5
