### ISSUE TITLE
Dilophosaurus can attack while resting

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#416]
## Expected Behavior

Dilo (and every other class) should not be able to attack while resting. 

## Current Behavior

The Dilophosaurus (juvie and adult) can currently attack while resting. 

## Steps to reproduce

1. Spawn as Dilophosaurus juvie or adult. 
2. Begin resting. 
3. Bite with your attack button. 

## Build Information

> **Game Version:** 0.1.51.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.51.2
