### ISSUE TITLE
Babies will be born with the same rotation properties as the nest they were born from.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#417]
## Expected Behavior

Babies to always be born the same way dinosaurs are spawned.

## Current Behavior

When a nest is built like this ( https://www.youtube.com/watch?v=n1axZ5PR4jc ) the baby born from this will be born at the same angolature as the nest, which means that they'll be born sideways, unlike how all the dinosaurs currently spawn standing straight.
Screenshots from The Warm Fridge : ( https://cdn.discordapp.com/attachments/401465476661641217/505026815748866048/20181025153527_1.jpg / https://cdn.discordapp.com/attachments/401465476661641217/505026883172433920/20181025153402_1.jpg  )

## Steps to reproduce

Build nest as shown in the video.
Nest someone in
The baby will be born at the same angolature as the nest.  (Tested on a sandbox server)

## Other Information
When I tested this on a sandbox server, I told the baby to relog, and they logged back in as this ( https://steamcommunity.com/sharedfiles/filedetails/?id=1547572127 ). I could eat said thing even though it was "alive".

## Build Information

> **Game Version:*0.1.51.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.51.2
