### ISSUE TITLE
Oro is missing it's eyes.

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#418]
## Expected Behavior

For the Oro to have it's eyes.

## Current Behavior

The eyes are missing from the current model.

## Steps to reproduce

Look at any AI oro.

![image](https://user-images.githubusercontent.com/40440922/47518679-a4995000-d859-11e8-90ff-b5023b667f54.png)

> **Game Version:** 0.1.51.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Reported in #409
