### ISSUE TITLE
Tree's shadows not being rendered at Low Shadows

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#42]
## Expected Behavior

Tree's shadows to be rendered Independently of Shadow settings

## Current Behavior

Tree's shadows won't be rendered if your set your shadows at Low, giving players a huge advantage

What i see with shadows at Epic:
![20180325104647_1](https://user-images.githubusercontent.com/35901313/37876364-c4ea1898-3021-11e8-838a-367a15552247.jpg)

What i see with shadows at Low:
![20180325104637_1](https://user-images.githubusercontent.com/35901313/37876367-cf9b5982-3021-11e8-951f-44089b855988.jpg)

## Steps to reproduce

-Spawn as anything.
-Go to a dark forested area/Wait until night and go to a forested area.
-Open you settings and set your shadows at low.
-Now you see it all.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1845429/TheIsle.log)

> **Game Version:** 0.1.35.2 ( development 0 

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
I don't think this is an issue we can fix without severely hindering lower end players again.
