### ISSUE TITLE
Scent coming from rivers is not visible through objects.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#420]
## Expected Behavior

Scent coming from rivers to be visible through objects like scent coming from lakes.

## Current Behavior

Highlighted rivers are not visible through objects (Or it could just be the one in the video below)

## Steps to reproduce

Press Q to use scent.
See how all the lakes are visible through objects, but rivers aren't, despite being a water source too.
( https://www.youtube.com/watch?v=1FRGfH8DWPI&feature=youtu.be )

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
The patch notes *did* specify only lakes are scentable through other objects. We don't have a way to support that with rivers.
