### ISSUE TITLE
Ceratosaurus uses Carnotaurus image for "my character screen"

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#421]
## Expected Behavior

The Ceratosaurus to show Ceratosaurus images on its character screen.

## Current Behavior

The Ceratosaurus currently shows Carnotaurus images for its character screen.

![image](https://user-images.githubusercontent.com/30550499/47583008-fcb17e80-d94d-11e8-87b9-4ee19f79d579.png)

## Steps to reproduce

1. Spawn as Cerato.
2. Press insert and look at images of Carnotaurus.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed with revision 3046
