### ISSUE TITLE
Nest Icons do not appear/work

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#423]
## Expected Behavior

Under gameplay settings, if you select "Nest Icon", then you should be able to locate a nest you have laid.

## Current Behavior

When you lay a nest, there is currently no way to locate where you put it. The Nesting Icon is no longer working.

## Steps to reproduce

Lay a nest. Make sure "Nest Icons" is selected. Notice that you cannot locate your nest.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Nest icons are yet to be added, so this is more of an enhancement.
