### ISSUE TITLE
Bush on Thenyaw has missing texture

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#425]
## Expected Behavior

The bush should not be missing its texture.

## Current Behavior

The bush seen in the pictures below currently have a missing texture for its branches.

![image](https://user-images.githubusercontent.com/30550499/47588156-350c8900-d95d-11e8-92a3-347a3dada34f.png)

![image](https://user-images.githubusercontent.com/30550499/47588172-3fc71e00-d95d-11e8-9cc9-c8e3c41278c2.png)

## Steps to reproduce

1. Spawn on Thenyaw.
2. Find one of the bushes seen in the picture.
3. Look at the texture of the branches.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
![image](https://user-images.githubusercontent.com/30550499/47592144-f29d7900-d969-11e8-8063-ab7748c228d2.png)

**Comment by ikarop** [comment]
Fixed in the next build.
