### ISSUE TITLE
Maiasaura (adult and juvie) scent is delayed

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#427]
## Expected Behavior

The Maiasaura (adult and juvie) scent should not be delayed. Items should appear as soon as the animation finishes.

## Current Behavior

The Maiasaura (adult and juvie) currently takes a few more seconds after its scent animation has played before the scented items will appear.

(This requires you to hold Q to scent these items even after the animation is finished.)

https://www.youtube.com/watch?v=Kht4TFbhbEw

## Steps to reproduce

1. Spawn as Maiasaura (adult or juvie).
2. Hold Q to use scent.
3. Wait until the animation has played - nothing will appear.
4. Keep holding Q for a few seconds until after the animation has played and the items appear.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Starting in 0.1.51.5, all animals scent visualization will begin during the last 10% of the scent animation
