### ISSUE TITLE
Unable to re-invite players to your group after dying

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#428]
## Expected Behavior

If you die, you should still be able to invite players to your group.

## Current Behavior

If you invite a player to your group and die, you will be unable to re-invite them to your group. 

They can however invite you to their group (which may or may not be your original group.)

## Steps to reproduce

1. Spawn as anything.
2. Invite a player to your group.
3. Be killed or die through any other means.
4. Attempt to invite the player again and be unable to.
5. Have them invite you and be able to accept the invite.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed
