### ISSUE TITLE
Pressing F3 to block a group invite does not block the player

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#429]
## Expected Behavior

Pressing F3 to block group invites from a player should block them.

## Current Behavior

Pressing F3 does not block the player from sending group invites.

## Steps to reproduce

1. Spawn in as anything.
2. Have someone that is the same species as you send a group invite.
3. Press F3 and be unable to block the player.
4. Continue receiving group invites despite pressing the block button.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.51.5
