### ISSUE TITLE
Chat auto appears even when in different channels

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#43]
## Expected Behavior

The chat should not appear when in a different channel to where messages are being typed.

## Current Behavior

When in group/global chat, the text will auto appear from messages sent in local chat.

## Steps to reproduce

1. Spawn as anything.
2. Change to global chat.
3. Ask another player to type in local chat and watch the messages from global auto appear.

## Build Information

> **Game Version:** 0.1.35.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.3
