### ISSUE TITLE
Waves on Thenyaw prevent footsteps being heard

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#432]
## Expected Behavior

Creatures should be making footstep sounds when walking everywhere, even along the coast of Thenyaw.

## Current Behavior

Footstep sounds cannot be heard along the whole of the coast of Thenyaw. I believe they are being muted by the sound of the crashing waves.

This isn't much of an issue where the waves are at their loudest, but is very jarring when it's silent further uphill.

https://www.youtube.com/watch?v=BElVoavoliA

## Steps to reproduce

1. Spawn as anything.
2. Head to the coast.
3. As you get closer and begin to hear the waves, you will notice your footsteps go silent.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Emanthealmighty** [comment]
Side note: Crouching or limping while moving will cause footsteps to be heard even when near the waves, for some reason.

**Comment by Hypno123** [comment]
May be worth noting that some of the larger creatures trotting footsteps can be heard, but the sprinting cannot. Trike is one example of this.

**Comment by Hypno123** [comment]
Fixed in 0.1.51.3
