### ISSUE TITLE
Blood splash effect causes FPS drops

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#434]
## Expected Behavior

The blood splash effects should not be causing big FPS hits.

## Current Behavior

The blood splash effects are causing big FPS hits. I personally dropped from solid 60 to mid 40s after I received bleed.

## Steps to reproduce

1. Spawn as anything.
2. Be bitten.
3. Watch FPS stutter and drop.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
You're talking about splatters on the ground right? There were some potential issues with those that should be fixed with the next build.

**Comment by dinosauriac** [comment]
Calling this one fixed.
