### ISSUE TITLE
Tyrannosaur Nest is not how it should be

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#435]
## Expected Behavior

The Tyrannosaur Nest to look like a Rex Nest.

## Current Behavior

Looks like a herbivore nest now.

## Steps to reproduce

Become a Female Adult Rex, Press B to place down the nest and you will see the nest is a herbivore nest instead of a Rex nest.
![20181026194304_1](https://user-images.githubusercontent.com/40440922/47598132-c2ec7200-d965-11e8-8e7e-4f054da5d3d4.jpg)
![20181026194251_1](https://user-images.githubusercontent.com/40440922/47598134-c4b63580-d965-11e8-8b9d-b4c36bae17ba.jpg)

> **Game Version:** 0.1.51.2

> **Operating System**: Windows
> **Network Role**: Client

**Comment by Hypno123** [comment]
This is the correct nest for large carnivores.
