### ISSUE TITLE
Dynamic Foliage Activated Client-Side Only

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#436]
## Expected Behavior

Dynamic foliage interaction triggering for all players server-side.

## Current Behavior

Dynamic foliage is only triggering for the player client-side.

## Steps to reproduce

1. Have at least two players spawn as any dinosaur (User A and User B).
2. Have both users run through the foliage coded for dynamism on Thenyaw.
3. Notice that your dinosaur (User A) will activate dynamic foliage as you move through the foliage.
4. Have User B run through the same foliage -- notice the foliage remains static.

**[Test Level // Sandbox]**
Reeds: https://streamable.com/mmywb
Edible Foliage: https://streamable.com/ykszw

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
This is more of an enhancement than a bug. The team still needs to decide whether foliage interaction will be synced between players or not.
