### ISSUE TITLE
Carnivore Infinite Eating Loop - Ragdolls Only

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#437]
## Expected Behavior

Carnivores are prevented from eating when hunger reaches 100% fullness when dining on gore (ribs) or carcasses (ragdolls).

## Current Behavior

Carnivores can continue eating past 100% fullness if dining on a carcass (ragdoll).
_Note: Dining from **gore (ribs**) functions as intended and prevents any overeating._ 

## Steps to reproduce

1. Spawn as any carnivore.
2. Find a carcass (ragdoll) and begin the eating prompt.
3. Continue to eat until the eating animation stops signifying 100% fullness. 
4. Immediately begin eating again if the food source is still a ragdoll.
-- Note: If the carcass disappears the player can choose to remain in the eating animation.

**[TestLevel // Sandbox]**
**Overeating Visual Reference:** https://streamable.com/6f96j
**Infinite Eating Animation Loop:** https://streamable.com/9ivdt

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Just checked client hosted game and the issue persists there too.

**Comment by looterz** [comment]
Fixed in 0.1.51.5
