### ISSUE TITLE
Nest Management Menu Persists After Death Until Logout

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#438]
## Expected Behavior

If killed while in the Nest Management Menu, users are to respawn as a dinosaur of their choice without the nest menu persisting on their screen after character selection.

## Current Behavior

If killed while in the Nest Management Menu, the menu persists after the user has selected a new dinosaur and begins play until the user logs out.

## Steps to reproduce

1. Be an adult dinosaur and build a nest.
2. Enter Nest Management while sitting on or near the nest.*
3. Have your dinosaur get killed while within the menu.
4. Respawn as a dinosaur of your choice and notice the nest menu persists on screen as soon as you begin playing your dinosaur regardless of how many times you die.**

-- *Sitting on the nest [B] or away from the nest [E] prompts the same persistent menu result.
-- **The only workaround to exit the menu is to log out and back into the server. No amount of character selections will exit the menu (see below).

**The following measures were tested:**
Same species carnivore after death (same sex)
Different species carnivore after death (same sex)
Carnivore to herbivore after death (same sex)
Same species herbivore after death (same sex)
Different species herbivore after death (same sex)
Herbivore to carnivore after death (opposite sex)

**[TestLevel // Sandbox]**
**Persistent Nest Management Menu PART I:** https://streamable.com/jcw2m
**Persistent Nest Management Menu PART II:** https://streamable.com/vbm12

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.51.5
