### ISSUE TITLE
Large dinosaur water trail effect twitches when NV is on.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#439]
## Expected Behavior

Large dinosaur water trail effect to work properly with NV.

## Current Behavior

Large dinosaur water trail effect twitches when NV is on.
Video Evidence: https://youtu.be/5oVCULtSRLc

Happens regardless of Graphical settings.

## Steps to reproduce

1.Select any large dinosaur (e.g Rex/Trike)
2.Sprint on the water
3.Repeat step 2 with NV on and notice that the water trail will twitch.

## Build Information

> **Game Version:** 0.1.51.2 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in the next build.
