### ISSUE TITLE
Inter-species chatting

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#44]
## Expected Behavior

Players should not be able to talk to those that are different species.

## Current Behavior

Gigas can currently talk to rexes via local chat. (There may be more species - will update this if that's the case.)

## Steps to reproduce

1. Spawn as Giga.
2. Have another player spawn as Rex.
3. Talk to them in local chat.

## Build Information

> **Game Version:** 0.1.35.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.3

**Comment by Emanthealmighty** [comment]
Retested on 22 April 2019
Gigas and Rexes cannot talk with eachother as intended.
