### ISSUE TITLE
Impersonating other players by typing out a long message

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#440]
## Expected Behavior

You should not be able to impersonate other players by typing a message long enough to go onto the next line.

## Current Behavior

If you type a long enough message that the text goes onto the next line down, it is possible to impersonate other players.

Server log: 

![image](https://user-images.githubusercontent.com/30550499/47623027-f8c75d00-db03-11e8-9cf7-3cdc0f4d0c1a.png)

How the messages look in-game:

![image](https://user-images.githubusercontent.com/30550499/47623017-de8d7f00-db03-11e8-8df3-a11f53a3d30b.png)

## Steps to reproduce

1. Spawn in as anything.
2. Type out a message long enough that it moves onto the next line.
3. Type out the players name on the next line, followed by whatever message you want it to look like they said.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.51.5
