### ISSUE TITLE
Biting as dilo causes body to stiffen

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#441]
## Expected Behavior

The Dilophosaurus' body should not stiffen up when biting.

## Current Behavior

The Dilophosaurus' (both juvie and adult) body stiffens up when biting.

https://www.youtube.com/watch?v=onbrn6CCz9A

## Steps to reproduce

1. Spawn as Dilo.
2. Bite.

## Build Information

> **Game Version:** 0.1.51.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Emanthealmighty** [comment]
I'm pretty sure this is only temporary as a full body biting animation hasn't been done yet, depending on when that will be done, they could just change the current animation so that it only affects the interested body parts rather than the whole body.
