### ISSUE TITLE
Opening character menu while interacting causes lock up

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#442]
## Expected Behavior

Opening the character menu while interacting with something should not cause your character to lock up and loop the animation.

## Current Behavior

Opening the character menu while interacting with something will cause your character to lock up and loop the animation that they are performing. 

This can be stopped by simply pressing the interaction button again.

https://www.youtube.com/watch?v=GnTYQWGSx1Y

## Steps to reproduce

1. Spawn as anything.
2. Find something to interact with (corpse or water.)
3. Hold the interaction button, press insert, then release the interaction button.
4. Press insert again to hide the menu. Your character will continue to interacting with the object.

## Build Information

> **Game Version:** 0.1.51.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Related to #463, fixed in 0.1.51.5
