### ISSUE TITLE
Certain Tree Meshes Lacking Collision

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#447]
## Expected Behavior

For the character to properly be stopped by collision in these tree meshes and unable to phase through.

## Current Behavior

Any character can phase through the 'smaller' tree meshes and proceed through as if it were a static object lacking collision, not halting the player as they walk into the tree.

## Steps to reproduce

1. Spawn as any character.
2. Proceed to move through select tree mesh (smaller than the alternate meshes, however large enough that it presents itself as a bug.)
3. Notice that you will phase through the tree mesh, as opposed to being halted by it.

**VIDEO EVIDENCE:**
https://streamable.com/fkgci - (Notice how my character will phase through certain trees as they lack collision, and be stopped by others of similar size.)
**COORDINATES:**
![image](https://user-images.githubusercontent.com/26824146/48389596-31eafa00-e6cc-11e8-94ae-e1c18d0e85cd.png)

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.51.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in the next build.
