### ISSUE TITLE
Hunger Meter Reverts to 75% Despite 100% Fullness

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#448]
## Expected Behavior

The hunger meter will match the player's level of fullness as it reaches 25%, 50%, 75%, and 100%.

## Current Behavior

The hunger meter reverts to a static 75% fill upon reaching 100% and will not increase past this point despite the player fullness reaching a value greater than 75%. 

**Note:** _The meter will decrease beyond 75% as the dinosaur reaches 50%, 25%, so on and so forth, but will not increase beyond 75% despite reaching 100% fullness when tended to._

## Steps to reproduce

1. Log onto any server as a dinosaur of your choice.
2. Eat when your hunger value begins to drop -- fill to 100%.
3. Notice the hunger meter suddenly revert to 75% despite the hunger meter appearing full and the dinosaur terminating the eating animation automatically.

**[TestLevel // Sandbox // Growth Enabled]**
**Video Reference:** https://streamable.com/7zsjo

## Build Information

> **Game Version:** 0.1.51.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Does this still exist in 0.1.51.5?

**Comment by Hypno123** [comment]
Fixed in 0.1.51.5
