### ISSUE TITLE
Can't unblock players via scoreboard

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#45]
## Expected Behavior

You should be able to unblock players once you have them blocked.

## Current Behavior

After blocking group/nest invites, the player cannot unblock the person - it automatically blocks them again.

https://gyazo.com/8663ca1fdbf8d0248502eac94a84bf82

Attempting to block a player on the scoreboard also doesn't function (you have to block them by getting them to send an invite and pressing F3.)

## Steps to reproduce

1. Have another player invite you to a group or nest.
2. Hit F3 to block the invite.
3. Go to the scoreboard and try to unblock them by pressing the muted button on their name.

## Build Information

> **Game Version:** 0.1.35.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.3
