### ISSUE TITLE
Tyrannosaur Nest Health Value Too Low

### ISSUE THREAD

**Issue by Aliens218** [TheIsleGame/bugs#452]
## Expected Behavior

For the Tyrannosaurus to have normalized nest health values, as opposed to ones that allow for it to be hastily destroyed upon taking damage from any source.

## Current Behavior

The Tyrannosaurus nest is currently destroyed too quickly when taking damage, when the nests of other animals have a higher health output.

## Steps to reproduce

1. Spawn in as female adult Tyrannosaurus.
2. Fully build a nest.
3. Have someone damage your nest and notice the health drop rapidly, allowing for it to be destroyed in a mere two attacks.

**VIDEO EVIDENCE:**
https://streamable.com/tbzey

**NOTE:**
_Adult Dryosaurus vs Tyrannosaur Nest // 1x attack from Dryosaurus resulted in the nest taking 55% damage.
In previous nesting destruction attempts for all other dinosaurs, multiple hits were required with the nest taking 5-10% damage per hit._

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.51.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.51.5
