### ISSUE TITLE
Flashing Lights Offset in Main Menu Sub-Menus

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#453]
## Expected Behavior

The flashing lights found on the lower right of the main menu shall remain in the same position for all sub-menus. 

## Current Behavior

The flashing lights found on the lower right of the main menu become offset to the left when switching to the Settings, Replays, and Mods sub-menus. 

**NOTE:** 
_Play, News, and Extra categories show the flashing lights in the correct positions._

## Steps to reproduce

1. Start the game and load into the main menu.
2. Select any of the following menus: Settings, Replays, or Mods
3. Notice the flashing lights in the lower right move very minutely to the left outside of their sockets.

**Video Reference (tabbing through each category):** 
https://streamable.com/aovs9

**Main Menu Positional Reference:**
![image](https://user-images.githubusercontent.com/42288648/48396114-615b3000-e6e7-11e8-9c93-a5faaf78010f.png)

**Settings Menu Positional Reference:**
![image](https://user-images.githubusercontent.com/42288648/48396128-6ddf8880-e6e7-11e8-9169-fb31cf50a058.png)

## Build Information

> **Game Version:** 0.1.51.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Reported in #397

**Comment by dinosauriac** [comment]
Fixed as of the latest internal build.
