### ISSUE TITLE
Settings Menu Not Reflecting Main Menu Time Of Day

### ISSUE THREAD

**Issue by Skysealer** [TheIsleGame/bugs#454]
## Expected Behavior

The time of day indicated within the Main Menu should match within each sub-menu (settings, replays, mods, news, extras). 

## Current Behavior

The Settings sub-menu does not follow the Main Menu time of day, remaining daylight while the Main Menu indicates night hours.

**NOTE:** 
_Replays, Mods, News, and Extra sub-menus all reflect the same time of day as the Main Menu._

## Steps to reproduce

1. Log on during the night -- Main Menu will appear dark to reflect current time of day
2. Select 'Settings'.
3. Notice Settings reflects the daylight hours.

**Video Reference:**
https://streamable.com/zjskh

**Main Menu - Settings Menu Disparity:** 
![20181113020838_1](https://user-images.githubusercontent.com/42288648/48396862-d6c80000-e6e9-11e8-9ad2-f63f49e31c2c.jpg)

![20181113020857_1](https://user-images.githubusercontent.com/42288648/48396877-e34c5880-e6e9-11e8-9a79-83e1fe9be3a3.jpg)

## Build Information

> **Game Version:** 0.1.51.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Not sure if it's even meant to reflect the time of day or if it just changes shade occasionally to mix things up. @dinosauriac can confirm.

If it doesn't reflect time of day then it's a great idea.

**Comment by dinosauriac** [comment]
There's supposed to be a check that toggles the theming based on whether you're on the main menu or viewing the settings in-game, but it seems to be doing the inverse currently... so the settings menu is only changing its look when viewed while playing.

**Comment by dinosauriac** [comment]
Fixed as of the latest internal build.
