### ISSUE TITLE
When looking from under water or at a dead body, dinos have no eye texture with nightvision

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#455]
## Expected Behavior

When using night vision, I expect to see eyes with a dead corpse or from looking under water seeing an eye texture exist.

## Current Behavior

When using night vision and looking at dead corpses or from under water, the eye textures are missing.

## Steps to reproduce.
1. Spawn in as any dinosaur.
2. When it is night time, use your NV and look at dead corpses or yourself underwater, no eye texture is there.
![20181112214952_1](https://user-images.githubusercontent.com/40440922/48450089-db84c680-e772-11e8-880c-ce0a1f5b39c6.jpg)
As you can see with Nivison's Giga, the eye texture is missing. This also happens with dead bodies, and night vision. 

> **Game Version:** 0.1.51.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Not entirely sure what you mean by this. Eyes are meant to glow with night vision on and if the player turns away from you, that glow will not be as strong as if they were looking directly at you.

If you were mistaken, please let me know so that I can close this.
