### ISSUE TITLE
Hunger and thirst do not appear on HUD

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#458]
## Expected Behavior

Hunger and thirst meters to appear on the HUD.

## Current Behavior

Hunger and thirst meters are no longer appearing on the HUD.

Static HUD enabled:

![image](https://user-images.githubusercontent.com/30550499/48712755-74e62980-ec06-11e8-9d46-98eb67ac51e5.png)

## Steps to reproduce

1. Spawn in.
2. Enable static HUD (although dynamic lacks them too).
3. Eat or drink.
4. Watch as neither meter appears.

## Build Information

> **Game Version:** 0.1.51.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Finally fixed in 0.1.51.6
