### ISSUE TITLE
Drinking hint shows while swimming

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#459]
## Expected Behavior

The hint to begin drinking should not appear while swimming.

## Current Behavior

The hint to begin drinking appears while swimming, though it is not possible to do so.

![image](https://user-images.githubusercontent.com/30550499/48864494-a278d180-edc4-11e8-9d90-6cf6687cd9fd.png)

## Steps to reproduce

1. Spawn.
2. Enter swimmable water.
3. Look on screen at the hint.

## Build Information

> **Game Version:** 0.1.51.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.51.5
