### ISSUE TITLE
Gallimimus shrinks upon growing to adult

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#46]
## Expected Behavior

The galli should increase in size when growing, not shrink.

## Current Behavior

The galli shrinks in size when you progress to adult.

https://clips.twitch.tv/RamshackleSlipperyPorcupineSpicyBoy

## Steps to reproduce

1. Spawn as galli.
2. Survive until you are ready to grow to adult.
3. Hit the grow button and watch your character shrink.

## Build Information

> **Game Version:** 0.1.35.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Paleocolour** [comment]
This should be fixed next patch. To clarify, this happens when galli grows from hatchling to juvenile, not juvenile to adult.
