### ISSUE TITLE
Server list does not show all servers from every patch

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#460]
## Expected Behavior

Server list should show all servers when "Hide Outdated" is disabled.

## Current Behavior

Server list currently only shows patches 0.1.51.2 and above:

![image](https://user-images.githubusercontent.com/30550499/48920045-71fd6a00-ee8e-11e8-8e6e-adad839a4e9d.png)

Switching to normal branch (0.1.50.9) will reveal the rest of the servers:

![image](https://user-images.githubusercontent.com/30550499/48920213-737b6200-ee8f-11e8-9f94-c6257d17aa8a.png)

## Steps to reproduce

1. Start the game.
2. Go to the player list.
3. Look for servers on version 0.1.50.9 and notice you can't find any.

## Build Information

> **Game Version:** 0.1.51.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
I'm looking into this one, it seems to be an issue with the new unreal engine version, unrelated to our game.

**Comment by looterz** [comment]
Fixed in 0.1.51.5, but servers running on UE4 4.19 will not be visible due to engine level changes.
