### ISSUE TITLE
Jumping does not pop up stamina bar.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#461]
## Expected Behavior

Stamina bar to pop up whenever player jumps

## Current Behavior

Stamina bar does not pop up whenever player jumps.
Video evidence: https://youtu.be/b7f8mmLygmA

Works fine with static HUD,as expected.

## Steps to reproduce

-Select any dinosaur capable of jumping and jump repeatedly.
-Notice that stamina bar won't pop up.

## Build Information

> **Game Version:** 0.1.51.4 ( development )

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.51.5
