### ISSUE TITLE
Opening "My Dinosaur" screen while sprinting will allow the player to continue sprinting without holding their Sprint key

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#463]
## Expected Behavior

Opening the "My Dinosaur" screen shouldn't allow the player to sprint without holding their Sprint key when closing it.

## Current Behavior

Opening the My Dinosaur screen while sprinting allows the player to continue sprinting without pressing their Sprint key.

## Steps to reproduce

1. Spawn as anything.
2. Begin sprinting.
3. While sprinting, open your "My Dinosaur" screen with Insert.
4. Release your Sprint key, then close the screen. You can now sprint without holding your Sprint key.

## Build Information

> **Game Version:** 0.1.51.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
0.1.51.5
