### ISSUE TITLE
Opening Character menu at certain times disables chat noises

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#468]
## Expected Behavior

When using the in-game chat features, your dinosaur should always make noise when communicating

## Current Behavior

When certain requirements are fulfilled, this does not happen and chatting becomes completely silent

## Steps to reproduce

1. Begin a sniff, eating, or drinking animation
2. Without stopping the animation, press the button to open your Character menu (Insert by default)
3. Chat like normal.  At this point you also should be able to close the menu.   The glitch will now be in effect.

Notes: While active, your dinosaur will be unable to eat or drink, but seems to be able to perform all other actions.  Sniffing or pressing Esc while the glitch is active will end it.

Video link of glitch at work: https://youtu.be/oYV9I4DJaAM

## Build Information

> **Game Version:** 0.1.51.4 (dev branch)

> **Operating System**: Windows 10 Home

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.51.5
