### ISSUE TITLE
Some food bushes are not edible

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#469]
## Expected Behavior

All bushes that light up should be edible.

## Current Behavior

Some of the bushes are not edible for one dinosaur, while functioning as intended for the other.

As a parasaur I could not interact with a bush, while a diablo could eat from it. I was not at full hunger and the bush was not depleted. These bushes were near the coastline, on the southern end.

![image](https://user-images.githubusercontent.com/38515115/49517667-bca5bb80-f86a-11e8-81aa-442164470889.png)

## Steps to reproduce

As a parasaur, attempt to eat.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.51.4 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Should be fixed now. Will reopen if it comes up again.
