### ISSUE TITLE
Dinosaur calls abruptly cut out

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#47]
## Expected Behavior
Expected: Dinosaur calls should behave correctly.
## Current Behavior
Currently: Many calls (in particular the long-distance variations, as well as possibly others) abruptly end, seemingly before the clip finishes playing.
## Steps to reproduce
To reproduce: Observe sounds made by certain dinosaurs at a distance (Para, Ava known so far, as well as Utah's new broadcast if heard from close range). 
## Build Information
Game version 0.1.35.2 (dev)
OS: Windows 10
Role: Client.

Below is a short video clip of an example, coming from what I believe is Para.

https://youtu.be/8iTbC40bMCg

**Comment by Souretsu** [comment]
As an update, Utah's broadcast no longer does this.  Have noticed that the distant version of rex's 4-call does, however.

**Comment by Hypno123** [comment]
Doesn't seem to be an issue in 0.1.39.7.

Correct me if I'm wrong and I'll re-open.
