### ISSUE TITLE
Shadows flickering depending on "Shadows" setting

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#473]
## Expected Behavior

Shadows should not be flickering, regardless of the setting that they are on.

## Current Behavior

Shadows are flickering at all levels on the Shadows setting, although the flicker is much less noticeable at Epic and Cinematic.

Cinematic: https://gyazo.com/40ce52308f6a66d9e01e65dec1c6d7e1

Epic: https://gyazo.com/68ba4a658be7ddc819c5f06e5cc4d94c

High: https://gyazo.com/43f692a0b2ae75947581cce027a4a416

Medium: https://gyazo.com/214e050cf32d44536ed1ed6d6fb57338

Low: https://gyazo.com/5e4c0a25472fff098c2c6dd946ebf9f7

## Steps to reproduce

1. Go to the main menu.
2. Lower your shadows setting to High or below for the most noticeable flickering.
3. Enter any server, set the time to day and look at the shadows.

## Build Information

> **Game Version:** 0.1.51.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Improved in the next build.

**Comment by spiral-static** [comment]
Issue still apparent in version 0.1.53.3, especially on Medium/Low settings.

Medium:
https://www.youtube.com/watch?v=ydnYV9WXYaU&feature=youtu.be

Low:
https://www.youtube.com/watch?v=cUraGldFSag&feature=youtu.be
