### ISSUE TITLE
Relogging without waiting for safe log timer causes "My Character" menu to be inaccessible

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#474]
## Expected Behavior

Relogging into your character without safelogging shouldn't cause the "My Character" screen to become inaccessible.

## Current Behavior

If you relog without waiting for the safe log timer, your character will remain in the server.

If you log back into your character before it disappears, you will be unable to access your My Character menu with the insert button.

## Steps to reproduce

1. Enter a server. Use insert to access character menu as normal.
2. Log out of the server without waiting for the safe log timer.
3. Log back into your character before it disappears. 
4. Attempt to view My Character menu with insert and be unable to until you safe log out properly.

## Build Information

> **Game Version:** 0.1.51.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.51.6
