### ISSUE TITLE
Players shown as admin in client hosted games without admin permissions

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#475]
## Expected Behavior

If players are shown as admins on the scoreboard for client hosted games, they should also be given admin permissions.

## Current Behavior

As shown in the following picture, Karth is shown as an admin in his client hosted game on the scoreboard. However, when using the /help command, he is only given access to regular player commands.

![image](https://user-images.githubusercontent.com/30550499/49830982-9ca25a80-fd8a-11e8-8a77-d932a014fe00.png)

## Steps to reproduce

1. Be on a regular player account.
2. Host a client game.
3. Check scoreboard at your admin name.
4. Type /help in the chat for a list of commands you are permitted to. You cannot use any that are admin restricted.

## Build Information

> **Game Version:** 0.1.51.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.51.5
