### ISSUE TITLE
Dryosaurus and Gallimimus' landing footstep points backwards

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#481]
## Expected Behavior

If a dryo/galli  jumps and when it lands a footstep appears,it should point forward.  

## Current Behavior

If a dryo/galli  jumps and when it lands a footstep appears,it points backwards
Video evidence: https://youtu.be/_9Oaj-iZ2Fs

## Steps to reproduce

-Be a dryosaurus/gallimimus (any life stage)
-Run and jump (keep holding shift whilst mid-air so a footstep can appear more easily)
-Notice that whenever you land,the landing footstep will point backwards.
## Build Information

> **Game Version:** 0.1.51.5 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed as of revision 3055
