### ISSUE TITLE
Inconsistent Crouch issue

### ISSUE THREAD

**Issue by Kingjaffad** [TheIsleGame/bugs#482]
## Expected Behavior

I press the crouch button while standing still, walking or trotting and enter into the crouched stance.

## Current Behavior

The crouch button works inconsistently, mostly while trotting. Sometimes you are required to press the crouch button multiple times. 2, 3 or 4 times. So far I have only tested this with Juvenile Giganotosaurus. I will test other creatures/life stage to see if they share this issue.

## Steps to reproduce

Simply trot around and repeatedly attempt to crouch and uncrouch. I have found this issue most commonly happens while walking in a straight line.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> Game version is 0.1.51.5 Development Branch

> **Operating System is Windows 7

> I encountered this issue while playing on "The Isle Official Dev 2"
[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2681989/TheIsle.log)

**Comment by Hypno123** [comment]
You cannot be moving if you want to begin crouching now. Are you sure it's not because of that change?

**Comment by Kingjaffad** [comment]
The patch notes claim that you can no longer be moving while moving at a sprint speed.

**Comment by Hypno123** [comment]
This is intended.
