### ISSUE TITLE
Adult Dryosaurus cannot access nest after building one.

### ISSUE THREAD

**Issue by PCSly** [TheIsleGame/bugs#486]
## Expected Behavior

After laying a nest, you should be able to press E to access your nest.

## Current Behavior

After laying a nest, you cannot access your nest by pressing E.

## Steps to reproduce
1. Spawn in as a Female Adult Dryosaurus.
2. Press B to make a nest.
3. Try to access Nest, nothing happens.
https://www.youtube.com/watch?v=_AKHzjlISdc

> **Game Version:** 0.1.51.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed next patch.
