### ISSUE TITLE
Lighting from lava affects characters through terrain

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#487]
## Expected Behavior

The light from the lava pits should not affect characters through solid terrain.

## Current Behavior

The light from lava pits shines through terrain, making character's glow.

![image](https://user-images.githubusercontent.com/30550499/50048046-2ff4cc00-00ba-11e9-9954-83144ea6953b.png)

## Steps to reproduce

1. Spawn in as any character.
2. Walk on top of the terrain above a lava pit.
3. Look at your character glow.

## Build Information

> **Game Version:** 0.1.51.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Turned shadows off to see if it'd help performance much, can easily toggle them back on.

**Comment by Hypno123** [comment]
Fixed.
