### ISSUE TITLE
Lava does not deal any damage

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#488]
## Expected Behavior

Lava should damage if not instantly kill players when stepped in.

## Current Behavior

Lava currently does no damage on Thenyaw for both the canyon and volcano.

## Steps to reproduce

1. Spawn in.
2. Go to lava.
3. Jump in and survive.

## Build Information

> **Game Version:** 0.1.51.6

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Possibly related to changes in the blueprint's tick rate / dormancy settings.

**Comment by Hypno123** [comment]
Fixed in 0.1.52.1
