### ISSUE TITLE
Juvenile life stages that do not light up on My Dinosaur screen

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#489]
## Expected Behavior

The stage in your life cycle should be lighting up on the My Dinosaur screen when playing as them.

## Current Behavior

Currently, the juvenile Dilo, Dryo, Galli, Maia and Para life stages do not light up when playing as them.

Here is a working example of the Allosaurus juvenile:

![image](https://user-images.githubusercontent.com/30550499/50244455-e3660500-03c7-11e9-9c8a-fcbfca47417b.png)

Here are the before mentioned juveniles:

![image](https://user-images.githubusercontent.com/30550499/50244515-04c6f100-03c8-11e9-939f-64f32e816c30.png)
![image](https://user-images.githubusercontent.com/30550499/50244528-11e3e000-03c8-11e9-872e-845a8aa9075a.png)
![image](https://user-images.githubusercontent.com/30550499/50244546-1d370b80-03c8-11e9-9cf6-e4ce7ec1a6d3.png)
![image](https://user-images.githubusercontent.com/30550499/50244554-21632900-03c8-11e9-8a01-e9729d29035f.png)
![image](https://user-images.githubusercontent.com/30550499/50244564-2a53fa80-03c8-11e9-8918-2c764bec16e7.png)

## Steps to reproduce

1. Spawn in as one of the before mentioned juveniles.
2. Look at your My Dinosaur screen.
3. See that your life stage is not lit up, even though you are currently playing as it.

## Build Information

> **Game Version:** 0.1.51.6

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
These are all dinosaurs without a sub adult growth stage, I'll fix this

**Comment by foszor** [comment]
Fixed in 0.1.51.6
