### ISSUE TITLE
Admins/devs cannot join server when server is full

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#49]
## Expected Behavior

Server admins/developers should be able to join a server regardless of its player limit and if the server is full, according to this patch:

http://steamcommunity.com/games/TheIsle/announcements/detail/1596955106526667374

## Current Behavior

Server admins/developers are kicked out of the server if it's full.

## Steps to reproduce

1. Be a developer/server admin.
2. Attempt to join a full server.
3. Be kicked out of the server.

## Build Information

> **Game Version:** 0.1.35.2 (dev)

> **Operating System**: Windows

> **Network Role**: Listen, dedicated.

**Comment by Hypno123** [comment]
Fixed in 0.1.35.3

**Comment by Hypno123** [comment]
Still apparent in 0.1.35.4 - the error given instead is 'The connection to the server has been lost' rather than 'Server full'.

**Comment by looterz** [comment]
Should be fixed in 0.1.35.5, will keep it open until its confirmed

**Comment by looterz** [comment]
Confirmed this is now fixed.
