### ISSUE TITLE
Female skin is applied to male Giga after growing from subadult to adult

### ISSUE THREAD

**Issue by dinosauriac** [TheIsleGame/bugs#490]
## Expected Behavior

Giga should have the correct skin applied after growing to adult stage. 

## Current Behavior

The female skin is still being applied when growing from subadult to adult as a male. Should be switching to the stripey-faced version at that point if you're playing a male. It doesn't actually have separate skins for male & female juvenile or subadult stages, unsure if that might be contributing to the issue. 

## Steps to reproduce

Play in Survival mode as a male Giganotosaurus, grow to subadult, then grow to adult. The skin does not change. 

## Build Information

Version 0.1.51.6

**Comment by Hypno123** [comment]
Fixed in 0.1.52.1
