### ISSUE TITLE
Dinosaurs can scent while building nest

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#491]
## Expected Behavior

Dinosaurs to be unable to scent while building nest

## Current Behavior

Dinosaurs can scent while building nest.
All survival species.
Video evidence: https://youtu.be/Dx16erK-eak

## Steps to reproduce

-Select any survival dinosaur (female).
-Build a nest.
-Use scent while building nest.

## Build Information

> **Game Version:**0.1.51.6 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ExtraHu3** [comment]
Originally reported by Paco#1497

**Comment by foszor** [comment]
Fixed in 0.1.52.1
