### ISSUE TITLE
Hatchling Giganotosaurus issues

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#493]
## Expected Behavior

The hatchling giganotosaurus to not do the things showcased in this video ( https://www.youtube.com/watch?v=kFEpGtaVuoA )

## Current Behavior

The hatchling giganotosaurus' legs move in impossible ways. ( For example, when its crouching, its legs twist towards eachother. It's left leg also moves strangely, you can better see it when the hatchling giganotosaurus is limping. The entire model shifts unnaturally when it bites and calls, too)
Also noticed it sinks into the ground when it rests.

## Steps to reproduce

Spawn in as an hatchling giganotosaurus, perform various movements. Notice how the legs move.

## Build Information

> **Game Version:** 0.1.51.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
