### ISSUE TITLE
Leave Group button not working

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#495]
## Expected Behavior

In the My Dinosaur menu, the Leave Group button should be useable to exit your group at any time.

## Current Behavior

Currently the Leave Group button does not appear to work.

## Steps to reproduce

1. Join a group
2. Through the character menu, attempt to leave the Group

video: https://youtu.be/nbqovpNm9ic

## Build Information

> **Game Version:** 0.1.51.7 (live branch)

> **Operating System**: Windows 10 Home

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.52.1
