### ISSUE TITLE
Herrerasaurus' eating animation has a flame particle.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#497]
## Expected Behavior

The flame particle in the herrerasaurus' eating animation to be blood.

## Current Behavior

A blood particle was mistakenly replaced with a fire particle.

## Steps to reproduce

Eat as an herrerasaurus. Notice the flames on the ground. ( https://gfycat.com/GaseousDistinctHog )

## Build Information

> **Game Version:** 0.1.51.8

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Hmm. I do think those are actually blood drops hitting the ground, they're just appearing a little over-bright for some reason. Reading the description I was expecting a flamethrower out of its mouth :P

**Comment by Hypno123** [comment]
Fixed in 0.1.52.1
