### ISSUE TITLE
Avaceratops' camera is too close.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#499]
## Expected Behavior

Its camera should be further away to allow it to see more things.

## Current Behavior

It is zoomed in too much. Not so much of a problem for the Juvenile Avaceratops.
( https://gfycat.com/HospitableMediocreImperialeagle )
The problem is more easily seen if you then compare it to any other dinosaur.

## Steps to reproduce

Spawn in as an avaceratops. Notice how close the camera is to your dinosaur, and how you can't zoom out all that far at all.

## Build Information

> **Game Version:** 0.1.51.9 (Also present in public branch)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Revision 3055- camera position has been pulled further back for adult Avaceratops. It's still close but not suffocatingly so.
