### ISSUE TITLE
Possible to create nests on the ocean surface of V3

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#502]
## Expected Behavior

It should not be possible to create a nest under water of any kind.

## Current Behavior

It is possible to create a nest on the surface of the ocean at the point just before your character begins swimming.

![image](https://user-images.githubusercontent.com/30550499/50591325-f9bf9680-0e86-11e9-8e26-b57f17afd5af.png)

## Steps to reproduce

1. Be an adult female creature.
2. Go to the ocean on V3.
3. Enter the water and press B just before your character begins swimming.

## Build Information

> **Game Version:** 0.1.51.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.52.1
