### ISSUE TITLE
Juvi Maia's friendly roar doesn't use the full body animation.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#503]
## Expected Behavior

Juvi maia's friendly roar to make it move its whole body, like the adult maia.

## Current Behavior

Juvi maia's body freezes up except for its head when it friendly roars.

## Steps to reproduce

Be a juvi maia, press 2 on your keyboard, notice how most of your body is frozen while the animation plays.

## Build Information

> **Game Version:** 0.1.51.9 

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
