### ISSUE TITLE
Dinosaurs can jump while building nest

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#505]
## Expected Behavior

Players should not be able to jump while performing the nesting animation.

## Current Behavior

Players can jump while building their nests, if playing as a species that can jump (Utah, Austro, Dryo and Galli.)

![image](https://user-images.githubusercontent.com/30550499/51064452-9efd0c00-15f7-11e9-963e-93a91dd5c9a1.png)

Similar problem to #491 

## Steps to reproduce

1. Spawn as one of the before mentioned species (adult female).
2. Press B to place a nest.
3. Begin jumping while the nesting animation plays.

## Build Information

> **Game Version:** 0.1.51.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Correction: he previously fixed #491 (scenting while building nest). This is now fixed in 0.1.52.1

**Comment by foszor** [comment]
FINAL CORRECTION: Ignore my previous comments, this has been fixed in 0.1.52.1
