### ISSUE TITLE
Chat window can be interacted with while escape menu is open

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#506]
## Expected Behavior

Players should not be able to click on the chat window while the escape menu is open.

## Current Behavior

The chat window can be interacted with while the escape menu is open. This can cause issues while trying to use the escape menu as you may instead click on the chat rather than logging out etc.

## Steps to reproduce

1. Spawn in.
2. Type in the chat for the window to appear.
3. Press escape to open the escape menu.
4. Click on the chatbox or one of the windows.

## Build Information

> **Game Version:** 0.1.51.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.52.1

**Comment by RagdollZombie** [comment]
Reaccuring in 0.1.53.3. The type box still works, Hover over it till you get the typing symbol. and lets you type/enter text.
