### ISSUE TITLE
Allosaurus Eating anim produces fire/spark particles

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#507]
## Expected Behavior

Blood particles to appear during eating animation

## Current Behavior

The particle effects and behavior seen during the eating seem to be fire, or sparks.

## Steps to reproduce

1) Spawn as an adult Allo
2) Find any food source
3) Eat and observe

https://youtu.be/CmgviX9Tg9w

## Build Information

> **Game Version:** 0.1.51.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Similar to #497 

Seems that some of the particle effects are just too bright. @dinosauriac Would it be useful to go through each species to look for this issue or would a change to one fix them all?

**Comment by Hypno123** [comment]
Fixed in 0.1.52.1
