### ISSUE TITLE
Once dead,Juvenile parasaurolophus Instantaneously turns into a carcass.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#51]
## Expected Behavior

Expected  juvenile parasaurolophus to turn into a ragdoll once dead, and into a carcass later on.

## Current Behavior

Once dead, juvenile parasaurolophus Instantaneously turns into a carcass.

This video shows it off :
https://www.youtube.com/watch?v=9ZOb8gNomLg&feature=youtu.be

## Steps to reproduce

-Select anything able to kill juvenile parasaurolophus.
-Find a juvenile parasaurolophus.
-Kill it.
-Notice that it Instantaneously turns into a carcass.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1850359/TheIsle.log)

> **Game Version:** 0.1.35.2 ( development )

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.6
