### ISSUE TITLE
Cliff face rocks collision allows players to walk above them

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#510]
## Expected Behavior

Players should not be able to walk above the rocks.

## Current Behavior

The collision for the large cliff face rocks allow players to "float" above them.

![image](https://user-images.githubusercontent.com/30550499/51281163-8b77e980-19d9-11e9-864e-a8a226744298.png)

## Steps to reproduce

1. Spawn in.
2. Navigate to the large ravine connected with the pipe.
3. Walk on the rocks on the cliff faces.
4. Notice that you can walk on them much higher than they appear.

## Build Information

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in the next build.
