### ISSUE TITLE
Water sources below the map disallow burrows to be made

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#511]
## Expected Behavior

There should be no water sources below the map preventing the burrows to be made other than the ocean, lakes and rivers.

## Current Behavior

There are large stretches of water sources below V3 that prevent burrows from being created (to prevent burrows being made in water.) This is most noticeable around the dockyard/swamp where the land is low and almost touches said water sources.

![image](https://user-images.githubusercontent.com/30550499/51281305-e8739f80-19d9-11e9-996b-0ea2cff2d37a.png)

## Steps to reproduce

1. Spawn as Psittacosaurus.
2. Navigate to a location where the land is low and almost touching the water source beneath the map.
3. Attempt to place a burrow and be unable to.

## Build Information

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
This is purely a map design issue. It's possible to reduce the depth of the burrows but at low altitudes near the large water sources it'll still happen
