### ISSUE TITLE
Pressing the create burrow button while in water allows you to walk on the water source surface

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#513]
## Expected Behavior

Players should not be able to walk on the surface of water sources by pressing the create burrow button.

## Current Behavior

Players can currently walk on the surface of water sources by pressing the create burrow button.

https://www.youtube.com/watch?v=rpBPRcCuzcM

## Steps to reproduce

1. Spawn as Psittaco.
2. Find a water source.
3. Begin swimming.
4. Press the create burrow button and begin walking on the surface.

## Build Information

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.52.1
