### ISSUE TITLE
Relogging with an active burrow causes the burrow to become non-interactive

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#515]
## Expected Behavior

Relogging should not cause a burrow to become non-interactive. It should either collapse when the player leaves or allow them to continue interacting with it when they rejoin. The former is preferable.

## Current Behavior

Relogging causes an active burrow to become non-interactive. The burrow will remain in the map and allow the player to create an entirely new burrow.

https://www.youtube.com/watch?v=iORfXycRYLk

## Steps to reproduce

1. Spawn as Psittaco.
2. Place a burrow.
3. Relog.
4. Be unable to interact with the burrow.
5. Place another burrow.

## Build Information

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Dedicated

**Comment by foszor** [comment]
Fixed in 0.1.52.1
