### ISSUE TITLE
Ragdolls fall through burrows

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#516]
## Expected Behavior

Ragdolls should not fall through burrows if we intend for small carnivores to enter them and kill the inhabitants.

## Current Behavior

Ragdolls currently fall through burrows when a player is killed. Should the ragdoll decay and turn to a corpse, the corpse will appear inside the burrow.

## Steps to reproduce

1. Spawn as Psittaco.
2. Place a burrow.
3. Die inside the burrow.
4. Go back to the burrow and look for your ragdoll - it has fallen through the map.
5. Wait until the corpse spawns.

## Build Information

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
This was a burrow design issue, the test burrow I created didn't have collision for ragdolls. Burrows should have custom static meshes and a better design. I've fixed this issue in my test burrow, so fixed in 0.1.52.1
