### ISSUE TITLE
Empty Thirst/Hunger bars display as kinda full when logging in with empty hunger/thirst

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#518]
## Expected Behavior

if you have 0% hunger and/or thirst, the hunger and thirst popups should display as empty

## Current Behavior

if you login with 0% hunger or water or both, the hunger/water gauges that appear upon spawning in are shown as being about 25% filled.
Screenshot:
https://media.discordapp.net/attachments/452971041581432854/535725212315156490/unknown.png?width=1082&height=596

## Steps to reproduce

Get empty hunger or water, or both.
Logout
Log back in

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.51.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.1
