### ISSUE TITLE
Juvi Sucho starts with 125 n bite force and 2 tons weight

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#519]
## Expected Behavior

juvi sucho should start out with a regular amount of damage

## Current Behavior

juvi sucho can 1 shot any other juvi right outta spawn, starts with 125 N

## Steps to reproduce

spawn as juvi sucho and go nuts

note: it also starts out with about 2 tons of weight, idk if thats intended or not but it probably isnt so im listing it here too

https://cdn.discordapp.com/attachments/401465476661641217/537240146274287617/unknown.png
pic from The Ninja Scout

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.3
