### ISSUE TITLE
Able to crouch-walk with broken leg

### ISSUE THREAD

**Issue by Souretsu** [TheIsleGame/bugs#52]
## Expected Behavior

Players should be forced into a limp animation when moving with a broken leg.

## Current Behavior

Under certain circumstances it is possible to crouch-walk with your leg broken, causing distorted gameplay.

Example shown in this video: https://youtu.be/ll4ahuA4TZs

## Steps to reproduce

Crouch-walk off of a ledge high enough to break your leg without killing you.  You should now be able to continue crouch-walking until you toggle out of it.

## Build Information
version 0.1.35.2 (dev)
System: Windows 10
Role: Client.

**Comment by foszor** [comment]
Fixed in 0.1.38.6
