### ISSUE TITLE
AI infinite spawning locations

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#520]
## Expected Behavior

a should spawn around hungry carnivore players, and maybe in certain areas if intended.

## Current Behavior

AI seems to spawn endlessly in certain areas

## Steps to reproduce

go to this area:
https://steamuserimages-a.akamaihd.net/ugc/963109385836647905/87C91C2EC37C73E0F65E7BEC6692A27CF5133CAC/

can also go to https://cdn.discordapp.com/attachments/401560830312841227/537234064122576896/unknown.png
^ image from the ninja scout

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.3
