### ISSUE TITLE
Fake Limping does not work anymore.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#521]
## Expected Behavior

Fake Limping to work when you press G

## Current Behavior

It doesn't work.

## Steps to reproduce

Press G, no limping animation will play. You'll still be able to run and do everything you would normally be able to do.

## Build Information.

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Intended.
