### ISSUE TITLE
Fall Damage is no longer applied when falling on the ground.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#522]
## Expected Behavior

Fall damage to work correctly and apply damage / kill the dinosaur if it falls for too long and lands on the ground.

## Current Behavior

When you fall and don't land on water, nothing will happen to you. Falling on water still applies damage, however.

## Steps to reproduce

Be any dinosaur, fall off something and don't land in the water. No fall damage is applied.

## Build Information
> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.3
