### ISSUE TITLE
Juvi pachy shows up as Adult Utah in insert menu

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#523]
## Expected Behavior

juvie pachhy should show as their respective age and dino in the insert menu

## Current Behavior

currently juvi pachy shows as adult utah in its insert menu

## Steps to reproduce

be a juvi pachy and press insert

## Build Information

> **Game Version:** 0.1.52.1

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
I've fixed the image references, but for some reason the Pachy still wants to identify as a raptor.

**Comment by Hypno123** [comment]
Updated report to reflect current patch.

**Comment by dinosauriac** [comment]
Fixed next build. Blueprints are using an.. alternative.. spelling of the species name, so the character menu wasn't finding the correct images.
