### ISSUE TITLE
Hatchling Pachy and Sucho cannot eat from their parents' nest.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#524]
## Expected Behavior
The hatchling suchomimus and pachycephalosaurus should be able to eat from their parent's nest.

## Current Behavior
The hatchling pachy and suchomimus are unable to eat from nests.

## Steps to reproduce
Be nested in as an pachy or sucho, notice how you cannot eat from nests.
Or
Simply spawn in as an hatchling pachy or sucho and interact with nests, see how your only option is to give food.

## Build Information

> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Emanthealmighty** [comment]
Removed the part about the hatchling pachy being able to sniff, as it is fixed next patch.

**Comment by Emanthealmighty** [comment]
Updated the issue, removing the fixed issues.
Hatchling Pachy and Sucho still count as adults, so they are unable to eat from their parents' nest.
(Asset age says they're adults and that they're also capable of mating)
This problem is also present in their juvenile forms as well, though it doesn't affect the gameplay as much.

**Comment by Hypno123** [comment]
Fixed in 0.1.52.4
