### ISSUE TITLE
Herbivores can smell carcasses.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#526]
## Expected Behavior

Herbivores should not be able to smell carcasses.

## Current Behavior

Herbivores can smell carcasses.

## Steps to reproduce

Play as an herbivore dinosaur in DV testlevel, sniff and notice how you can smell carcasses.

## Build Information
> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Herbivores smelling carcasses is intended so that they know to stay away from that area.
