### ISSUE TITLE
Cerato,Giga,Sucho and Pachy body locations can't be focused during skin customization.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#527]
## Expected Behavior

User to able to focus on Cerato,Giga,Sucho and Pachy body locations while customizing skin.

## Current Behavior

User can't focus on any of Cerato,Giga,Sucho and Pachy body locations (Body,Head,Tail) while customizing skin.

Screenshot evidence: 

![](https://cdn.discordapp.com/attachments/376420384637190146/537301880703811604/unknown.png)

## Steps to reproduce

-Select any of the dinosaurs mentioned before.
-Click the location drop-down menu while customizing skin.
-Notice that the only option is "None"

## Build Information

> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Added in the next build.
