### ISSUE TITLE
Juvenile Ceratosaurus has two attacks.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#528]
## Expected Behavior

The Juvenile Ceratosaurus to only have one attack, like all the other carnivores.

## Current Behavior

The Juvenile Ceratosaurus has two attacks, one performed with mouse1 and the other one with mouse2. They both deal the same damage, and while you are sprinting, you can only use the mouse2 attack.

## Steps to reproduce

Spawn as a juvenile ceratosaurus, press mouse1 and then mouse2, see how you attack by pressing both, while it should only be with mouse1.
Start sprinting, see how you can only attack with mouse2 now.

## Build Information

> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
