### ISSUE TITLE
Juvenile Gallimimus jitters during scent animation

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#529]
## Expected Behavior

Juvenile Gallimimus scent animation to play properly,no jittering 

## Current Behavior

Juvenile Gallimimus jitters during scent animation.
Video Evidence:
https://i.gyazo.com/9ae51e4e40cd6881678155d735f77ac2.mp4
## Steps to reproduce

-Select Juvenile gallimimus.
-Use scent.

## Build Information

> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Added to #501
