### ISSUE TITLE
Hatchling Pachycephalosaurus can use scnet

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#530]
## Expected Behavior

Hatchling Pachy to be unable to use scent,just like other hatchlings

## Current Behavior

Hatchling Pachy is capable of using scent,unlike any other hatchlings
Video evidence: https://youtu.be/ZqOHE_D2Qj4

## Steps to reproduce

-Spawn in as Hatchling pachy / Get nested as a pachy
-Use scent

## Build Information

> **Game Version:** 0.1.52.2 

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
