### ISSUE TITLE
Nest Icon cannot be toggled off.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#532]
## Expected Behavior

The in-game menu option regarding nest icons should allow you to disable the nest icon when it's unticked.

## Current Behavior

The nest icon will stay visible for all the time the nest is in the world, even if destroyed. It must disappear fully for the nest icon to go away.

## Steps to reproduce

Build a nest as any dinosaur
Untick the "show nest icons" option
Notice how the icon does not disappear.
## Build Information

> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.8
