### ISSUE TITLE
Dinosaurs can crouch while building nests.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#539]
## Expected Behavior

Dinosaurs to be unable to crouch while building nests.

## Current Behavior

Dinosaurs can crouch while building nests.
Exclusive to dinosaurs capable of crouching,obviously.
Sucho/Cerato aren't affected because they lack nest building animation.
Easier to notice as carnivores due to ambush.

Video evidence: https://youtu.be/1ddVTExquAE

Tested on both Listen and Dedicated Servers.
## Steps to reproduce

-Select any female dinosaur capable of crouching.
-Build a nest and crouch while nest is being built.
-Notice that camera angle will change (as of current build) and ambush will be triggered on carnivores.
-Also notice that once the nest is built,you dinosaur will automatically change to crouch animation.

## Build Information

> **Game Version:** 0.1.52.2

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
This can also be done while eating/drinking. I personally don't see this as an issue, as it allows players to crouch faster from those actions, rather than having to wait for the animation to play entirely.
