### ISSUE TITLE
New survival dinosaurs spawning with half hunger and half thirst

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#54]
## Expected Behavior

On Survival,expected all juvenile dinosaurs to spawn with half hunger/half thirst or full hunger/full thirst.

## Current Behavior

On survival, Juvenile Giga, Para, Galli and Trike spawn with half hunger/half thirst. Meanwhile juvenile Rex, Utah and Carno spawn with full hunger/full thirst.

## Steps to reproduce

-Select any of the new survival juveniles.
-Spawn.
-Notice that you have half hunger/half thirst, as opposed to full.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1858085/TheIsle.log)

> **Game Version:** 0.1.35.2 ( development ) 

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.35.6
