### ISSUE TITLE
Hatchling and juvenile Trike uses adult eating sound

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#540]
## Expected Behavior

Hatchling and juvenile Trike should use eating sounds appropriate for their size.

## Current Behavior

Hatchling and juvenile Trike uses the adult eating sounds.

## Steps to reproduce

1. Spawn in as juvenile or hatchling Trike.
2. Find an edible bush.
3. Eat and listen to the adult sound produced.

## Build Information

> **Game Version:** 0.1.52.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed next build.
