### ISSUE TITLE
Brachiosaurus' skin isn't applied to the model correctly

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#543]
## Expected Behavior

The skins for the Brachiosaurus (both male and female) should look normal.

## Current Behavior

The skins for the Brachiosaurus (both male and female) are distorted on the model in client sessions.

![image](https://user-images.githubusercontent.com/30550499/51951143-58971200-242b-11e9-894a-fc6f8e4e8f8e.png)

**The male works as intended in a dedicated session.**

## Steps to reproduce

1. Spawn as Brachiosaurus.
2. Look at your skin.

## Build Information

> **Game Version:** 0.1.52.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
After further testing, this seems to be an issue for both genders in a client hosted session but the male works fine in a dedicated session. I've updated the report to reflect that.

**Comment by ikarop** [comment]
Fixed in the next build.
