### ISSUE TITLE
Adult Pachy nests in Juvi Pachies instead of hatchlings.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#544]
## Expected Behavior

The adult pachycephalosaurus should be nesting in hatchlings when it invites someone to join their nest as an egg.

## Current Behavior

When you are nested in by a pachy, you'll spawn in as a juvi pachy.

## Steps to reproduce

Be nested in as a pachy, notice how you are not an hatchling, but a juvie.

## Build Information

>**Game Version**: 0.1.52.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.4
