### ISSUE TITLE
Spamming Enter after choosing a dinosaur will cause it to clone.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#545]
## Expected Behavior

Spamming Enter after clicking confirming a selected dinosaur should not spawn more dinosaurs in the preview area.

## Current Behavior

It is still possible to cause https://github.com/TheIsleGame/bugs/issues/525 to happen by spamming enter after pressing confirm.

## Steps to reproduce

Select a dinosaur, press enter to confirm your choice and start spamming it. Notice how more than one dinosaur is present in the preview area.

## Build Information
> **Game Version:** 0.1.52.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.52.4
