### ISSUE TITLE
Juvie Galli red hunger icon does not show

### ISSUE THREAD

**Issue by MortenSilver** [TheIsleGame/bugs#549]
## Expected Behavior

Red hunger icon should indicate low - 0 hunger.

## Current Behavior

Red hunger icon does not show up at all, even when taking hunger damage.

## Steps to reproduce

Log in as juvie Galli and wait to starve.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.52.3

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Red hunger prompt will only show when static HUD is disabled.
Here it is working for the juvenile Galli:

![image](https://user-images.githubusercontent.com/30550499/52146315-4f8c8780-265b-11e9-804b-f3ecd7cb2212.png)
