### ISSUE TITLE
Triceratops cannot nest

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#55]
## Expected Behavior

The baby should come out of the nest when they hit the nest button.

## Current Behavior

The baby currently never spawns in:

![image](https://user-images.githubusercontent.com/30550499/38100251-c905a5a4-3374-11e8-8892-fa885220d1fe.png)

## Steps to reproduce

1. Be female adult trike.
2. Place a nest.
3. Send nest invite to other player.
4. Have them press the nest button and they will never actually spawn.

## Build Information

> **Game Version:** 0.1.35.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.4

**Comment by Hypno123** [comment]
Still apparent in 0.1.35.4

**Comment by Paleocolour** [comment]
This should be fixed in the next patch. There was an error where the "growth" of the hatchling was set to 0.0.
