### ISSUE TITLE
Giga subadult skin is pure white when "Effects" are set to low on dedicated servers

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#556]
## Expected Behavior

Giga subadult should not be pure white when effects are set to low.

## Current Behavior

Giga subadult shows as pure white when effects are set to low.

![image](https://user-images.githubusercontent.com/30550499/52545869-cb50a780-2db2-11e9-953a-3a9abeeca1ae.png)

Seems to only happen on dedicated servers.

## Steps to reproduce

1. Set effects to low.
2. Enter a server.
3. Select subadult Giga.
4. Spawn in and look at your skin.

## Build Information

> **Game Version:** 0.1.52.5

> **Operating System**: Windows

> **Network Role**: Dedicated

**Comment by ikarop** [comment]
Fixed in the next build.
