### ISSUE TITLE
Giga subadult receives no scar decals when damaged

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#557]
## Expected Behavior

Giga subadult should have scar decals applied when damaged.

## Current Behavior

Giga subadult currently does not have scar decals applied when damaged.

![image](https://user-images.githubusercontent.com/30550499/52547067-6306c380-2dbc-11e9-8a5f-7bafa3d16af6.png)

## Steps to reproduce

1. Spawn as a Giga subadult.
2. Become damaged.
3. Notice that despite the damage, no scar decals appear on your character.

## Build Information

> **Game Version:** 0.1.52.5

> **Operating System**: Windows

> **Network Role**: Client

**Comment by ikarop** [comment]
Fixed in the next build.
