### ISSUE TITLE
Can no longer host an offline server.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#559]
## Expected Behavior

Pressing "Confirm" in the Host menu accessible through the server selection screen to put you into a private offline server.

## Current Behavior

Upon pressing confirm, the game just freezes at a black screen, without ever transitioning into the loading screen.
https://gfycat.com/MisguidedQuestionableIcterinewarbler

## Steps to reproduce

Press "Play" after opening the game.
Press "Host".
Select any setting you want till the "Confirm" button lights up.
Press "Confirm".
The screen turns black, and absolutely nothing happens from there.

## Build Information

> **Game Version:** 0.1.52.6 ( Been an issue since Patch 0.1.52.4 )

> **Operating System**: Windows

> **Network Role**: Client

## Other Information
This is more than likely not a reproducible bug, but I really do need help to fix it, it's seriously hindering my ability to test things.

My system specs:
Processor Information:
    CPU Vendor:  GenuineIntel
    CPU Brand:  Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    CPU Family:  0x6
    CPU Model:  0x9e
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3600 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    AES:  Supported
    AVX:  Supported
    CMPXCHG16B:  Supported
    LAHF/SAHF:  Supported
    PrefetchW:  Unsupported

Operating System Version:
    Windows 7 (64 bit)
    NTFS:  Supported
    Crypto Provider Codes:  Supported 311 0x0 0x0 0x0

Video Card:
    Driver:  NVIDIA GeForce GTX 1060 3GB
    DirectX Driver Name:  nvd3dum.dll
    Driver Version:  25.21.14.1881
    DirectX Driver Version:  25.21.14.1881
    Driver Date: 1 30 2019
    OpenGL Version: 4.6
    Desktop Color Depth: 32 bits per pixel
    Monitor Refresh Rate: 60 Hz
    DirectX Card: NVIDIA GeForce GTX 1060 3GB
    VendorID:  0x10de
    DeviceID:  0x1c02
    Revision:  0xa1
    Number of Monitors:  1
    Number of Logical Video Cards:  1
    No SLI or Crossfire Detected
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 1920 x 1080
    Primary Display Size: 26.65" x 15.00" (30.55" diag)
                                            67.7cm x 38.1cm (77.6cm diag)
    Primary Bus: PCI Express 16x
    Primary VRAM: 3071 MB
    Supported MSAA Modes:  2x 4x 8x 

Sound card:
    Audio device: Altoparlanti (3- USB Audio Devi

Memory:
    RAM:  16314 Mb

**Comment by Hypno123** [comment]
Isn't an issue for me. It's more than likely that we're cutting out listen server support in favor of dedicated servers anyway, due to the amount of development time they would take to continue.

Use the testing server for testing.
