### ISSUE TITLE
Humans can't enter combat stance

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#56]
## Expected Behavior

Hitting V should enter the humans into combat stance (not sure if this is still wanted? Deathly addition.)

## Current Behavior

Hitting V currently brings up the dinosaur voice wheel, rather than entering into combat stance. This prevents humans from being able to shoot their guns/bows.

**EDIT:** You *can* change your voice wheel keybind to allow the combat stance bind to work again.

## Steps to reproduce

1. Spawn as human.
2. Hit V to try to enter combat stance.
3. Be met with dinosaur voice wheel instead.

## Build Information

> **Game Version:** 0.1.35.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
An update on this: They _can_ enter combat stance, it's just that the default button is the same as for voice wheel.

**Comment by looterz** [comment]
Closing this in preparation for the human rewrite.
