### ISSUE TITLE
Toggle Hud custom keybind doesn't work.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#560]
## Expected Behavior

Pressing the key bound to "Toggle Hud" should make the HUD disappear.

## Current Behavior

Upon pressing the key bound to "Toggle Hud", the HUD does not disappear.
The only way to make the HUD disappear is by using the standard keybind.

## Steps to reproduce

Set the keybind to any other key.
Press the button bound to the command "Toggle Hud"
See how the HUD doesn't disappear.

## Build Information

> **Game Version:** 0.1.52.6

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
After further testing, it seems that the toggle HUD keybind doesn't function at all.

Ctrl + H is currently the only way to toggle HUD. The keybind has no effect on this.

**Comment by foszor** [comment]
While designing the new key binding system I didn't realized we had combination action keys (holding Shift, Ctrl, Alt, Cmd). If its something we want to continue using I'll have to look further into it.

**Comment by foszor** [comment]
Combination inputs have been disabled in the next build and ToggleHUD default key will be F10
