### ISSUE TITLE
Allosaurus' old versions are still playable.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#561]
## Expected Behavior

Allosaurus Old and Allosaurus Juvenile Old should not be playable in sandbox.

## Current Behavior

Allosaurus Old and Allosaurus Juvenile Old are playable in sandbox.

## Steps to reproduce

Play in sandbox.
Notice how you can select the abovementioned dinosaurs.

## Build Information

> **Game Version:** 0.1.52.6

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed next patch.
