### ISSUE TITLE
Crouching in the Radio Tower Water (V3) makes some Dinos go Below Ground

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#563]
## Expected Behavior

crouching in the water at Radio Tower should make you just crouch down normally

## Current Behavior

currently, if you crouch when in the water supply at V3's radio tower (the tower that lights up all the time), your model glitches and sinks below the ground

screenshot:
https://media.discordapp.net/attachments/452971041581432854/546017951975866368/unknown.png?width=1058&height=596

List of dinos it happens to: Juvi dryo, Juvi gali, juvi dilo

## Steps to reproduce

Go to the radio tower (-592 lat, -137 long), get in the water, and crouch.

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.52.6

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
This will be irrelevant when the map is updated next, water source has been swapped out for a more natural one instead of a miniature paddling pool.
