### ISSUE TITLE
Dryosaurus Character Menu Has an Extra Dryo Growth Outline that gets Cut Off

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#564]
## Expected Behavior

Dryo character menu (also known as insert menu) should not display cut-off images

## Current Behavior

Currently, the dryo character menu has an extra dryo picture (the pictures used to show what growth stage you;re at) that gets cut off so its only a head with an open mouth

Picture: https://media.discordapp.net/attachments/452971041581432854/546032802248916993/unknown.png?width=1081&height=595

## Steps to reproduce

Be a dryo and press insert

## Build Information

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.52.6

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Fixed.
