### ISSUE TITLE
Carnotaurus Adult and Juvenile don't take fall damage.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#568]
## Expected Behavior

Carnotaurus Adult and Juvenile should be able to break their legs.

## Current Behavior

They can't.

## Steps to reproduce

Be a carnotaurus, fall from heights that would normally kill or injure similiar sized creatures.
Watch as nothing happens.

## Build Information
> **Game Version:** 0.1.52.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
They _are_ able to break their legs, the threshold is just too high for them at the moment. I'll leave this up until it gets adjusted.

**Comment by dinosauriac** [comment]
I think this was a recent adjustment done as a temporary measure due to the fall damage / damage threshold being multiplied by velocity, so if you went off a one foot drop at full speed as a Carno you might become crippled or outright die.

**Comment by Hypno123** [comment]
Fixed in 0.1.52.8
