### ISSUE TITLE
Growing removes ownership of a nest.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#569]
## Expected Behavior

Growing to the next life stage should not disown your current nest, requiring you to build a new one.

## Current Behavior

Growing to the next life stage removes ownership of your nest.

## Steps to reproduce

Be a 1.0 subadult dinosaur
Make a nest
Grow
Notice how you don't own the nest anymore.

## Build Information
> **Game Version:** 0.1.52.7

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.52.8
