### ISSUE TITLE
Entering a server will make your cursor disappear.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#573]
## Expected Behavior

When connecting to a server, your mouse cursor should stay on screen, so you can press the required buttons to correctly play.

## Current Behavior

When connecting to a server, your cursor will disappear in-game, making it impossible to press any of the buttons required to play for those who do not know how to manually make the cursor reappear.
This also happens when logging in a server where you already have a living dinosaur.

## Steps to reproduce

Connect to a server.
Your mouse cursor will not be present on screen.

## Build Information

> **Game Version:** 0.1.52.8

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
This only affects servers with a MotD enabled.

**Comment by Emanthealmighty** [comment]
Problem is still present as of 0.1.52.9 . This time it's not related to the MoTD, but rather just anytime you're in the character selection screen.

**Comment by Hypno123** [comment]
Users still reporting in 0.1.53.0. Same issue as above.

**Comment by Hypno123** [comment]
Fixed in 0.1.53.1
