### ISSUE TITLE
Adult Gallimimus can slide when attacking.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#574]
## Expected Behavior

The adult gallimimus shouldn't be able to move while attacking (when not running), like its juvenile growth stage.

## Current Behavior

The adult gallimimus can move while attacking, causing it to slide if it performs the full body attack animation.
Attacking while standing still and then moving also works.

## Steps to reproduce

Be an adult gallimimus, walk / trot around and notice how you can attack while doing so.

## Build Information

> **Game Version:** 0.1.52.8

> **Operating System**: Windows

> **Network Role**: Client

## Notes
If you make the adult gallimimus attack the same way the juvenile gallimimus does (stopping every single time you attack until the animation is over regardless if you are sprinting or not), then definitely buff its damage and/or weight to make up for all the time it spends standing still when attacking.

**Comment by dinosauriac** [comment]
Fixed next build.
