### ISSUE TITLE
Hatchling galli and dryo can jump too high.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#575]
## Expected Behavior

The hatchling galli and dryo shouldn't be able to jump as high as they currently can, or they shouldn't be able to jump at all, like the hatchling pachy.

## Current Behavior

The hatchling galli and dryo can jump too high, which looks unnatural considering they're _hatchlings_ who just came into the world.

## Steps to reproduce

Be an hatchling galli/dryo, jump, notice how they can jump too high.

## Build Information

> **Game Version:** 0.1.52.8

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Their jump height/velocity is reduced with the next update.
