### ISSUE TITLE
Growing while using night vision doesn't remove the glowing eyes effect on dinosaurs.

### ISSUE THREAD

**Issue by Emanthealmighty** [TheIsleGame/bugs#576]
## Expected Behavior

When growing to the next stage while using night vision, other dinosaurs' eyes shouldn't appear to glow anymore until you turn on your night vision again.

## Current Behavior

When growing to the next life stage while using night vision, every dinosaur's eyes will keep glowing even though you don't have night vision on anymore. The eyes will keep glowing forever (even during the day) until you turn on night vision after growing or relog.

## Steps to reproduce

Grow to the point where you can advance to the next life stage as any dinosaur.
Turn on night vision.
Grow to the next life stage.
Notice how everything's eyes still glow, even if your night vision has been turned off.

## Build Information

> **Game Version:** 0.1.52.8

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Tried to keep night vision persistent during growth but is currently too complicated while the process is a hybrid of blueprints and C++ and growth is server side while night vision is client side. For now I just turned it off just before growth to fix the glowing eyes. Fixed in 0.1.52.9
