### ISSUE TITLE
Nests can be placed while entering/exiting a burrow

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#579]
## Expected Behavior

Players should be unable to place nests while entering/exiting a burrow.

## Current Behavior

Players can build nests while entering/exiting a burrow. The nest however will never appear inside the burrow.

![image](https://user-images.githubusercontent.com/30550499/53839245-efa53b80-3f8e-11e9-8a8c-38eb3f068bbd.png)

_The above picture shows an adult female Dryo mid nest building animation while inside the burrow._

## Steps to reproduce

1. Spawn as an adult female Dryo.
2. Press RMB to dig a burrow.
3. Press RMB to enter the burrow and push B to build a nest as you enter.

## Build Information

> **Game Version:** 0.1.52.9

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.53.0
