### ISSUE TITLE
Hatchling Giga uses adult eating sound

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#58]
## Expected Behavior

The hatchling Giga should have eating sounds appropriate for its size.

## Current Behavior

The hatchling Giga currently uses the adult eating sound.

## Steps to reproduce

1. Spawn as hatchling giga in sbox or get nested on survival.
2. Eat a corpse.
3. Listen to the adult eating sound.

## Build Information

> **Game Version:** 0.1.35.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Paleocolour** [comment]
Fixed in revision 510.
