### ISSUE TITLE
Tear in V3 map

### ISSUE THREAD

**Issue by Kingjaffad** [TheIsleGame/bugs#582]
## Expected Behavior

The terrain should not feature any gaps in the world.

## Current Behavior

There exists a tear in the terrain, it appears to be too small to actually fall through.

## Steps to reproduce

The tear can be visibly seen at these coordinates. (Lat: -353,893.219 Long: 277,700.906 Alt: -63,150.348)

## Build Information

> **Game Version:**  0.1.52.9

> **Operating System**: Windows 7

> **Network Role**: Client
![20190309002303_1](https://user-images.githubusercontent.com/27590871/54063422-3485d800-4204-11e9-88ff-473dda1c8d02.jpg)
![20190309002313_1](https://user-images.githubusercontent.com/27590871/54063425-38b1f580-4204-11e9-8a89-0ecec86fdaa1.jpg)

**Comment by Hypno123** [comment]
Should be fixed in 0.1.53.0
