### ISSUE TITLE
Hole in rock mesh

### ISSUE THREAD

**Issue by Kingjaffad** [TheIsleGame/bugs#583]
## Expected Behavior

Rock mesh should be be fully visible from all angles.

## Current Behavior

A large tear can be seen in the side of the rock.

## Steps to reproduce

Simply head to these coordinates. (Lat: -151,140.219 Long: 201,311.094 Alt: -57,804.594)

## Build Information

> **Game Version:** 0.1.52.9

> **Operating System**: Windows

> **Network Role**: Client
![20190309235732_1](https://user-images.githubusercontent.com/27590871/54078836-aa9f4300-42c7-11e9-80b5-64ccd4265403.jpg)
![20190309235736_1](https://user-images.githubusercontent.com/27590871/54078838-ad019d00-42c7-11e9-8be2-993b18494d3e.jpg)

**Comment by Hypno123** [comment]
Should be fixed in 0.1.53.0
