### ISSUE TITLE
Nest invite menu can be opened an infinite number of times

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#585]
## Expected Behavior

Players should be unable to open the invite to nest menu while it is already open.

## Current Behavior

Players are currently able to open the invite to nest menu an infinite number of times by simply clicking the button while the menu is open.

https://www.youtube.com/watch?v=VDiktavQHf8

## Steps to reproduce

1. Be an adult female creature.
2. Place a nest.
3. Wait for an egg to be ready.
4. Click on the invite button.
5. When the invite to nest menu opens, simply click the button again.

## Build Information

> **Game Version:** 0.1.53.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
Should be fixed next build, will need testing.

**Comment by Hypno123** [comment]
Fixed in 0.1.53.0
