### ISSUE TITLE
Male creatures can place nests and gestate eggs

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#589]
## Expected Behavior

Male creatures should be unable to place nests and gestate eggs.

## Current Behavior

Male creatures can currently place nests and gestate eggs.

## Steps to reproduce

1. Spawn as a male adult creature.
2. Press B to place a nest.

## Build Information

> **Game Version:** 0.1.53.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.53.1
