### ISSUE TITLE
Tribal torch burns your own character

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#59]
## Expected Behavior

Jumping with the torch should not burn your character - they should hold it further away or do no damage to you.

## Current Behavior

Jumping, swimming, any animation that puts the torch close to the player's character causes the player to burn themselves to death.

## Steps to reproduce

1. Spawn as tribal.
2. Press 2 to get torch out.
3. Run and jump forward into your torch, burning your own character.

## Build Information

> **Game Version:** 0.1.35.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.4
