### ISSUE TITLE
All Allosaurus Life Stages have a Jittery Ankle

### ISSUE THREAD

**Issue by Blockomaniac** [TheIsleGame/bugs#591]
## Expected Behavior

Dinos shouldnt have shaky joints 

## Current Behavior

When any allosaurus (hatchling, juvi, adult) crouches, their ankle (left ankle if you are looking from the tail) will start to vibrate and shake around. Other ankle is fine. It also shakes a bit when getting up from resting.

## Steps to reproduce

Be any life stage allo, then crouch. It doesn't matter what surface you're on.

## Build Information 

Fill out the fields below to match the game that you experienced the bug on.
You can attach your `TheIsle.log` file from the games log directory to the report.

> **Game Version:** 0.1.53.0

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
This belongs in the animation issues master list.

**Comment by Hypno123** [comment]
This has been reported in #501
