### ISSUE TITLE
Hatchling Trike uses adult sound

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#60]
## Expected Behavior

The hatchling Triceratops should use baby sounds, not adult ones. (Needs generic hatchling call.)

## Current Behavior

The hatchling Triceratops currently uses the adult sound.

## Steps to reproduce

1. Spawn as hatchling Triceratops in sbox.
2. Press any of your call buttons (1-4) and listen to the adult sound.

## Build Information

> **Game Version:** 0.1.35.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Paleocolour** [comment]
Should be fixed as of Revision 496.
