### ISSUE TITLE
Voice wheel does not function

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#61]
## Expected Behavior

When selecting a call on the voice wheel, it should perform the selected call.

## Current Behavior

Selecting a call on the voice wheel does not perform the selected call. Nothing happens.

## Steps to reproduce

1. Spawn as any dinosaur.
2. Hit V for voice wheel.
3. Click and drag from the middle of the voice wheel to any of the calls.
4. Be disappointed when the call is not performed.

## Build Information

> **Game Version:** 0.1.35.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Blockomaniac** [comment]
also if you die with it open, it stays open on the respawn screen and you cant do anything

**Comment by foszor** [comment]
Fixed in 0.1.38.6
