### ISSUE TITLE
Entering spectator mode while resting on a nest incubates eggs

### ISSUE THREAD

**Issue by spiral-static** [TheIsleGame/bugs#613]
## Expected Behavior

When going into spectator mode while sitting on a nest as any dinosaur, eggs should not continue to incubate.

## Current Behavior

Sitting on a nest and then entering spectator mode will continue to incubate eggs.

## Steps to reproduce

1. Be an adult female dinosaur and lay a nest.
2. Press H (default key) to rest on the nest and incubate eggs.
3. Enter spectator mode with \ (default key) and observe that the eggs continue to incubate in spectator mode.

## Build Information

> **Game Version:** 0.1.53.3

> **Network Role**: Dedicated Server (The Isle Official US 1)

> **Operating System:** Windows 10

**Comment by foszor** [comment]
Entering spectator mode basically places your existing character in a non-damageable and invisible state, this result would be expected.
