### ISSUE TITLE
Triceratops juvenile deals no damage

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#62]
## Expected Behavior

Triceratops juvenile, though small, should deal damage.

## Current Behavior

Triceratops juvenile currently deals no damage.

## Steps to reproduce

1. Spawn as Trike juvie.
2. Attack another juvie.
3. Deal no damage.

## Build Information

> **Game Version:** 0.1.35.3 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.35.6
