### ISSUE TITLE
Juvenile Giga stats do not increase with growth

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#63]
## Expected Behavior

As you grow, your stats should increase as juvenile giga, like every other survival dinosaur.

## Current Behavior

The juvenile giga stats do not increase as it grows.

## Steps to reproduce

1. Spawn as juvenile Giga.
2. Open debug menu with Ctrl + Insert.
3. Wait for a growth tick and notice stats do not change.

## Build Information

> **Game Version:** 0.1.35.4

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.6
