### ISSUE TITLE
Parasaurolophus uses Shant headbutt sound

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#64]
## Expected Behavior

The Parasaurolophus should use a different headbutt sound to the Shantungosaurus.

## Current Behavior

The Parasaurolophus currently uses the Shantungosaurus headbutt sound.

## Steps to reproduce

1. Spawn as para.
2. Right click for headbutt.
3. Listen to Shant sound.

## Build Information

> **Game Version:** 0.1.35.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by dinosauriac** [comment]
This isn't really a bug / issue, plenty of dinosaurs share the same breaths and grunts. That said, the Para might not even *have* a headbutt considering the animation revisions going on currently, so would be getting new sounds anyway if/when the attack is replaced.
