### ISSUE TITLE
Growing to the next stage removes bleed

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#65]
## Expected Behavior

Growing to the next stage should not remove heal your bleeding level.

## Current Behavior

Pressing the growth button to the next stage removes any bleed that you may have - can prevent death.

## Steps to reproduce

1. Spawn as something.
2. Grow enough to progress to the next stage.
3. Have another player give your dinosaur bleed.
4. Grow to the next stage and heal the bleed.

## Build Information

> **Game Version:** 0.1.35.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.35.6
