### ISSUE TITLE
Adult Giga floats when crouching/resting

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#66]
## Expected Behavior

The adult Giga should not be floating when crouching or resting.

## Current Behavior

The adult Giga floats just above the ground when crouching or resting.

![image](https://user-images.githubusercontent.com/30550499/38142873-ff2a14be-3435-11e8-84a7-66e35e4f3f94.png)

## Steps to reproduce

1. Spawn as adult Giga.
2. Crouch/rest.
3. Look at your character floating above the ground.

## Build Information

> **Game Version:** 0.1.35.4 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by MortenSilver** [comment]
![image](https://user-images.githubusercontent.com/38515115/39166736-515a95d4-4759-11e8-90a7-2bce03378b95.png)

Had a screenie. Thought I'd throw it up here.

**Comment by Hypno123** [comment]
Added to #501

**Comment by Kingjaffad** [comment]
Still apparent in 0.1.53.3, albeit not quite as noticeable.

https://www.youtube.com/watch?v=XvLRSkIW4tc

**Comment by Hypno123** [comment]
@Kingjaffad This was added to #501 to save space on the tracker. It will remain closed here.
