### ISSUE TITLE
Logging out in spectator mode doesn't save to DB

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#67]
## Expected Behavior

Player location, growth etc should all save, regardless of if they are in spectator or not.

## Current Behavior

Logging out while in spectator will reset your character to where you last logged out, meaning any new growth and/or location will be lost. 

## Steps to reproduce

1. Be an admin/dev.
2. Spawn as anything.
3. Grow up a little or move location.
4. Go into spectator with \
5. Log out then log back in to find you have been reset to where you last logged in or spawned.

## Build Information

> **Game Version:** 0.1.35.5 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.6

**Comment by looterz** [comment]
On further review, this isn't possible at the moment.
