### ISSUE TITLE
Footprints on ceiling

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#68]
## Expected Behavior

Stepping underneath a space with a low ceiling should not cause footprint decals to appear above the player.

## Current Behavior

Stepping underneath a space with a low ceiling causes footprint decals to appear above the player.

![image](https://user-images.githubusercontent.com/30550499/38156884-7fea7024-3479-11e8-9497-94b4290f073d.png)

## Steps to reproduce

1. Spawn as something small enough to fit under a low ceiling / cave.
2. Walk around.
3. Watch the footprint decals appear on a ceiling.

## Build Information

> **Game Version:** 0.1.35.5 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.35.6
