### ISSUE TITLE
Hatchling trike eating/drinking issues

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#70]
## Expected Behavior

The hatchling triceratops should have no issues when eating/drinking.

## Current Behavior

The hatchling triceratops currently has no drinking animation and increases to adult size when eating.

Drinking (no animation):

![image](https://user-images.githubusercontent.com/30550499/38165500-476bbd96-350c-11e8-8bc1-16153f67bfb3.png)

Eating (size increases):

![image](https://user-images.githubusercontent.com/30550499/38165495-36c1fd48-350c-11e8-9905-0e2421726a21.png)

Although they have issues visually, the hunger/thirst values do increase as intended.

## Steps to reproduce

1. Spawn as hatchling Trike
2. Drink and watch no animation play.
3. Eat and watch size increase.

## Build Information

> **Game Version:** 0.1.35.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Paleocolour** [comment]
Should be fixed next patch.
