### ISSUE TITLE
Juvenile Trike hunger does not increase/decay

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#72]
## Expected Behavior

Juvenile Triceratops hunger should increase when growing and decay over time.

## Current Behavior

The juvenile Triceratops hunger currently:

- Starts at 150 and gradually decreases.
- Does not decay.

This effectively allows you to survive until sub adult without eating.

At .8:
![image](https://user-images.githubusercontent.com/30550499/38169070-96ea3924-3557-11e8-886c-98498c4eef6c.png)

At .81: 
![image](https://user-images.githubusercontent.com/30550499/38169064-816bde40-3557-11e8-9a54-c378b8eedf29.png)

## Steps to reproduce

1. Spawn as juvenile Trike.
2. Hit ctrl + insert for debug menu.
3. Watch as you grow that your max hunger decreases and your hunger never decays.

## Build Information

> **Game Version:** 0.1.35.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.35.9
