### ISSUE TITLE
Entering spectator mode on characterselect causes server crash

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#73]
## Expected Behavior

Hitting spectator mode button when on CharacterSelect screen should not cause the server to crash.

## Current Behavior

Hitting the spectator mode button while on CharacterSelect screen causes the server to crash.

## Steps to reproduce

1. Don't spawn as anything.
2. Hit \ key for spectator.
3. Watch everyone lose their progress. _Evil grin_

## Build Information

> **Game Version:** 0.1.35.8 (dev)

> **Operating System**: Windows

> **Network Role**: Dedicated, listen.

**Comment by looterz** [comment]
Fixed in 0.1.35.9
