### ISSUE TITLE
Game Locked when hitting "Enter" while HUD is hidden

### ISSUE THREAD

**Issue by melmelMeliora** [TheIsleGame/bugs#75]
Development Branch Server 3
0.1.36.0
April 1, 2018

1) Hide your HUD by hitting ctrl+H

2) Hit enter.

3) Controls lock up but game is not frozen. Only way to esc is to force esc.

Tested out esc, tested tab- able to open and close without issues.

Recreated by multiple users.

https://www.youtube.com/watch?v=YO7Jw12SDWc&feature=youtu.be

**Comment by Hypno123** [comment]
Fixed in 0.1.36.1
