### ISSUE TITLE
Sub adult rex bite damage does not scale with growth

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#78]
## Expected Behavior

As the sub adult rex gets bigger, it should do more and more damage, not immediately start with 424.

## Current Behavior

At juvenile you have 70 bite damage then immediately have 424 when progressing to sub adult. The sub adult does not increase in bite damage with growth.

At .6:

![image](https://user-images.githubusercontent.com/30550499/38368747-0458f7e6-38de-11e8-8ca9-32938c534116.png)

At .9:

![image](https://user-images.githubusercontent.com/30550499/38368765-15402444-38de-11e8-9b96-c5feb714a739.png)

## Steps to reproduce

1. Spawn as rex.
2. Grow to sub adult - check debug menu and see damage is 424.
3. Grow and notice bite damage does not increase with growth (always stays at 424.)

## Build Information

> **Game Version:** 0.1.36.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.36.3
