### ISSUE TITLE
Player count doesn't show on scoreboard when over max slots

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#79]
## Expected Behavior

The player count should show on the scoreboard regardless of if the server has surpassed the max amount of players.

## Current Behavior

When the max player count is surpassed, the population is no longer advertised on the bottom left of the scoreboard.

![image](https://user-images.githubusercontent.com/30550499/38401703-38f573dc-394f-11e8-8dda-a6d200a5a948.png)

Screenshot taken with 84/80 players on the server.

## Steps to reproduce

1. Enter a full server.
2. Check the population in the bottom right.
3. It will display " / " if over the limit.

## Build Information

> **Game Version:** 0.1.36.2 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.36.3
