### ISSUE TITLE
No way to be nested without suiciding first

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#83]
## Expected Behavior

Players should be able to be nested regardless of if they are already spawned in as something else.

## Current Behavior

If a player is already spawned in, they are forced to suicide or be killed so that they can be nested. (The nest button is only on the characterscreen - could be added to escape menu too.)

## Steps to reproduce

1. Spawn as anything.
2. Accept a nest invite from another player.
3. Realize you have to suicide to be able to be nested.

## Build Information

> **Game Version:** 0.1.36.6 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Closing this in preparation for the new nest system.
