### ISSUE TITLE
Female baby icon used for males

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#84]
## Expected Behavior

If your gender is male, you should have a male icon when nested.

## Current Behavior

The female icon is given to male babies as well as female.

## Steps to reproduce

1. Spawn as anything.
2. Place a nest.
3. Look at your baby's icon. It will always be female, even if their gender is male.

## Build Information

> **Game Version:** 0.1.36.6 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Closing this in preparation for the new nest system.
