### ISSUE TITLE
Sub-adult rex being able to move mid-transition animation

### ISSUE THREAD

**Issue by FatLemur** [TheIsleGame/bugs#87]
## Expected Behavior

The sub rex should not be able to move until the animation is complete

## Current Behavior

The rex is able to move mid-animation, resulting in sliding

## Steps to reproduce

Movement keys while the getting up animation plays. https://www.youtube.com/watch?v=KTZioSPi27U

## Build Information

> **Game Version:** 0.1.36.6 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.36.7
