### ISSUE TITLE
Utahraptor nests juveniles instead of hatchlings

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#91]
## Expected Behavior

Utahraptors should be nesting in hatchlings, not juveniles.

## Current Behavior

Utahraptors are currently nested in as juveniles rather than hatchlings.

![image](https://user-images.githubusercontent.com/30550499/38771707-9ce13d46-401f-11e8-8a5e-010ba2ae468a.png)

(Screenshot from Chimichanga immediately after being nested.)

## Steps to reproduce

1. Be adult female utahraptor.
2. Nest in a friend.
3. Tell them to check their growth. It says 0.6 instead of 0.2.

## Build Information

> **Game Version:** 0.1.36.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.38.4
