### ISSUE TITLE
Playerlist will show kicked /banned player's name till reopening it

### ISSUE THREAD

**Issue by Queenz29** [TheIsleGame/bugs#96]
## Expected Behavior

When you kick or ban someone as admin using the symbols in the playerlist you expect the kicked player to vanish from it.

## Current Behavior

Kicked or banned player name will only vanish by reopening the playerlist. ( Can be seen in the screen )
![playerlist](https://user-images.githubusercontent.com/37963687/38772054-493b6c16-402e-11e8-96bb-49183050aa90.png)

## Steps to reproduce

1. Log into a Server
2. Kick someone using the symbols in the playerlist
3. Watch how the Chat says 'Kicked PlayerX for Kicked by admin'
4. Watch how his/her name will stay in the playerlist till reopening it.

## Build Information

> **Game Version:** 0.1.36.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Not the biggest issue - the player list just doesn't auto-update. This includes kicks, bans, leaving, joining etc.

**Comment by looterz** [comment]
This is intended, atleast for now.
