### ISSUE TITLE
Chinese characters do not show in spectator

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#98]
## Expected Behavior

Chinese characters should show on names when in spectator mode.

## Current Behavior

Chinese characters currently show as [ in spectator mode.

![image](https://user-images.githubusercontent.com/30550499/38879200-a9aeddca-425a-11e8-8c38-962815a5ee11.png)

## Steps to reproduce

1. Spawn in.
2. Go to spectator with \
3. Find a person with Chinese characters in their name and see that it shows as [.

## Build Information

> **Game Version:** 0.1.36.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.37.0
