### ISSUE TITLE
Sandbox (I.E non-nested) Hatchling Rex cannot turn while trotting or sprinting

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#99]
## Expected Behavior

Expected hatchling Rex to be able to turn while trotting and sprinting

## Current Behavior

On sandbox, Hatchling Rex cannot turn while trotting or sprinting

Video evidence:
https://www.youtube.com/watch?v=HGzjWuiFGjQ&feature=youtu.be
## Steps to reproduce

-select hatch Rex
-use A or D keys to move around while trotting or sprinting
-unable to turn unless walking, limping or crouching

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/1921447/TheIsle.log)

> **Game Version:** 0.1.36.8 (development)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
I'm able to turn as hatchling rex both trotting and sprinting. Might be an issue on your end?

**Comment by ExtraHu3** [comment]
Seems to only happen to no nested hatchlings (I.E sandbox hatchlings)

**Comment by Hypno123** [comment]
Fixed in 0.1.38.4
